// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: arena.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const finishArenaMatch = `-- name: FinishArenaMatch :exec
UPDATE arena_match
SET status = 'finished', finished_at = now(), end_reason = $2
WHERE id = $1 AND status <> 'finished'
`

type FinishArenaMatchParams struct {
	ID        uuid.UUID   `json:"id"`
	EndReason pgtype.Text `json:"end_reason"`
}

func (q *Queries) FinishArenaMatch(ctx context.Context, arg FinishArenaMatchParams) error {
	_, err := q.db.Exec(ctx, finishArenaMatch, arg.ID, arg.EndReason)
	return err
}

const getArenaMatchPlayer = `-- name: GetArenaMatchPlayer :one
SELECT match_id, profile_id, slot, locale, score, correct_count, total_response_ms, outcome, rating_before, rating_after, rating_delta, disconnected_at, joined_at FROM arena_match_player
WHERE match_id = $1 AND profile_id = $2
`

type GetArenaMatchPlayerParams struct {
	MatchID   uuid.UUID `json:"match_id"`
	ProfileID uuid.UUID `json:"profile_id"`
}

func (q *Queries) GetArenaMatchPlayer(ctx context.Context, arg GetArenaMatchPlayerParams) (ArenaMatchPlayer, error) {
	row := q.db.QueryRow(ctx, getArenaMatchPlayer, arg.MatchID, arg.ProfileID)
	var i ArenaMatchPlayer
	err := row.Scan(
		&i.MatchID,
		&i.ProfileID,
		&i.Slot,
		&i.Locale,
		&i.Score,
		&i.CorrectCount,
		&i.TotalResponseMs,
		&i.Outcome,
		&i.RatingBefore,
		&i.RatingAfter,
		&i.RatingDelta,
		&i.DisconnectedAt,
		&i.JoinedAt,
	)
	return i, err
}

const insertArenaAnswer = `-- name: InsertArenaAnswer :exec
INSERT INTO arena_answer (
  match_id, profile_id, question_id, position, answer_id, is_correct, response_ms, points, answered_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertArenaAnswerParams struct {
	MatchID    uuid.UUID          `json:"match_id"`
	ProfileID  uuid.UUID          `json:"profile_id"`
	QuestionID uuid.UUID          `json:"question_id"`
	Position   int16              `json:"position"`
	AnswerID   uuid.NullUUID      `json:"answer_id"`
	IsCorrect  bool               `json:"is_correct"`
	ResponseMs pgtype.Int4        `json:"response_ms"`
	Points     int16              `json:"points"`
	AnsweredAt pgtype.Timestamptz `json:"answered_at"`
}

func (q *Queries) InsertArenaAnswer(ctx context.Context, arg InsertArenaAnswerParams) error {
	_, err := q.db.Exec(ctx, insertArenaAnswer,
		arg.MatchID,
		arg.ProfileID,
		arg.QuestionID,
		arg.Position,
		arg.AnswerID,
		arg.IsCorrect,
		arg.ResponseMs,
		arg.Points,
		arg.AnsweredAt,
	)
	return err
}

const insertArenaMatch = `-- name: InsertArenaMatch :one
INSERT INTO arena_match (question_ids, question_time_sec, status, started_at)
VALUES ($1, $2, 'in_progress', now())
RETURNING id, status, question_ids, question_time_sec, created_at, started_at, finished_at, end_reason
`

type InsertArenaMatchParams struct {
	QuestionIds     []uuid.UUID `json:"question_ids"`
	QuestionTimeSec int16       `json:"question_time_sec"`
}

func (q *Queries) InsertArenaMatch(ctx context.Context, arg InsertArenaMatchParams) (ArenaMatch, error) {
	row := q.db.QueryRow(ctx, insertArenaMatch, arg.QuestionIds, arg.QuestionTimeSec)
	var i ArenaMatch
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.QuestionIds,
		&i.QuestionTimeSec,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
		&i.EndReason,
	)
	return i, err
}

const insertArenaMatchPlayer = `-- name: InsertArenaMatchPlayer :exec
INSERT INTO arena_match_player (
  match_id, profile_id, slot, locale, score, correct_count, total_response_ms,
  outcome, rating_before, rating_after, rating_delta
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertArenaMatchPlayerParams struct {
	MatchID         uuid.UUID   `json:"match_id"`
	ProfileID       uuid.UUID   `json:"profile_id"`
	Slot            int16       `json:"slot"`
	Locale          string      `json:"locale"`
	Score           int32       `json:"score"`
	CorrectCount    int16       `json:"correct_count"`
	TotalResponseMs int32       `json:"total_response_ms"`
	Outcome         pgtype.Text `json:"outcome"`
	RatingBefore    pgtype.Int4 `json:"rating_before"`
	RatingAfter     pgtype.Int4 `json:"rating_after"`
	RatingDelta     pgtype.Int4 `json:"rating_delta"`
}

func (q *Queries) InsertArenaMatchPlayer(ctx context.Context, arg InsertArenaMatchPlayerParams) error {
	_, err := q.db.Exec(ctx, insertArenaMatchPlayer,
		arg.MatchID,
		arg.ProfileID,
		arg.Slot,
		arg.Locale,
		arg.Score,
		arg.CorrectCount,
		arg.TotalResponseMs,
		arg.Outcome,
		arg.RatingBefore,
		arg.RatingAfter,
		arg.RatingDelta,
	)
	return err
}

const listArenaMatchesForProfile = `-- name: ListArenaMatchesForProfile :many
SELECT m.id, m.status, m.finished_at, m.end_reason, m.created_at,
       p.slot, p.score, p.correct_count, p.outcome,
       p.rating_before, p.rating_after, p.rating_delta
FROM arena_match_player p
JOIN arena_match m ON m.id = p.match_id
WHERE p.profile_id = $1
ORDER BY p.joined_at DESC
LIMIT $2
`

type ListArenaMatchesForProfileParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Limit     int32     `json:"limit"`
}

type ListArenaMatchesForProfileRow struct {
	ID           uuid.UUID          `json:"id"`
	Status       string             `json:"status"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	EndReason    pgtype.Text        `json:"end_reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Slot         int16              `json:"slot"`
	Score        int32              `json:"score"`
	CorrectCount int16              `json:"correct_count"`
	Outcome      pgtype.Text        `json:"outcome"`
	RatingBefore pgtype.Int4        `json:"rating_before"`
	RatingAfter  pgtype.Int4        `json:"rating_after"`
	RatingDelta  pgtype.Int4        `json:"rating_delta"`
}

func (q *Queries) ListArenaMatchesForProfile(ctx context.Context, arg ListArenaMatchesForProfileParams) ([]ListArenaMatchesForProfileRow, error) {
	rows, err := q.db.Query(ctx, listArenaMatchesForProfile, arg.ProfileID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArenaMatchesForProfileRow
	for rows.Next() {
		var i ListArenaMatchesForProfileRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.FinishedAt,
			&i.EndReason,
			&i.CreatedAt,
			&i.Slot,
			&i.Score,
			&i.CorrectCount,
			&i.Outcome,
			&i.RatingBefore,
			&i.RatingAfter,
			&i.RatingDelta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCorrectAnswerIDsForQuestions = `-- name: ListCorrectAnswerIDsForQuestions :many
SELECT question_id, id AS answer_id
FROM answer
WHERE question_id = ANY($1::uuid[]) AND is_correct = true
`

type ListCorrectAnswerIDsForQuestionsRow struct {
	QuestionID uuid.UUID `json:"question_id"`
	AnswerID   uuid.UUID `json:"answer_id"`
}

func (q *Queries) ListCorrectAnswerIDsForQuestions(ctx context.Context, dollar_1 []uuid.UUID) ([]ListCorrectAnswerIDsForQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listCorrectAnswerIDsForQuestions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCorrectAnswerIDsForQuestionsRow
	for rows.Next() {
		var i ListCorrectAnswerIDsForQuestionsRow
		if err := rows.Scan(&i.QuestionID, &i.AnswerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
