// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const activeEntitlementEnd = `-- name: ActiveEntitlementEnd :one
SELECT ends_at FROM entitlement
WHERE profile_id = $1 AND ends_at > now()
ORDER BY ends_at DESC LIMIT 1
`

func (q *Queries) ActiveEntitlementEnd(ctx context.Context, profileID uuid.UUID) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, activeEntitlementEnd, profileID)
	var ends_at pgtype.Timestamptz
	err := row.Scan(&ends_at)
	return ends_at, err
}

const clampAllEntitlementsForPayment = `-- name: ClampAllEntitlementsForPayment :exec
UPDATE entitlement
SET ends_at = CASE
      WHEN starts_at >= $1::timestamptz THEN starts_at + interval '1 second'
      ELSE $1::timestamptz
    END,
    note = note || $2
WHERE payment_id = $3 AND ends_at > $1::timestamptz
`

type ClampAllEntitlementsForPaymentParams struct {
	ClampTo    pgtype.Timestamptz `json:"clamp_to"`
	NoteSuffix string             `json:"note_suffix"`
	PaymentID  uuid.NullUUID      `json:"payment_id"`
}

// Clamps purchase + referral_buyer rows for one payment (refund path).
func (q *Queries) ClampAllEntitlementsForPayment(ctx context.Context, arg ClampAllEntitlementsForPaymentParams) error {
	_, err := q.db.Exec(ctx, clampAllEntitlementsForPayment, arg.ClampTo, arg.NoteSuffix, arg.PaymentID)
	return err
}

const clampEntitlementEnd = `-- name: ClampEntitlementEnd :exec
UPDATE entitlement
SET ends_at = $2,
    note = note || $3
WHERE id = $1 AND ends_at > $2
`

type ClampEntitlementEndParams struct {
	ID     uuid.UUID          `json:"id"`
	EndsAt pgtype.Timestamptz `json:"ends_at"`
	Note   string             `json:"note"`
}

func (q *Queries) ClampEntitlementEnd(ctx context.Context, arg ClampEntitlementEndParams) error {
	_, err := q.db.Exec(ctx, clampEntitlementEnd, arg.ID, arg.EndsAt, arg.Note)
	return err
}

const consumeOTP = `-- name: ConsumeOTP :exec
UPDATE otp_challenge SET consumed = true WHERE id = $1
`

func (q *Queries) ConsumeOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeOTP, id)
	return err
}

const createOTPChallenge = `-- name: CreateOTPChallenge :one
INSERT INTO otp_challenge (phone, code_hash, channel, expires_at)
VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateOTPChallengeParams struct {
	Phone     string             `json:"phone"`
	CodeHash  string             `json:"code_hash"`
	Channel   string             `json:"channel"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOTPChallenge(ctx context.Context, arg CreateOTPChallengeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createOTPChallenge,
		arg.Phone,
		arg.CodeHash,
		arg.Channel,
		arg.ExpiresAt,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createProfile = `-- name: CreateProfile :one
INSERT INTO profile (phone, referral_code, password_hash, name)
VALUES ($1, $2, $3, $4) RETURNING id, phone, name, region, district, birth_date, locale_pref, theme_pref, role, referral_code, referred_by, status, created_at, password_hash, referral_commission_percent, bypass_variant_progress, kind
`

type CreateProfileParams struct {
	Phone        string      `json:"phone"`
	ReferralCode pgtype.Text `json:"referral_code"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Name         string      `json:"name"`
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error) {
	row := q.db.QueryRow(ctx, createProfile,
		arg.Phone,
		arg.ReferralCode,
		arg.PasswordHash,
		arg.Name,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Region,
		&i.District,
		&i.BirthDate,
		&i.LocalePref,
		&i.ThemePref,
		&i.Role,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.Status,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.ReferralCommissionPercent,
		&i.BypassVariantProgress,
		&i.Kind,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_token (profile_id, token_hash, expires_at) VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	ProfileID uuid.UUID          `json:"profile_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.ProfileID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const deleteRefreshToken = `-- name: DeleteRefreshToken :exec
DELETE FROM refresh_token WHERE id = $1
`

func (q *Queries) DeleteRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshToken, id)
	return err
}

const getEntitlementByPaymentID = `-- name: GetEntitlementByPaymentID :one
SELECT id, profile_id, source, starts_at, ends_at, payment_id, created_by, note, created_at
FROM entitlement
WHERE payment_id = $1
LIMIT 1
`

func (q *Queries) GetEntitlementByPaymentID(ctx context.Context, paymentID uuid.NullUUID) (Entitlement, error) {
	row := q.db.QueryRow(ctx, getEntitlementByPaymentID, paymentID)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Source,
		&i.StartsAt,
		&i.EndsAt,
		&i.PaymentID,
		&i.CreatedBy,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPurchaseEntitlement = `-- name: GetLatestPurchaseEntitlement :one
SELECT id, profile_id, source, starts_at, ends_at, payment_id, created_by, note, created_at
FROM entitlement
WHERE profile_id = $1 AND source = 'purchase'
ORDER BY created_at DESC
LIMIT 1
`

// Most recent purchase-sourced grant for learner-facing proration messaging.
func (q *Queries) GetLatestPurchaseEntitlement(ctx context.Context, profileID uuid.UUID) (Entitlement, error) {
	row := q.db.QueryRow(ctx, getLatestPurchaseEntitlement, profileID)
	var i Entitlement
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Source,
		&i.StartsAt,
		&i.EndsAt,
		&i.PaymentID,
		&i.CreatedBy,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getProfileByID = `-- name: GetProfileByID :one
SELECT id, phone, name, region, district, birth_date, locale_pref, theme_pref, role, referral_code, referred_by, status, created_at, password_hash, referral_commission_percent, bypass_variant_progress, kind FROM profile WHERE id = $1
`

func (q *Queries) GetProfileByID(ctx context.Context, id uuid.UUID) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Region,
		&i.District,
		&i.BirthDate,
		&i.LocalePref,
		&i.ThemePref,
		&i.Role,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.Status,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.ReferralCommissionPercent,
		&i.BypassVariantProgress,
		&i.Kind,
	)
	return i, err
}

const getProfileKind = `-- name: GetProfileKind :one
SELECT kind FROM profile WHERE id = $1
`

// Used by leaderboard.Service.RecordPoint to keep station shadow profiles
// (kind = 'station') out of the live leaderboard write path before it ever
// touches Billing.Status or Redis. Selecting just the column, rather than
// reusing GetProfileByID, keeps the hot answer-submission path from paying
// for columns it doesn't need.
func (q *Queries) GetProfileKind(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getProfileKind, id)
	var kind string
	err := row.Scan(&kind)
	return kind, err
}

const getProfileByPhone = `-- name: GetProfileByPhone :one
SELECT id, phone, name, region, district, birth_date, locale_pref, theme_pref, role, referral_code, referred_by, status, created_at, password_hash, referral_commission_percent, bypass_variant_progress, kind FROM profile WHERE phone = $1
`

func (q *Queries) GetProfileByPhone(ctx context.Context, phone string) (Profile, error) {
	row := q.db.QueryRow(ctx, getProfileByPhone, phone)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Region,
		&i.District,
		&i.BirthDate,
		&i.LocalePref,
		&i.ThemePref,
		&i.Role,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.Status,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.ReferralCommissionPercent,
		&i.BypassVariantProgress,
		&i.Kind,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, profile_id, token_hash, expires_at, revoked_at, created_at FROM refresh_token WHERE token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :exec
UPDATE otp_challenge SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempts, id)
	return err
}

const insertEntitlement = `-- name: InsertEntitlement :one
INSERT INTO entitlement (profile_id, source, starts_at, ends_at, note, created_by, payment_id)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id
`

type InsertEntitlementParams struct {
	ProfileID uuid.UUID          `json:"profile_id"`
	Source    string             `json:"source"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	Note      string             `json:"note"`
	CreatedBy uuid.NullUUID      `json:"created_by"`
	PaymentID uuid.NullUUID      `json:"payment_id"`
}

func (q *Queries) InsertEntitlement(ctx context.Context, arg InsertEntitlementParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertEntitlement,
		arg.ProfileID,
		arg.Source,
		arg.StartsAt,
		arg.EndsAt,
		arg.Note,
		arg.CreatedBy,
		arg.PaymentID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const latestOTPChallenge = `-- name: LatestOTPChallenge :one
SELECT id, phone, code_hash, channel, expires_at, attempts, consumed, created_at FROM otp_challenge
WHERE phone = $1 AND consumed = false
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) LatestOTPChallenge(ctx context.Context, phone string) (OtpChallenge, error) {
	row := q.db.QueryRow(ctx, latestOTPChallenge, phone)
	var i OtpChallenge
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CodeHash,
		&i.Channel,
		&i.ExpiresAt,
		&i.Attempts,
		&i.Consumed,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllRefreshTokens = `-- name: RevokeAllRefreshTokens :exec
UPDATE refresh_token SET revoked_at = now() WHERE profile_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokens(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokens, profileID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_token SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const setBypassVariantProgress = `-- name: SetBypassVariantProgress :exec
UPDATE profile SET bypass_variant_progress = $2 WHERE id = $1
`

type SetBypassVariantProgressParams struct {
	ID                    uuid.UUID `json:"id"`
	BypassVariantProgress bool      `json:"bypass_variant_progress"`
}

func (q *Queries) SetBypassVariantProgress(ctx context.Context, arg SetBypassVariantProgressParams) error {
	_, err := q.db.Exec(ctx, setBypassVariantProgress, arg.ID, arg.BypassVariantProgress)
	return err
}

const setPasswordHashIfNull = `-- name: SetPasswordHashIfNull :execrows
UPDATE profile
SET password_hash = $2
WHERE phone = $1 AND password_hash IS NULL
`

type SetPasswordHashIfNullParams struct {
	Phone        string      `json:"phone"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) SetPasswordHashIfNull(ctx context.Context, arg SetPasswordHashIfNullParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPasswordHashIfNull, arg.Phone, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProfileMe = `-- name: UpdateProfileMe :one
UPDATE profile SET
  name = $2, region = $3, district = $4, birth_date = $5,
  locale_pref = $6, theme_pref = $7
WHERE id = $1 RETURNING id, phone, name, region, district, birth_date, locale_pref, theme_pref, role, referral_code, referred_by, status, created_at, password_hash, referral_commission_percent, bypass_variant_progress, kind
`

type UpdateProfileMeParams struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	Region     string      `json:"region"`
	District   string      `json:"district"`
	BirthDate  pgtype.Date `json:"birth_date"`
	LocalePref string      `json:"locale_pref"`
	ThemePref  string      `json:"theme_pref"`
}

func (q *Queries) UpdateProfileMe(ctx context.Context, arg UpdateProfileMeParams) (Profile, error) {
	row := q.db.QueryRow(ctx, updateProfileMe,
		arg.ID,
		arg.Name,
		arg.Region,
		arg.District,
		arg.BirthDate,
		arg.LocalePref,
		arg.ThemePref,
	)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Region,
		&i.District,
		&i.BirthDate,
		&i.LocalePref,
		&i.ThemePref,
		&i.Role,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.Status,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.ReferralCommissionPercent,
		&i.BypassVariantProgress,
		&i.Kind,
	)
	return i, err
}
