// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: avatar.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearProfileAvatarUnlessVerified = `-- name: ClearProfileAvatarUnlessVerified :one
WITH old AS (
  SELECT o.id, o.avatar_key FROM profile o WHERE o.id = $1 FOR UPDATE
)
UPDATE profile p
SET avatar_key = NULL, avatar_source = NULL, avatar_updated_at = NULL
FROM old
WHERE p.id = old.id
  AND (p.avatar_key IS NOT NULL OR p.avatar_updated_at IS NOT NULL)
  AND (p.kind <> 'user' OR NOT EXISTS (
    SELECT 1 FROM telegram_account ta
    WHERE ta.profile_id = p.id AND ta.phone_verified_at IS NOT NULL
  ))
RETURNING old.avatar_key AS previous_key
`

// Drops the photo of a profile that no longer has a phone-verified link (or
// is not a learner). Judged in the same statement as the write, so a link
// re-proven concurrently keeps its photo. No row = nothing to clear.
func (q *Queries) ClearProfileAvatarUnlessVerified(ctx context.Context, profileID uuid.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, clearProfileAvatarUnlessVerified, profileID)
	var previous_key pgtype.Text
	err := row.Scan(&previous_key)
	return previous_key, err
}

const getProfileAvatarState = `-- name: GetProfileAvatarState :one
SELECT p.kind, p.avatar_key, p.avatar_updated_at,
       ta.tg_user_id AS verified_tg_user_id
FROM profile p
LEFT JOIN telegram_account ta
       ON ta.profile_id = p.id AND ta.phone_verified_at IS NOT NULL
WHERE p.id = $1
`

type GetProfileAvatarStateRow struct {
	Kind             string             `json:"kind"`
	AvatarKey        pgtype.Text        `json:"avatar_key"`
	AvatarUpdatedAt  pgtype.Timestamptz `json:"avatar_updated_at"`
	VerifiedTgUserID pgtype.Int8        `json:"verified_tg_user_id"`
}

// Everything the avatar code decides on, read in one round trip: the stored
// photo, when it was last checked, and the Telegram user of the profile's
// phone-verified link (NULL = none, so no photo may be shown or fetched).
func (q *Queries) GetProfileAvatarState(ctx context.Context, profileID uuid.UUID) (GetProfileAvatarStateRow, error) {
	row := q.db.QueryRow(ctx, getProfileAvatarState, profileID)
	var i GetProfileAvatarStateRow
	err := row.Scan(
		&i.Kind,
		&i.AvatarKey,
		&i.AvatarUpdatedAt,
		&i.VerifiedTgUserID,
	)
	return i, err
}

const setProfileTelegramAvatar = `-- name: SetProfileTelegramAvatar :one
WITH old AS (
  SELECT o.id, o.avatar_key FROM profile o WHERE o.id = $3 FOR UPDATE
)
UPDATE profile p
SET avatar_key = $1::text,
    avatar_source = CASE WHEN $1::text IS NULL THEN NULL ELSE 'telegram' END,
    avatar_updated_at = now()
FROM old
WHERE p.id = old.id
  AND p.kind = 'user'
  AND EXISTS (
    SELECT 1 FROM telegram_account ta
    WHERE ta.profile_id = p.id
      AND ta.tg_user_id = $2
      AND ta.phone_verified_at IS NOT NULL
  )
RETURNING old.avatar_key AS previous_key
`

type SetProfileTelegramAvatarParams struct {
	AvatarKey pgtype.Text `json:"avatar_key"`
	TgUserID  int64       `json:"tg_user_id"`
	ProfileID uuid.UUID   `json:"profile_id"`
}

// Records a finished Telegram check (avatar_key NULL = no usable photo) and
// returns the key it replaced, for the caller to delete. It only applies
// while the profile is a learner whose phone-verified link still points at
// the Telegram user the photo came from: a fetch that raced an unlink or a
// re-link writes nothing (no row), and the caller drops the object it just
// uploaded. The CTE locks the row so the returned previous key is the one
// actually overwritten.
func (q *Queries) SetProfileTelegramAvatar(ctx context.Context, arg SetProfileTelegramAvatarParams) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, setProfileTelegramAvatar, arg.AvatarKey, arg.TgUserID, arg.ProfileID)
	var previous_key pgtype.Text
	err := row.Scan(&previous_key)
	return previous_key, err
}
