// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listActiveTariffs = `-- name: ListActiveTariffs :many
SELECT t.code, t.days, t.price_uzs, t.old_price_uzs, t.badge,
       COALESCE(tr.name, ftr.name, t.code) AS name,
       COALESCE(tr.description, ftr.description, '') AS description
FROM tariff t
LEFT JOIN tariff_translation tr ON tr.tariff_id = t.id AND tr.locale = $1
LEFT JOIN tariff_translation ftr ON ftr.tariff_id = t.id AND ftr.locale = 'uz-Latn'
WHERE t.active = true
ORDER BY t.sort_order, t.code
`

type ListActiveTariffsRow struct {
	Code        string      `json:"code"`
	Days        int32       `json:"days"`
	PriceUzs    int64       `json:"price_uzs"`
	OldPriceUzs pgtype.Int8 `json:"old_price_uzs"`
	Badge       pgtype.Text `json:"badge"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

// Localized tariff list with uz-Latn fallback (mirrors ListCategories).
func (q *Queries) ListActiveTariffs(ctx context.Context, locale string) ([]ListActiveTariffsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTariffs, locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTariffsRow
	for rows.Next() {
		var i ListActiveTariffsRow
		if err := rows.Scan(
			&i.Code,
			&i.Days,
			&i.PriceUzs,
			&i.OldPriceUzs,
			&i.Badge,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
