// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPaymeTransaction = `-- name: CancelPaymeTransaction :exec
UPDATE payme_transaction SET state = $2, reason = $3, cancel_time = $4 WHERE payme_id = $1
`

type CancelPaymeTransactionParams struct {
	PaymeID    string      `json:"payme_id"`
	State      int32       `json:"state"`
	Reason     pgtype.Int4 `json:"reason"`
	CancelTime int64       `json:"cancel_time"`
}

func (q *Queries) CancelPaymeTransaction(ctx context.Context, arg CancelPaymeTransactionParams) error {
	_, err := q.db.Exec(ctx, cancelPaymeTransaction,
		arg.PaymeID,
		arg.State,
		arg.Reason,
		arg.CancelTime,
	)
	return err
}

const confirmClickTransaction = `-- name: ConfirmClickTransaction :exec
UPDATE click_transaction SET state = 1, confirmed_at = now() WHERE id = $1
`

func (q *Queries) ConfirmClickTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, confirmClickTransaction, id)
	return err
}

const createClickTransaction = `-- name: CreateClickTransaction :one
INSERT INTO click_transaction (click_trans_id, click_paydoc_id, payment_id, amount_uzs)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateClickTransactionParams struct {
	ClickTransID  string      `json:"click_trans_id"`
	ClickPaydocID pgtype.Text `json:"click_paydoc_id"`
	PaymentID     uuid.UUID   `json:"payment_id"`
	AmountUzs     int64       `json:"amount_uzs"`
}

func (q *Queries) CreateClickTransaction(ctx context.Context, arg CreateClickTransactionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createClickTransaction,
		arg.ClickTransID,
		arg.ClickPaydocID,
		arg.PaymentID,
		arg.AmountUzs,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createPaymeTransaction = `-- name: CreatePaymeTransaction :exec
INSERT INTO payme_transaction (payme_id, payment_id, amount_tiyin, state, create_time)
VALUES ($1, $2, $3, 1, $4)
`

type CreatePaymeTransactionParams struct {
	PaymeID     string    `json:"payme_id"`
	PaymentID   uuid.UUID `json:"payment_id"`
	AmountTiyin int64     `json:"amount_tiyin"`
	CreateTime  int64     `json:"create_time"`
}

func (q *Queries) CreatePaymeTransaction(ctx context.Context, arg CreatePaymeTransactionParams) error {
	_, err := q.db.Exec(ctx, createPaymeTransaction,
		arg.PaymeID,
		arg.PaymentID,
		arg.AmountTiyin,
		arg.CreateTime,
	)
	return err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payment (profile_id, tariff_id, amount_uzs, provider, status, idempotency_key)
VALUES ($1, $2, $3, $4, 'created', $5)
RETURNING id
`

type CreatePaymentParams struct {
	ProfileID      uuid.UUID `json:"profile_id"`
	TariffID       uuid.UUID `json:"tariff_id"`
	AmountUzs      int64     `json:"amount_uzs"`
	Provider       string    `json:"provider"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.ProfileID,
		arg.TariffID,
		arg.AmountUzs,
		arg.Provider,
		arg.IdempotencyKey,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getActiveClickTxByPayment = `-- name: GetActiveClickTxByPayment :one
SELECT id, state FROM click_transaction WHERE payment_id = $1 AND state IN (0, 1) LIMIT 1
`

type GetActiveClickTxByPaymentRow struct {
	ID    uuid.UUID `json:"id"`
	State int32     `json:"state"`
}

func (q *Queries) GetActiveClickTxByPayment(ctx context.Context, paymentID uuid.UUID) (GetActiveClickTxByPaymentRow, error) {
	row := q.db.QueryRow(ctx, getActiveClickTxByPayment, paymentID)
	var i GetActiveClickTxByPaymentRow
	err := row.Scan(&i.ID, &i.State)
	return i, err
}

const getActivePaymeTxByPayment = `-- name: GetActivePaymeTxByPayment :one
SELECT payme_id, state FROM payme_transaction
WHERE payment_id = $1 AND state IN (1, 2) LIMIT 1
`

type GetActivePaymeTxByPaymentRow struct {
	PaymeID string `json:"payme_id"`
	State   int32  `json:"state"`
}

func (q *Queries) GetActivePaymeTxByPayment(ctx context.Context, paymentID uuid.UUID) (GetActivePaymeTxByPaymentRow, error) {
	row := q.db.QueryRow(ctx, getActivePaymeTxByPayment, paymentID)
	var i GetActivePaymeTxByPaymentRow
	err := row.Scan(&i.PaymeID, &i.State)
	return i, err
}

const getActiveTariffByCode = `-- name: GetActiveTariffByCode :one
SELECT id, days, price_uzs FROM tariff WHERE code = $1 AND active = true
`

type GetActiveTariffByCodeRow struct {
	ID       uuid.UUID `json:"id"`
	Days     int32     `json:"days"`
	PriceUzs int64     `json:"price_uzs"`
}

func (q *Queries) GetActiveTariffByCode(ctx context.Context, code string) (GetActiveTariffByCodeRow, error) {
	row := q.db.QueryRow(ctx, getActiveTariffByCode, code)
	var i GetActiveTariffByCodeRow
	err := row.Scan(&i.ID, &i.Days, &i.PriceUzs)
	return i, err
}

const getClickTransactionByClickTransID = `-- name: GetClickTransactionByClickTransID :one
SELECT id, click_trans_id, click_paydoc_id, payment_id, amount_uzs, state, reason, created_at, confirmed_at, rejected_at
FROM click_transaction WHERE click_trans_id = $1
`

func (q *Queries) GetClickTransactionByClickTransID(ctx context.Context, clickTransID string) (ClickTransaction, error) {
	row := q.db.QueryRow(ctx, getClickTransactionByClickTransID, clickTransID)
	var i ClickTransaction
	err := row.Scan(
		&i.ID,
		&i.ClickTransID,
		&i.ClickPaydocID,
		&i.PaymentID,
		&i.AmountUzs,
		&i.State,
		&i.Reason,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.RejectedAt,
	)
	return i, err
}

const getClickTransactionByID = `-- name: GetClickTransactionByID :one
SELECT id, click_trans_id, click_paydoc_id, payment_id, amount_uzs, state, reason, created_at, confirmed_at, rejected_at
FROM click_transaction WHERE id = $1
`

func (q *Queries) GetClickTransactionByID(ctx context.Context, id uuid.UUID) (ClickTransaction, error) {
	row := q.db.QueryRow(ctx, getClickTransactionByID, id)
	var i ClickTransaction
	err := row.Scan(
		&i.ID,
		&i.ClickTransID,
		&i.ClickPaydocID,
		&i.PaymentID,
		&i.AmountUzs,
		&i.State,
		&i.Reason,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.RejectedAt,
	)
	return i, err
}

const getClickTransactionByIDForUpdate = `-- name: GetClickTransactionByIDForUpdate :one
SELECT id, click_trans_id, click_paydoc_id, payment_id, amount_uzs, state, reason, created_at, confirmed_at, rejected_at
FROM click_transaction WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetClickTransactionByIDForUpdate(ctx context.Context, id uuid.UUID) (ClickTransaction, error) {
	row := q.db.QueryRow(ctx, getClickTransactionByIDForUpdate, id)
	var i ClickTransaction
	err := row.Scan(
		&i.ID,
		&i.ClickTransID,
		&i.ClickPaydocID,
		&i.PaymentID,
		&i.AmountUzs,
		&i.State,
		&i.Reason,
		&i.CreatedAt,
		&i.ConfirmedAt,
		&i.RejectedAt,
	)
	return i, err
}

const getPaymeTransaction = `-- name: GetPaymeTransaction :one
SELECT payme_id, payment_id, amount_tiyin, state, reason, create_time, perform_time, cancel_time
FROM payme_transaction WHERE payme_id = $1
`

type GetPaymeTransactionRow struct {
	PaymeID     string      `json:"payme_id"`
	PaymentID   uuid.UUID   `json:"payment_id"`
	AmountTiyin int64       `json:"amount_tiyin"`
	State       int32       `json:"state"`
	Reason      pgtype.Int4 `json:"reason"`
	CreateTime  int64       `json:"create_time"`
	PerformTime int64       `json:"perform_time"`
	CancelTime  int64       `json:"cancel_time"`
}

func (q *Queries) GetPaymeTransaction(ctx context.Context, paymeID string) (GetPaymeTransactionRow, error) {
	row := q.db.QueryRow(ctx, getPaymeTransaction, paymeID)
	var i GetPaymeTransactionRow
	err := row.Scan(
		&i.PaymeID,
		&i.PaymentID,
		&i.AmountTiyin,
		&i.State,
		&i.Reason,
		&i.CreateTime,
		&i.PerformTime,
		&i.CancelTime,
	)
	return i, err
}

const getPaymeTransactionForUpdate = `-- name: GetPaymeTransactionForUpdate :one
SELECT payme_id, payment_id, amount_tiyin, state, reason, create_time, perform_time, cancel_time
FROM payme_transaction WHERE payme_id = $1 FOR UPDATE
`

type GetPaymeTransactionForUpdateRow struct {
	PaymeID     string      `json:"payme_id"`
	PaymentID   uuid.UUID   `json:"payment_id"`
	AmountTiyin int64       `json:"amount_tiyin"`
	State       int32       `json:"state"`
	Reason      pgtype.Int4 `json:"reason"`
	CreateTime  int64       `json:"create_time"`
	PerformTime int64       `json:"perform_time"`
	CancelTime  int64       `json:"cancel_time"`
}

func (q *Queries) GetPaymeTransactionForUpdate(ctx context.Context, paymeID string) (GetPaymeTransactionForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getPaymeTransactionForUpdate, paymeID)
	var i GetPaymeTransactionForUpdateRow
	err := row.Scan(
		&i.PaymeID,
		&i.PaymentID,
		&i.AmountTiyin,
		&i.State,
		&i.Reason,
		&i.CreateTime,
		&i.PerformTime,
		&i.CancelTime,
	)
	return i, err
}

const getPaymentForPayme = `-- name: GetPaymentForPayme :one
SELECT p.id, p.profile_id, p.tariff_id, p.amount_uzs, p.status, t.days AS tariff_days
FROM payment p JOIN tariff t ON t.id = p.tariff_id
WHERE p.id = $1
`

type GetPaymentForPaymeRow struct {
	ID         uuid.UUID `json:"id"`
	ProfileID  uuid.UUID `json:"profile_id"`
	TariffID   uuid.UUID `json:"tariff_id"`
	AmountUzs  int64     `json:"amount_uzs"`
	Status     string    `json:"status"`
	TariffDays int32     `json:"tariff_days"`
}

func (q *Queries) GetPaymentForPayme(ctx context.Context, id uuid.UUID) (GetPaymentForPaymeRow, error) {
	row := q.db.QueryRow(ctx, getPaymentForPayme, id)
	var i GetPaymentForPaymeRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.TariffID,
		&i.AmountUzs,
		&i.Status,
		&i.TariffDays,
	)
	return i, err
}

const listActiveTariffs = `-- name: ListActiveTariffs :many
SELECT t.code, t.days, t.price_uzs, t.old_price_uzs, t.badge,
       COALESCE(tr.name, ftr.name, t.code) AS name,
       COALESCE(tr.description, ftr.description, '') AS description
FROM tariff t
LEFT JOIN tariff_translation tr ON tr.tariff_id = t.id AND tr.locale = $1
LEFT JOIN tariff_translation ftr ON ftr.tariff_id = t.id AND ftr.locale = 'uz-Latn'
WHERE t.active = true
ORDER BY t.sort_order, t.code
`

type ListActiveTariffsRow struct {
	Code        string      `json:"code"`
	Days        int32       `json:"days"`
	PriceUzs    int64       `json:"price_uzs"`
	OldPriceUzs pgtype.Int8 `json:"old_price_uzs"`
	Badge       pgtype.Text `json:"badge"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

// Localized tariff list with uz-Latn fallback (mirrors ListCategories).
func (q *Queries) ListActiveTariffs(ctx context.Context, locale string) ([]ListActiveTariffsRow, error) {
	rows, err := q.db.Query(ctx, listActiveTariffs, locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveTariffsRow
	for rows.Next() {
		var i ListActiveTariffsRow
		if err := rows.Scan(
			&i.Code,
			&i.Days,
			&i.PriceUzs,
			&i.OldPriceUzs,
			&i.Badge,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyPayments = `-- name: ListMyPayments :many
SELECT p.id, p.amount_uzs, p.provider, p.status, p.created_at, p.paid_at,
       t.code AS tariff_code, t.days AS tariff_days,
       COALESCE(tr.name, ftr.name, t.code) AS tariff_name
FROM payment p
JOIN tariff t ON t.id = p.tariff_id
LEFT JOIN tariff_translation tr ON tr.tariff_id = t.id AND tr.locale = $2
LEFT JOIN tariff_translation ftr ON ftr.tariff_id = t.id AND ftr.locale = 'uz-Latn'
WHERE p.profile_id = $1
ORDER BY p.created_at DESC
LIMIT $3
`

type ListMyPaymentsParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Locale    string    `json:"locale"`
	Limit     int32     `json:"limit"`
}

type ListMyPaymentsRow struct {
	ID         uuid.UUID          `json:"id"`
	AmountUzs  int64              `json:"amount_uzs"`
	Provider   string             `json:"provider"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	PaidAt     pgtype.Timestamptz `json:"paid_at"`
	TariffCode string             `json:"tariff_code"`
	TariffDays int32              `json:"tariff_days"`
	TariffName string             `json:"tariff_name"`
}

func (q *Queries) ListMyPayments(ctx context.Context, arg ListMyPaymentsParams) ([]ListMyPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listMyPayments, arg.ProfileID, arg.Locale, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyPaymentsRow
	for rows.Next() {
		var i ListMyPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountUzs,
			&i.Provider,
			&i.Status,
			&i.CreatedAt,
			&i.PaidAt,
			&i.TariffCode,
			&i.TariffDays,
			&i.TariffName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymeTransactionsByTime = `-- name: ListPaymeTransactionsByTime :many
SELECT payme_id, payment_id, amount_tiyin, state, reason, create_time, perform_time, cancel_time
FROM payme_transaction WHERE create_time >= $1 AND create_time <= $2 ORDER BY create_time
`

type ListPaymeTransactionsByTimeParams struct {
	CreateTime   int64 `json:"create_time"`
	CreateTime_2 int64 `json:"create_time_2"`
}

type ListPaymeTransactionsByTimeRow struct {
	PaymeID     string      `json:"payme_id"`
	PaymentID   uuid.UUID   `json:"payment_id"`
	AmountTiyin int64       `json:"amount_tiyin"`
	State       int32       `json:"state"`
	Reason      pgtype.Int4 `json:"reason"`
	CreateTime  int64       `json:"create_time"`
	PerformTime int64       `json:"perform_time"`
	CancelTime  int64       `json:"cancel_time"`
}

func (q *Queries) ListPaymeTransactionsByTime(ctx context.Context, arg ListPaymeTransactionsByTimeParams) ([]ListPaymeTransactionsByTimeRow, error) {
	rows, err := q.db.Query(ctx, listPaymeTransactionsByTime, arg.CreateTime, arg.CreateTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPaymeTransactionsByTimeRow
	for rows.Next() {
		var i ListPaymeTransactionsByTimeRow
		if err := rows.Scan(
			&i.PaymeID,
			&i.PaymentID,
			&i.AmountTiyin,
			&i.State,
			&i.Reason,
			&i.CreateTime,
			&i.PerformTime,
			&i.CancelTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPaymentPaid = `-- name: MarkPaymentPaid :exec
UPDATE payment SET status = 'paid', paid_at = now() WHERE id = $1
`

func (q *Queries) MarkPaymentPaid(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPaymentPaid, id)
	return err
}

const markPaymentPending = `-- name: MarkPaymentPending :exec
UPDATE payment SET status = 'pending', provider_txn_id = $2 WHERE id = $1
`

type MarkPaymentPendingParams struct {
	ID            uuid.UUID   `json:"id"`
	ProviderTxnID pgtype.Text `json:"provider_txn_id"`
}

func (q *Queries) MarkPaymentPending(ctx context.Context, arg MarkPaymentPendingParams) error {
	_, err := q.db.Exec(ctx, markPaymentPending, arg.ID, arg.ProviderTxnID)
	return err
}

const performPaymeTransaction = `-- name: PerformPaymeTransaction :exec
UPDATE payme_transaction SET state = 2, perform_time = $2 WHERE payme_id = $1
`

type PerformPaymeTransactionParams struct {
	PaymeID     string `json:"payme_id"`
	PerformTime int64  `json:"perform_time"`
}

func (q *Queries) PerformPaymeTransaction(ctx context.Context, arg PerformPaymeTransactionParams) error {
	_, err := q.db.Exec(ctx, performPaymeTransaction, arg.PaymeID, arg.PerformTime)
	return err
}

const rejectClickTransaction = `-- name: RejectClickTransaction :exec
UPDATE click_transaction SET state = -1, rejected_at = now(), reason = $2 WHERE id = $1
`

type RejectClickTransactionParams struct {
	ID     uuid.UUID   `json:"id"`
	Reason pgtype.Text `json:"reason"`
}

func (q *Queries) RejectClickTransaction(ctx context.Context, arg RejectClickTransactionParams) error {
	_, err := q.db.Exec(ctx, rejectClickTransaction, arg.ID, arg.Reason)
	return err
}

const setPaymentStatus = `-- name: SetPaymentStatus :exec
UPDATE payment SET status = $2 WHERE id = $1
`

type SetPaymentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetPaymentStatus(ctx context.Context, arg SetPaymentStatusParams) error {
	_, err := q.db.Exec(ctx, setPaymentStatus, arg.ID, arg.Status)
	return err
}
