// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: broadcast.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBroadcastCampaign = `-- name: CancelBroadcastCampaign :one
UPDATE broadcast_campaign
SET status = 'cancelled',
    finished_at = COALESCE(finished_at, now())
WHERE id = $1
  AND status IN ('queued', 'expanding', 'sending')
RETURNING id, created_by_admin, title, body, image_url, action_url, audience, channels, status, idempotency_key, recipient_total, pending_count, sent_count, failed_count, push_sent_count, push_failed_count, error_summary, created_at, queued_at, started_at, finished_at
`

func (q *Queries) CancelBroadcastCampaign(ctx context.Context, id uuid.UUID) (BroadcastCampaign, error) {
	row := q.db.QueryRow(ctx, cancelBroadcastCampaign, id)
	var i BroadcastCampaign
	err := row.Scan(
		&i.ID,
		&i.CreatedByAdmin,
		&i.Title,
		&i.Body,
		&i.ImageUrl,
		&i.ActionUrl,
		&i.Audience,
		&i.Channels,
		&i.Status,
		&i.IdempotencyKey,
		&i.RecipientTotal,
		&i.PendingCount,
		&i.SentCount,
		&i.FailedCount,
		&i.PushSentCount,
		&i.PushFailedCount,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const countBroadcastCampaigns = `-- name: CountBroadcastCampaigns :one
SELECT count(*)::int AS count
FROM broadcast_campaign
`

func (q *Queries) CountBroadcastCampaigns(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, countBroadcastCampaigns)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const countUnreadInappNotifications = `-- name: CountUnreadInappNotifications :one
SELECT count(*)::int AS count
FROM notification
WHERE profile_id = $1
  AND channel = 'inapp'
  AND read_at IS NULL
`

func (q *Queries) CountUnreadInappNotifications(ctx context.Context, profileID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnreadInappNotifications, profileID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const getBroadcastCampaignByID = `-- name: GetBroadcastCampaignByID :one
SELECT id, created_by_admin, title, body, image_url, action_url, audience, channels, status, idempotency_key, recipient_total, pending_count, sent_count, failed_count, push_sent_count, push_failed_count, error_summary, created_at, queued_at, started_at, finished_at
FROM broadcast_campaign
WHERE id = $1
`

func (q *Queries) GetBroadcastCampaignByID(ctx context.Context, id uuid.UUID) (BroadcastCampaign, error) {
	row := q.db.QueryRow(ctx, getBroadcastCampaignByID, id)
	var i BroadcastCampaign
	err := row.Scan(
		&i.ID,
		&i.CreatedByAdmin,
		&i.Title,
		&i.Body,
		&i.ImageUrl,
		&i.ActionUrl,
		&i.Audience,
		&i.Channels,
		&i.Status,
		&i.IdempotencyKey,
		&i.RecipientTotal,
		&i.PendingCount,
		&i.SentCount,
		&i.FailedCount,
		&i.PushSentCount,
		&i.PushFailedCount,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getBroadcastCampaignByIdempotencyKey = `-- name: GetBroadcastCampaignByIdempotencyKey :one
SELECT id, created_by_admin, title, body, image_url, action_url, audience, channels, status, idempotency_key, recipient_total, pending_count, sent_count, failed_count, push_sent_count, push_failed_count, error_summary, created_at, queued_at, started_at, finished_at
FROM broadcast_campaign
WHERE idempotency_key = $1
`

func (q *Queries) GetBroadcastCampaignByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (BroadcastCampaign, error) {
	row := q.db.QueryRow(ctx, getBroadcastCampaignByIdempotencyKey, idempotencyKey)
	var i BroadcastCampaign
	err := row.Scan(
		&i.ID,
		&i.CreatedByAdmin,
		&i.Title,
		&i.Body,
		&i.ImageUrl,
		&i.ActionUrl,
		&i.Audience,
		&i.Channels,
		&i.Status,
		&i.IdempotencyKey,
		&i.RecipientTotal,
		&i.PendingCount,
		&i.SentCount,
		&i.FailedCount,
		&i.PushSentCount,
		&i.PushFailedCount,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getInappNotificationByCampaignProfile = `-- name: GetInappNotificationByCampaignProfile :one
SELECT id, profile_id, kind, payload, channel, sent_at, read_at, created_at, campaign_id
FROM notification
WHERE campaign_id = $1
  AND profile_id = $2
  AND channel = 'inapp'
LIMIT 1
`

type GetInappNotificationByCampaignProfileParams struct {
	CampaignID uuid.NullUUID `json:"campaign_id"`
	ProfileID  uuid.UUID     `json:"profile_id"`
}

func (q *Queries) GetInappNotificationByCampaignProfile(ctx context.Context, arg GetInappNotificationByCampaignProfileParams) (Notification, error) {
	row := q.db.QueryRow(ctx, getInappNotificationByCampaignProfile, arg.CampaignID, arg.ProfileID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Kind,
		&i.Payload,
		&i.Channel,
		&i.SentAt,
		&i.ReadAt,
		&i.CreatedAt,
		&i.CampaignID,
	)
	return i, err
}

const insertBroadcastCampaign = `-- name: InsertBroadcastCampaign :one
INSERT INTO broadcast_campaign (
  created_by_admin, title, body, image_url, action_url,
  audience, channels, status, idempotency_key, queued_at
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, now()
)
RETURNING id, created_by_admin, title, body, image_url, action_url, audience, channels, status, idempotency_key, recipient_total, pending_count, sent_count, failed_count, push_sent_count, push_failed_count, error_summary, created_at, queued_at, started_at, finished_at
`

type InsertBroadcastCampaignParams struct {
	CreatedByAdmin uuid.UUID   `json:"created_by_admin"`
	Title          string      `json:"title"`
	Body           string      `json:"body"`
	ImageUrl       string      `json:"image_url"`
	ActionUrl      string      `json:"action_url"`
	Audience       string      `json:"audience"`
	Channels       string      `json:"channels"`
	Status         string      `json:"status"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) InsertBroadcastCampaign(ctx context.Context, arg InsertBroadcastCampaignParams) (BroadcastCampaign, error) {
	row := q.db.QueryRow(ctx, insertBroadcastCampaign,
		arg.CreatedByAdmin,
		arg.Title,
		arg.Body,
		arg.ImageUrl,
		arg.ActionUrl,
		arg.Audience,
		arg.Channels,
		arg.Status,
		arg.IdempotencyKey,
	)
	var i BroadcastCampaign
	err := row.Scan(
		&i.ID,
		&i.CreatedByAdmin,
		&i.Title,
		&i.Body,
		&i.ImageUrl,
		&i.ActionUrl,
		&i.Audience,
		&i.Channels,
		&i.Status,
		&i.IdempotencyKey,
		&i.RecipientTotal,
		&i.PendingCount,
		&i.SentCount,
		&i.FailedCount,
		&i.PushSentCount,
		&i.PushFailedCount,
		&i.ErrorSummary,
		&i.CreatedAt,
		&i.QueuedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertInappNotification = `-- name: InsertInappNotification :one
INSERT INTO notification (profile_id, kind, payload, channel, campaign_id, sent_at)
VALUES ($1, $2, $3, 'inapp', $4, now())
RETURNING id, profile_id, kind, payload, channel, sent_at, read_at, created_at, campaign_id
`

type InsertInappNotificationParams struct {
	ProfileID  uuid.UUID       `json:"profile_id"`
	Kind       string          `json:"kind"`
	Payload    json.RawMessage `json:"payload"`
	CampaignID uuid.NullUUID   `json:"campaign_id"`
}

func (q *Queries) InsertInappNotification(ctx context.Context, arg InsertInappNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertInappNotification,
		arg.ProfileID,
		arg.Kind,
		arg.Payload,
		arg.CampaignID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Kind,
		&i.Payload,
		&i.Channel,
		&i.SentAt,
		&i.ReadAt,
		&i.CreatedAt,
		&i.CampaignID,
	)
	return i, err
}

const listBroadcastCampaigns = `-- name: ListBroadcastCampaigns :many
SELECT id, created_by_admin, title, body, image_url, action_url, audience, channels, status, idempotency_key, recipient_total, pending_count, sent_count, failed_count, push_sent_count, push_failed_count, error_summary, created_at, queued_at, started_at, finished_at
FROM broadcast_campaign
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBroadcastCampaignsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBroadcastCampaigns(ctx context.Context, arg ListBroadcastCampaignsParams) ([]BroadcastCampaign, error) {
	rows, err := q.db.Query(ctx, listBroadcastCampaigns, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BroadcastCampaign
	for rows.Next() {
		var i BroadcastCampaign
		if err := rows.Scan(
			&i.ID,
			&i.CreatedByAdmin,
			&i.Title,
			&i.Body,
			&i.ImageUrl,
			&i.ActionUrl,
			&i.Audience,
			&i.Channels,
			&i.Status,
			&i.IdempotencyKey,
			&i.RecipientTotal,
			&i.PendingCount,
			&i.SentCount,
			&i.FailedCount,
			&i.PushSentCount,
			&i.PushFailedCount,
			&i.ErrorSummary,
			&i.CreatedAt,
			&i.QueuedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInappNotifications = `-- name: ListInappNotifications :many
SELECT id, profile_id, kind, payload, channel, sent_at, read_at, created_at, campaign_id
FROM notification
WHERE profile_id = $1
  AND channel = 'inapp'
  AND ($2::timestamptz IS NULL OR created_at < $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListInappNotificationsParams struct {
	ProfileID uuid.UUID          `json:"profile_id"`
	Before    pgtype.Timestamptz `json:"before"`
	Limit     int32              `json:"limit"`
}

func (q *Queries) ListInappNotifications(ctx context.Context, arg ListInappNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listInappNotifications, arg.ProfileID, arg.Before, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Kind,
			&i.Payload,
			&i.Channel,
			&i.SentAt,
			&i.ReadAt,
			&i.CreatedAt,
			&i.CampaignID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllInappNotificationsRead = `-- name: MarkAllInappNotificationsRead :execrows
UPDATE notification
SET read_at = now()
WHERE profile_id = $1
  AND channel = 'inapp'
  AND read_at IS NULL
`

func (q *Queries) MarkAllInappNotificationsRead(ctx context.Context, profileID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markAllInappNotificationsRead, profileID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markInappNotificationRead = `-- name: MarkInappNotificationRead :one
UPDATE notification
SET read_at = COALESCE(read_at, now())
WHERE id = $1
  AND profile_id = $2
  AND channel = 'inapp'
RETURNING id, profile_id, kind, payload, channel, sent_at, read_at, created_at, campaign_id
`

type MarkInappNotificationReadParams struct {
	ID        uuid.UUID `json:"id"`
	ProfileID uuid.UUID `json:"profile_id"`
}

func (q *Queries) MarkInappNotificationRead(ctx context.Context, arg MarkInappNotificationReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markInappNotificationRead, arg.ID, arg.ProfileID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Kind,
		&i.Payload,
		&i.Channel,
		&i.SentAt,
		&i.ReadAt,
		&i.CreatedAt,
		&i.CampaignID,
	)
	return i, err
}
