// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content_read.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getQuestion = `-- name: GetQuestion :one
SELECT q.id, c.code AS category_code,
       img.storage_key AS image_key,
       COALESCE(qt.text, qft.text, '') AS text,
       (qt.text IS NULL)::bool AS fallback_used
FROM question q
JOIN category c ON c.id = q.category_id
LEFT JOIN image img ON img.id = q.image_id
LEFT JOIN question_translation qt
       ON qt.question_id = q.id AND qt.locale = $1 AND qt.status = 'verified'
LEFT JOIN question_translation qft
       ON qft.question_id = q.id AND qft.locale = 'uz-Latn' AND qft.status = 'verified'
WHERE q.id = $2 AND q.validation_status = 'valid'
`

type GetQuestionParams struct {
	Locale string    `json:"locale"`
	ID     uuid.UUID `json:"id"`
}

type GetQuestionRow struct {
	ID           uuid.UUID   `json:"id"`
	CategoryCode string      `json:"category_code"`
	ImageKey     pgtype.Text `json:"image_key"`
	Text         string      `json:"text"`
	FallbackUsed bool        `json:"fallback_used"`
}

func (q *Queries) GetQuestion(ctx context.Context, arg GetQuestionParams) (GetQuestionRow, error) {
	row := q.db.QueryRow(ctx, getQuestion, arg.Locale, arg.ID)
	var i GetQuestionRow
	err := row.Scan(
		&i.ID,
		&i.CategoryCode,
		&i.ImageKey,
		&i.Text,
		&i.FallbackUsed,
	)
	return i, err
}

const getSignByCode = `-- name: GetSignByCode :one
SELECT s.id, s.code, g.code AS group_code,
       simg.storage_key AS image_key,
       COALESCE(st.name, sft.name, '') AS name,
       COALESCE(st.description, sft.description, '') AS description
FROM sign s
JOIN sign_group g ON g.id = s.group_id
LEFT JOIN image simg ON simg.id = s.image_id
LEFT JOIN sign_translation st
       ON st.sign_id = s.id AND st.locale = $1 AND st.status = 'verified'
LEFT JOIN sign_translation sft
       ON sft.sign_id = s.id AND sft.locale = 'uz-Latn' AND sft.status = 'verified'
WHERE s.code = $2
`

type GetSignByCodeParams struct {
	Locale string `json:"locale"`
	Code   string `json:"code"`
}

type GetSignByCodeRow struct {
	ID          uuid.UUID   `json:"id"`
	Code        string      `json:"code"`
	GroupCode   string      `json:"group_code"`
	ImageKey    pgtype.Text `json:"image_key"`
	Name        string      `json:"name"`
	Description string      `json:"description"`
}

func (q *Queries) GetSignByCode(ctx context.Context, arg GetSignByCodeParams) (GetSignByCodeRow, error) {
	row := q.db.QueryRow(ctx, getSignByCode, arg.Locale, arg.Code)
	var i GetSignByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.GroupCode,
		&i.ImageKey,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const getVariantByNumber = `-- name: GetVariantByNumber :one
SELECT id, number, sort_order FROM variant WHERE number = $1
`

func (q *Queries) GetVariantByNumber(ctx context.Context, number int32) (Variant, error) {
	row := q.db.QueryRow(ctx, getVariantByNumber, number)
	var i Variant
	err := row.Scan(&i.ID, &i.Number, &i.SortOrder)
	return i, err
}

const getVerifiedExplanation = `-- name: GetVerifiedExplanation :one
SELECT e.id, e.legal_refs,
       COALESCE(et.blocks, eft.blocks) AS blocks
FROM explanation e
LEFT JOIN explanation_translation et
       ON et.explanation_id = e.id AND et.locale = $1 AND et.status = 'verified'
LEFT JOIN explanation_translation eft
       ON eft.explanation_id = e.id AND eft.locale = 'uz-Latn' AND eft.status = 'verified'
WHERE e.question_id = $2
  AND COALESCE(et.blocks, eft.blocks) IS NOT NULL
`

type GetVerifiedExplanationParams struct {
	Locale     string    `json:"locale"`
	QuestionID uuid.UUID `json:"question_id"`
}

type GetVerifiedExplanationRow struct {
	ID        uuid.UUID       `json:"id"`
	LegalRefs json.RawMessage `json:"legal_refs"`
	Blocks    json.RawMessage `json:"blocks"`
}

func (q *Queries) GetVerifiedExplanation(ctx context.Context, arg GetVerifiedExplanationParams) (GetVerifiedExplanationRow, error) {
	row := q.db.QueryRow(ctx, getVerifiedExplanation, arg.Locale, arg.QuestionID)
	var i GetVerifiedExplanationRow
	err := row.Scan(&i.ID, &i.LegalRefs, &i.Blocks)
	return i, err
}

const listAnswersByQuestionIDs = `-- name: ListAnswersByQuestionIDs :many
SELECT a.id, a.question_id, a.position,
       aimg.storage_key AS image_key,
       COALESCE(at.text, aft.text, '') AS text,
       -- Answer-shuffling reads this, never the localized text: whether a
       -- question's options may be reordered is a property of the question,
       -- and deciding it from whichever locale the reader happens to use made
       -- the same question shuffle in Russian and stay put in Uzbek.
       COALESCE(aft.text, at.text, '') AS text_uz_latn,
       (at.text IS NULL)::bool AS fallback_used
FROM answer a
LEFT JOIN image aimg ON aimg.id = a.image_id
LEFT JOIN answer_translation at
       ON at.answer_id = a.id AND at.locale = $1 AND at.status = 'verified'
LEFT JOIN answer_translation aft
       ON aft.answer_id = a.id AND aft.locale = 'uz-Latn' AND aft.status = 'verified'
WHERE a.question_id = ANY($2::uuid[])
ORDER BY a.question_id, a.position
`

type ListAnswersByQuestionIDsParams struct {
	Locale      string      `json:"locale"`
	QuestionIds []uuid.UUID `json:"question_ids"`
}

type ListAnswersByQuestionIDsRow struct {
	ID           uuid.UUID   `json:"id"`
	QuestionID   uuid.UUID   `json:"question_id"`
	Position     int16       `json:"position"`
	ImageKey     pgtype.Text `json:"image_key"`
	Text         string      `json:"text"`
	TextUzLatn   string      `json:"text_uz_latn"`
	FallbackUsed bool        `json:"fallback_used"`
}

func (q *Queries) ListAnswersByQuestionIDs(ctx context.Context, arg ListAnswersByQuestionIDsParams) ([]ListAnswersByQuestionIDsRow, error) {
	rows, err := q.db.Query(ctx, listAnswersByQuestionIDs, arg.Locale, arg.QuestionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAnswersByQuestionIDsRow
	for rows.Next() {
		var i ListAnswersByQuestionIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Position,
			&i.ImageKey,
			&i.Text,
			&i.TextUzLatn,
			&i.FallbackUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT c.id, c.code, c.sort_order,
       COALESCE(t.name, ft.name, '') AS name,
       (t.name IS NULL)::bool AS fallback_used,
       (SELECT count(*) FROM question q
         WHERE q.category_id = c.id AND q.validation_status = 'valid')::int AS question_count
FROM category c
LEFT JOIN category_translation t
       ON t.category_id = c.id AND t.locale = $1 AND t.status = 'verified'
LEFT JOIN category_translation ft
       ON ft.category_id = c.id AND ft.locale = 'uz-Latn' AND ft.status = 'verified'
ORDER BY c.sort_order, c.code
`

type ListCategoriesRow struct {
	ID            uuid.UUID `json:"id"`
	Code          string    `json:"code"`
	SortOrder     int32     `json:"sort_order"`
	Name          string    `json:"name"`
	FallbackUsed  bool      `json:"fallback_used"`
	QuestionCount int32     `json:"question_count"`
}

// question_count lets the practice picker state how much material a topic
// actually holds instead of guessing; categories range from tens to hundreds.
func (q *Queries) ListCategories(ctx context.Context, locale string) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories, locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.SortOrder,
			&i.Name,
			&i.FallbackUsed,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionSigns = `-- name: ListQuestionSigns :many
SELECT s.code, simg.storage_key AS image_key,
       COALESCE(st.name, sft.name, '') AS name
FROM question_sign qs
JOIN sign s ON s.id = qs.sign_id
LEFT JOIN image simg ON simg.id = s.image_id
LEFT JOIN sign_translation st
       ON st.sign_id = s.id AND st.locale = $1 AND st.status = 'verified'
LEFT JOIN sign_translation sft
       ON sft.sign_id = s.id AND sft.locale = 'uz-Latn' AND sft.status = 'verified'
WHERE qs.question_id = $2
ORDER BY s.code
`

type ListQuestionSignsParams struct {
	Locale     string    `json:"locale"`
	QuestionID uuid.UUID `json:"question_id"`
}

type ListQuestionSignsRow struct {
	Code     string      `json:"code"`
	ImageKey pgtype.Text `json:"image_key"`
	Name     string      `json:"name"`
}

func (q *Queries) ListQuestionSigns(ctx context.Context, arg ListQuestionSignsParams) ([]ListQuestionSignsRow, error) {
	rows, err := q.db.Query(ctx, listQuestionSigns, arg.Locale, arg.QuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionSignsRow
	for rows.Next() {
		var i ListQuestionSignsRow
		if err := rows.Scan(&i.Code, &i.ImageKey, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionSignsByQuestionIDs = `-- name: ListQuestionSignsByQuestionIDs :many
SELECT qs.question_id, s.code, simg.storage_key AS image_key,
       COALESCE(st.name, sft.name, '') AS name
FROM question_sign qs
JOIN sign s ON s.id = qs.sign_id
LEFT JOIN image simg ON simg.id = s.image_id
LEFT JOIN sign_translation st
       ON st.sign_id = s.id AND st.locale = $1 AND st.status = 'verified'
LEFT JOIN sign_translation sft
       ON sft.sign_id = s.id AND sft.locale = 'uz-Latn' AND sft.status = 'verified'
WHERE qs.question_id = ANY($2::uuid[])
ORDER BY qs.question_id, s.code
`

type ListQuestionSignsByQuestionIDsParams struct {
	Locale      string      `json:"locale"`
	QuestionIds []uuid.UUID `json:"question_ids"`
}

type ListQuestionSignsByQuestionIDsRow struct {
	QuestionID uuid.UUID   `json:"question_id"`
	Code       string      `json:"code"`
	ImageKey   pgtype.Text `json:"image_key"`
	Name       string      `json:"name"`
}

func (q *Queries) ListQuestionSignsByQuestionIDs(ctx context.Context, arg ListQuestionSignsByQuestionIDsParams) ([]ListQuestionSignsByQuestionIDsRow, error) {
	rows, err := q.db.Query(ctx, listQuestionSignsByQuestionIDs, arg.Locale, arg.QuestionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionSignsByQuestionIDsRow
	for rows.Next() {
		var i ListQuestionSignsByQuestionIDsRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.Code,
			&i.ImageKey,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQuestionsByIDs = `-- name: ListQuestionsByIDs :many
SELECT q.id, c.code AS category_code,
       img.storage_key AS image_key,
       COALESCE(qt.text, qft.text, '') AS text,
       (qt.text IS NULL)::bool AS fallback_used
FROM question q
JOIN category c ON c.id = q.category_id
LEFT JOIN image img ON img.id = q.image_id
LEFT JOIN question_translation qt
       ON qt.question_id = q.id AND qt.locale = $1 AND qt.status = 'verified'
LEFT JOIN question_translation qft
       ON qft.question_id = q.id AND qft.locale = 'uz-Latn' AND qft.status = 'verified'
WHERE q.id = ANY($2::uuid[]) AND q.validation_status = 'valid'
`

type ListQuestionsByIDsParams struct {
	Locale string      `json:"locale"`
	Ids    []uuid.UUID `json:"ids"`
}

type ListQuestionsByIDsRow struct {
	ID           uuid.UUID   `json:"id"`
	CategoryCode string      `json:"category_code"`
	ImageKey     pgtype.Text `json:"image_key"`
	Text         string      `json:"text"`
	FallbackUsed bool        `json:"fallback_used"`
}

func (q *Queries) ListQuestionsByIDs(ctx context.Context, arg ListQuestionsByIDsParams) ([]ListQuestionsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listQuestionsByIDs, arg.Locale, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuestionsByIDsRow
	for rows.Next() {
		var i ListQuestionsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryCode,
			&i.ImageKey,
			&i.Text,
			&i.FallbackUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignGroups = `-- name: ListSignGroups :many
SELECT g.id, g.code, g.sort_order,
       COALESCE(t.name, ft.name, '') AS name
FROM sign_group g
LEFT JOIN sign_group_translation t
       ON t.sign_group_id = g.id AND t.locale = $1 AND t.status = 'verified'
LEFT JOIN sign_group_translation ft
       ON ft.sign_group_id = g.id AND ft.locale = 'uz-Latn' AND ft.status = 'verified'
ORDER BY g.sort_order, g.code
`

type ListSignGroupsRow struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	SortOrder int32     `json:"sort_order"`
	Name      string    `json:"name"`
}

func (q *Queries) ListSignGroups(ctx context.Context, locale string) ([]ListSignGroupsRow, error) {
	rows, err := q.db.Query(ctx, listSignGroups, locale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSignGroupsRow
	for rows.Next() {
		var i ListSignGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.SortOrder,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignQuestionIDs = `-- name: ListSignQuestionIDs :many
SELECT qs.question_id
FROM question_sign qs
JOIN question q ON q.id = qs.question_id AND q.validation_status = 'valid'
WHERE qs.sign_id = $1
`

func (q *Queries) ListSignQuestionIDs(ctx context.Context, signID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listSignQuestionIDs, signID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var question_id uuid.UUID
		if err := rows.Scan(&question_id); err != nil {
			return nil, err
		}
		items = append(items, question_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSigns = `-- name: ListSigns :many
SELECT s.id, s.code, g.code AS group_code,
       simg.storage_key AS image_key,
       COALESCE(st.name, sft.name, '') AS name,
       (SELECT count(*)::int FROM question_sign qs
         JOIN question q ON q.id = qs.question_id AND q.validation_status = 'valid'
        WHERE qs.sign_id = s.id) AS question_count
FROM sign s
JOIN sign_group g ON g.id = s.group_id
LEFT JOIN image simg ON simg.id = s.image_id
LEFT JOIN sign_translation st
       ON st.sign_id = s.id AND st.locale = $1 AND st.status = 'verified'
LEFT JOIN sign_translation sft
       ON sft.sign_id = s.id AND sft.locale = 'uz-Latn' AND sft.status = 'verified'
WHERE ($2::text = '' OR g.code = $2::text)
  AND ($3::text = ''
       OR s.code ILIKE '%' || $3::text || '%'
       OR COALESCE(st.name, sft.name, '') ILIKE '%' || $3::text || '%')
ORDER BY g.sort_order, s.sort_order, s.code
`

type ListSignsParams struct {
	Locale    string `json:"locale"`
	GroupCode string `json:"group_code"`
	Search    string `json:"search"`
}

type ListSignsRow struct {
	ID            uuid.UUID   `json:"id"`
	Code          string      `json:"code"`
	GroupCode     string      `json:"group_code"`
	ImageKey      pgtype.Text `json:"image_key"`
	Name          string      `json:"name"`
	QuestionCount int32       `json:"question_count"`
}

func (q *Queries) ListSigns(ctx context.Context, arg ListSignsParams) ([]ListSignsRow, error) {
	rows, err := q.db.Query(ctx, listSigns, arg.Locale, arg.GroupCode, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSignsRow
	for rows.Next() {
		var i ListSignsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.GroupCode,
			&i.ImageKey,
			&i.Name,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantQuestions = `-- name: ListVariantQuestions :many
SELECT q.id, vq.position, c.code AS category_code,
       img.storage_key AS image_key,
       COALESCE(qt.text, qft.text, '') AS text,
       (qt.text IS NULL)::bool AS fallback_used
FROM variant_question vq
JOIN question q ON q.id = vq.question_id AND q.validation_status = 'valid'
JOIN category c ON c.id = q.category_id
LEFT JOIN image img ON img.id = q.image_id
LEFT JOIN question_translation qt
       ON qt.question_id = q.id AND qt.locale = $1 AND qt.status = 'verified'
LEFT JOIN question_translation qft
       ON qft.question_id = q.id AND qft.locale = 'uz-Latn' AND qft.status = 'verified'
WHERE vq.variant_id = $2
ORDER BY vq.position
`

type ListVariantQuestionsParams struct {
	Locale    string    `json:"locale"`
	VariantID uuid.UUID `json:"variant_id"`
}

type ListVariantQuestionsRow struct {
	ID           uuid.UUID   `json:"id"`
	Position     int16       `json:"position"`
	CategoryCode string      `json:"category_code"`
	ImageKey     pgtype.Text `json:"image_key"`
	Text         string      `json:"text"`
	FallbackUsed bool        `json:"fallback_used"`
}

func (q *Queries) ListVariantQuestions(ctx context.Context, arg ListVariantQuestionsParams) ([]ListVariantQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listVariantQuestions, arg.Locale, arg.VariantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVariantQuestionsRow
	for rows.Next() {
		var i ListVariantQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.CategoryCode,
			&i.ImageKey,
			&i.Text,
			&i.FallbackUsed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariants = `-- name: ListVariants :many
SELECT v.id, v.number, count(vq.question_id)::int AS question_count
FROM variant v
LEFT JOIN variant_question vq ON vq.variant_id = v.id
GROUP BY v.id, v.number
ORDER BY v.number
`

type ListVariantsRow struct {
	ID            uuid.UUID `json:"id"`
	Number        int32     `json:"number"`
	QuestionCount int32     `json:"question_count"`
}

func (q *Queries) ListVariants(ctx context.Context) ([]ListVariantsRow, error) {
	rows, err := q.db.Query(ctx, listVariants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVariantsRow
	for rows.Next() {
		var i ListVariantsRow
		if err := rows.Scan(&i.ID, &i.Number, &i.QuestionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVerifiedExplanationsByQuestionIDs = `-- name: ListVerifiedExplanationsByQuestionIDs :many
SELECT e.question_id, e.legal_refs,
       COALESCE(et.blocks, eft.blocks) AS blocks
FROM explanation e
LEFT JOIN explanation_translation et
       ON et.explanation_id = e.id AND et.locale = $1 AND et.status = 'verified'
LEFT JOIN explanation_translation eft
       ON eft.explanation_id = e.id AND eft.locale = 'uz-Latn' AND eft.status = 'verified'
WHERE e.question_id = ANY($2::uuid[])
  AND COALESCE(et.blocks, eft.blocks) IS NOT NULL
`

type ListVerifiedExplanationsByQuestionIDsParams struct {
	Locale      string      `json:"locale"`
	QuestionIds []uuid.UUID `json:"question_ids"`
}

type ListVerifiedExplanationsByQuestionIDsRow struct {
	QuestionID uuid.UUID       `json:"question_id"`
	LegalRefs  json.RawMessage `json:"legal_refs"`
	Blocks     json.RawMessage `json:"blocks"`
}

func (q *Queries) ListVerifiedExplanationsByQuestionIDs(ctx context.Context, arg ListVerifiedExplanationsByQuestionIDsParams) ([]ListVerifiedExplanationsByQuestionIDsRow, error) {
	rows, err := q.db.Query(ctx, listVerifiedExplanationsByQuestionIDs, arg.Locale, arg.QuestionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVerifiedExplanationsByQuestionIDsRow
	for rows.Next() {
		var i ListVerifiedExplanationsByQuestionIDsRow
		if err := rows.Scan(&i.QuestionID, &i.LegalRefs, &i.Blocks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
