// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO event (profile_id, name, props, ts)
VALUES ($1, $2, $3, $4)
`

type InsertEventParams struct {
	ProfileID uuid.NullUUID      `json:"profile_id"`
	Name      string             `json:"name"`
	Props     json.RawMessage    `json:"props"`
	Ts        pgtype.Timestamptz `json:"ts"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ProfileID,
		arg.Name,
		arg.Props,
		arg.Ts,
	)
	return err
}
