// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: explanation.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getCorrectAnswerTextForDraft = `-- name: GetCorrectAnswerTextForDraft :one
SELECT COALESCE(at.text, aft.text, '') AS answer_text
FROM answer a
LEFT JOIN answer_translation at
       ON at.answer_id = a.id AND at.locale = 'uz-Latn' AND at.status = 'verified'
LEFT JOIN answer_translation aft
       ON aft.answer_id = a.id AND aft.locale = 'uz-Latn'
WHERE a.question_id = $1 AND a.is_correct = true
`

func (q *Queries) GetCorrectAnswerTextForDraft(ctx context.Context, questionID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getCorrectAnswerTextForDraft, questionID)
	var answer_text string
	err := row.Scan(&answer_text)
	return answer_text, err
}

const getExplanationIDByQuestionID = `-- name: GetExplanationIDByQuestionID :one
SELECT id FROM explanation WHERE question_id = $1
`

func (q *Queries) GetExplanationIDByQuestionID(ctx context.Context, questionID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getExplanationIDByQuestionID, questionID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getExplanationTranslationByExplanationAndLocale = `-- name: GetExplanationTranslationByExplanationAndLocale :one
SELECT explanation_id, locale, blocks, status, verified_by, verified_at, source FROM explanation_translation
WHERE explanation_id = $1 AND locale = $2
`

type GetExplanationTranslationByExplanationAndLocaleParams struct {
	ExplanationID uuid.UUID `json:"explanation_id"`
	Locale        string    `json:"locale"`
}

func (q *Queries) GetExplanationTranslationByExplanationAndLocale(ctx context.Context, arg GetExplanationTranslationByExplanationAndLocaleParams) (ExplanationTranslation, error) {
	row := q.db.QueryRow(ctx, getExplanationTranslationByExplanationAndLocale, arg.ExplanationID, arg.Locale)
	var i ExplanationTranslation
	err := row.Scan(
		&i.ExplanationID,
		&i.Locale,
		&i.Blocks,
		&i.Status,
		&i.VerifiedBy,
		&i.VerifiedAt,
		&i.Source,
	)
	return i, err
}

const getExplanationTranslationForFeedback = `-- name: GetExplanationTranslationForFeedback :one
SELECT e.id AS explanation_id
FROM explanation e
WHERE e.question_id = $1
LIMIT 1
`

// Used only to validate that a question has an explanation before recording
// feedback against it — returns the explanation_id regardless of locale/status,
// since feedback is about the question's explanation as a whole, not one locale.
func (q *Queries) GetExplanationTranslationForFeedback(ctx context.Context, questionID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getExplanationTranslationForFeedback, questionID)
	var explanation_id uuid.UUID
	err := row.Scan(&explanation_id)
	return explanation_id, err
}

const getQuestionForDraft = `-- name: GetQuestionForDraft :one
SELECT q.id, q.category_id, c.code AS category_code,
       COALESCE(qt.text, qft.text, '') AS question_text
FROM question q
JOIN category c ON c.id = q.category_id
LEFT JOIN question_translation qt
       ON qt.question_id = q.id AND qt.locale = 'uz-Latn' AND qt.status = 'verified'
LEFT JOIN question_translation qft
       ON qft.question_id = q.id AND qft.locale = 'uz-Latn'
WHERE q.id = $1
`

type GetQuestionForDraftRow struct {
	ID           uuid.UUID `json:"id"`
	CategoryID   uuid.UUID `json:"category_id"`
	CategoryCode string    `json:"category_code"`
	QuestionText string    `json:"question_text"`
}

func (q *Queries) GetQuestionForDraft(ctx context.Context, id uuid.UUID) (GetQuestionForDraftRow, error) {
	row := q.db.QueryRow(ctx, getQuestionForDraft, id)
	var i GetQuestionForDraftRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.CategoryCode,
		&i.QuestionText,
	)
	return i, err
}

const insertDraftExplanation = `-- name: InsertDraftExplanation :one
INSERT INTO explanation (question_id, legal_refs)
VALUES ($1, '[]'::jsonb)
ON CONFLICT (question_id) DO UPDATE SET legal_refs = explanation.legal_refs
RETURNING id
`

func (q *Queries) InsertDraftExplanation(ctx context.Context, questionID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertDraftExplanation, questionID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertDraftTranslation = `-- name: InsertDraftTranslation :exec
INSERT INTO explanation_translation (explanation_id, locale, blocks, status, source)
VALUES ($1, $2, $3, 'draft', 'ai-stub')
ON CONFLICT (explanation_id, locale) DO UPDATE
  SET blocks = EXCLUDED.blocks, status = 'draft', source = 'ai-stub'
`

type InsertDraftTranslationParams struct {
	ExplanationID uuid.UUID       `json:"explanation_id"`
	Locale        string          `json:"locale"`
	Blocks        json.RawMessage `json:"blocks"`
}

func (q *Queries) InsertDraftTranslation(ctx context.Context, arg InsertDraftTranslationParams) error {
	_, err := q.db.Exec(ctx, insertDraftTranslation, arg.ExplanationID, arg.Locale, arg.Blocks)
	return err
}

const upsertExplanationFeedback = `-- name: UpsertExplanationFeedback :exec
INSERT INTO explanation_feedback (profile_id, explanation_id, helpful)
VALUES ($1, $2, $3)
ON CONFLICT (profile_id, explanation_id) DO UPDATE SET helpful = EXCLUDED.helpful
`

type UpsertExplanationFeedbackParams struct {
	ProfileID     uuid.UUID `json:"profile_id"`
	ExplanationID uuid.UUID `json:"explanation_id"`
	Helpful       bool      `json:"helpful"`
}

func (q *Queries) UpsertExplanationFeedback(ctx context.Context, arg UpsertExplanationFeedbackParams) error {
	_, err := q.db.Exec(ctx, upsertExplanationFeedback, arg.ProfileID, arg.ExplanationID, arg.Helpful)
	return err
}

const verifyExplanationTranslation = `-- name: VerifyExplanationTranslation :exec
UPDATE explanation_translation
SET status = 'verified', verified_by = $1, verified_at = now()
WHERE explanation_id = $2 AND locale = $3
`

type VerifyExplanationTranslationParams struct {
	VerifiedBy    uuid.NullUUID `json:"verified_by"`
	ExplanationID uuid.UUID     `json:"explanation_id"`
	Locale        string        `json:"locale"`
}

func (q *Queries) VerifyExplanationTranslation(ctx context.Context, arg VerifyExplanationTranslationParams) error {
	_, err := q.db.Exec(ctx, verifyExplanationTranslation, arg.VerifiedBy, arg.ExplanationID, arg.Locale)
	return err
}
