// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grand_mock_certificate.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getGrandMockCertificateBySession = `-- name: GetGrandMockCertificateBySession :one
SELECT id, session_id, profile_id, share_code, score, total, created_at FROM grand_mock_certificate WHERE session_id = $1
`

func (q *Queries) GetGrandMockCertificateBySession(ctx context.Context, sessionID uuid.UUID) (GrandMockCertificate, error) {
	row := q.db.QueryRow(ctx, getGrandMockCertificateBySession, sessionID)
	var i GrandMockCertificate
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProfileID,
		&i.ShareCode,
		&i.Score,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const getGrandMockCertificateByShareCode = `-- name: GetGrandMockCertificateByShareCode :one
SELECT id, session_id, profile_id, share_code, score, total, created_at FROM grand_mock_certificate WHERE share_code = $1
`

func (q *Queries) GetGrandMockCertificateByShareCode(ctx context.Context, shareCode string) (GrandMockCertificate, error) {
	row := q.db.QueryRow(ctx, getGrandMockCertificateByShareCode, shareCode)
	var i GrandMockCertificate
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProfileID,
		&i.ShareCode,
		&i.Score,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}

const insertGrandMockCertificate = `-- name: InsertGrandMockCertificate :one
INSERT INTO grand_mock_certificate (session_id, profile_id, share_code, score, total)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (session_id) DO UPDATE SET
  share_code = grand_mock_certificate.share_code
RETURNING id, session_id, profile_id, share_code, score, total, created_at
`

type InsertGrandMockCertificateParams struct {
	SessionID uuid.UUID `json:"session_id"`
	ProfileID uuid.UUID `json:"profile_id"`
	ShareCode string    `json:"share_code"`
	Score     int32     `json:"score"`
	Total     int32     `json:"total"`
}

func (q *Queries) InsertGrandMockCertificate(ctx context.Context, arg InsertGrandMockCertificateParams) (GrandMockCertificate, error) {
	row := q.db.QueryRow(ctx, insertGrandMockCertificate,
		arg.SessionID,
		arg.ProfileID,
		arg.ShareCode,
		arg.Score,
		arg.Total,
	)
	var i GrandMockCertificate
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ProfileID,
		&i.ShareCode,
		&i.Score,
		&i.Total,
		&i.CreatedAt,
	)
	return i, err
}
