// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: importer_write.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const deleteAnswersForQuestion = `-- name: DeleteAnswersForQuestion :exec
DELETE FROM answer WHERE question_id = $1
`

// Dev/fixture wipe helper. Production re-import must NOT call this when
// session_answer / arena_answer rows still reference answer ids.
func (q *Queries) DeleteAnswersForQuestion(ctx context.Context, questionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAnswersForQuestion, questionID)
	return err
}

const deleteQuestionSigns = `-- name: DeleteQuestionSigns :exec
DELETE FROM question_sign WHERE question_id = $1
`

func (q *Queries) DeleteQuestionSigns(ctx context.Context, questionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestionSigns, questionID)
	return err
}

const deleteVariantQuestions = `-- name: DeleteVariantQuestions :exec
DELETE FROM variant_question WHERE variant_id = $1
`

func (q *Queries) DeleteVariantQuestions(ctx context.Context, variantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariantQuestions, variantID)
	return err
}

const getQuestionIDBySourceExtID = `-- name: GetQuestionIDBySourceExtID :one
SELECT id FROM question WHERE source_ext_id = $1
`

func (q *Queries) GetQuestionIDBySourceExtID(ctx context.Context, sourceExtID string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getQuestionIDBySourceExtID, sourceExtID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertAnswer = `-- name: InsertAnswer :one
INSERT INTO answer (question_id, position, is_correct, image_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertAnswerParams struct {
	QuestionID uuid.UUID     `json:"question_id"`
	Position   int16         `json:"position"`
	IsCorrect  bool          `json:"is_correct"`
	ImageID    uuid.NullUUID `json:"image_id"`
}

func (q *Queries) InsertAnswer(ctx context.Context, arg InsertAnswerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertAnswer,
		arg.QuestionID,
		arg.Position,
		arg.IsCorrect,
		arg.ImageID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertAnswerTranslation = `-- name: InsertAnswerTranslation :exec
INSERT INTO answer_translation (answer_id, locale, text, status)
VALUES ($1, $2, $3, $4)
`

type InsertAnswerTranslationParams struct {
	AnswerID uuid.UUID `json:"answer_id"`
	Locale   string    `json:"locale"`
	Text     string    `json:"text"`
	Status   string    `json:"status"`
}

func (q *Queries) InsertAnswerTranslation(ctx context.Context, arg InsertAnswerTranslationParams) error {
	_, err := q.db.Exec(ctx, insertAnswerTranslation,
		arg.AnswerID,
		arg.Locale,
		arg.Text,
		arg.Status,
	)
	return err
}

const insertQuestionSign = `-- name: InsertQuestionSign :exec
INSERT INTO question_sign (question_id, sign_id) VALUES ($1, $2)
`

type InsertQuestionSignParams struct {
	QuestionID uuid.UUID `json:"question_id"`
	SignID     uuid.UUID `json:"sign_id"`
}

func (q *Queries) InsertQuestionSign(ctx context.Context, arg InsertQuestionSignParams) error {
	_, err := q.db.Exec(ctx, insertQuestionSign, arg.QuestionID, arg.SignID)
	return err
}

const insertVariantQuestion = `-- name: InsertVariantQuestion :exec
INSERT INTO variant_question (variant_id, question_id, position) VALUES ($1, $2, $3)
`

type InsertVariantQuestionParams struct {
	VariantID  uuid.UUID `json:"variant_id"`
	QuestionID uuid.UUID `json:"question_id"`
	Position   int16     `json:"position"`
}

func (q *Queries) InsertVariantQuestion(ctx context.Context, arg InsertVariantQuestionParams) error {
	_, err := q.db.Exec(ctx, insertVariantQuestion, arg.VariantID, arg.QuestionID, arg.Position)
	return err
}

const setCorrectAnswer = `-- name: SetCorrectAnswer :exec
UPDATE question SET correct_answer_id = $2 WHERE id = $1
`

type SetCorrectAnswerParams struct {
	ID              uuid.UUID     `json:"id"`
	CorrectAnswerID uuid.NullUUID `json:"correct_answer_id"`
}

func (q *Queries) SetCorrectAnswer(ctx context.Context, arg SetCorrectAnswerParams) error {
	_, err := q.db.Exec(ctx, setCorrectAnswer, arg.ID, arg.CorrectAnswerID)
	return err
}

const upsertAnswer = `-- name: UpsertAnswer :one
INSERT INTO answer (question_id, position, is_correct, image_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (question_id, position) DO UPDATE
  SET is_correct = EXCLUDED.is_correct,
      image_id = EXCLUDED.image_id
RETURNING id
`

type UpsertAnswerParams struct {
	QuestionID uuid.UUID     `json:"question_id"`
	Position   int16         `json:"position"`
	IsCorrect  bool          `json:"is_correct"`
	ImageID    uuid.NullUUID `json:"image_id"`
}

// Preserve answer row ids across re-import so session_answer / arena_answer
// foreign keys keep pointing at the same choices.
func (q *Queries) UpsertAnswer(ctx context.Context, arg UpsertAnswerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertAnswer,
		arg.QuestionID,
		arg.Position,
		arg.IsCorrect,
		arg.ImageID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertAnswerTranslation = `-- name: UpsertAnswerTranslation :exec
INSERT INTO answer_translation (answer_id, locale, text, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (answer_id, locale) DO UPDATE
  SET text = EXCLUDED.text, status = EXCLUDED.status
`

type UpsertAnswerTranslationParams struct {
	AnswerID uuid.UUID `json:"answer_id"`
	Locale   string    `json:"locale"`
	Text     string    `json:"text"`
	Status   string    `json:"status"`
}

func (q *Queries) UpsertAnswerTranslation(ctx context.Context, arg UpsertAnswerTranslationParams) error {
	_, err := q.db.Exec(ctx, upsertAnswerTranslation,
		arg.AnswerID,
		arg.Locale,
		arg.Text,
		arg.Status,
	)
	return err
}

const upsertCategory = `-- name: UpsertCategory :one
INSERT INTO category (code, sort_order)
VALUES ($1, $2)
ON CONFLICT (code) DO UPDATE SET sort_order = EXCLUDED.sort_order
RETURNING id
`

type UpsertCategoryParams struct {
	Code      string `json:"code"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) UpsertCategory(ctx context.Context, arg UpsertCategoryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertCategory, arg.Code, arg.SortOrder)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertCategoryTranslation = `-- name: UpsertCategoryTranslation :exec
INSERT INTO category_translation (category_id, locale, name, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (category_id, locale) DO UPDATE SET name = EXCLUDED.name, status = EXCLUDED.status
`

type UpsertCategoryTranslationParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	Locale     string    `json:"locale"`
	Name       string    `json:"name"`
	Status     string    `json:"status"`
}

func (q *Queries) UpsertCategoryTranslation(ctx context.Context, arg UpsertCategoryTranslationParams) error {
	_, err := q.db.Exec(ctx, upsertCategoryTranslation,
		arg.CategoryID,
		arg.Locale,
		arg.Name,
		arg.Status,
	)
	return err
}

const upsertExplanation = `-- name: UpsertExplanation :one
INSERT INTO explanation (question_id, legal_refs)
VALUES ($1, $2)
ON CONFLICT (question_id) DO UPDATE SET legal_refs = EXCLUDED.legal_refs
RETURNING id
`

type UpsertExplanationParams struct {
	QuestionID uuid.UUID       `json:"question_id"`
	LegalRefs  json.RawMessage `json:"legal_refs"`
}

func (q *Queries) UpsertExplanation(ctx context.Context, arg UpsertExplanationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertExplanation, arg.QuestionID, arg.LegalRefs)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertExplanationTranslation = `-- name: UpsertExplanationTranslation :exec
INSERT INTO explanation_translation (explanation_id, locale, blocks, status, source)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (explanation_id, locale) DO UPDATE
  SET blocks = EXCLUDED.blocks, status = EXCLUDED.status, source = EXCLUDED.source
`

type UpsertExplanationTranslationParams struct {
	ExplanationID uuid.UUID       `json:"explanation_id"`
	Locale        string          `json:"locale"`
	Blocks        json.RawMessage `json:"blocks"`
	Status        string          `json:"status"`
	Source        string          `json:"source"`
}

func (q *Queries) UpsertExplanationTranslation(ctx context.Context, arg UpsertExplanationTranslationParams) error {
	_, err := q.db.Exec(ctx, upsertExplanationTranslation,
		arg.ExplanationID,
		arg.Locale,
		arg.Blocks,
		arg.Status,
		arg.Source,
	)
	return err
}

const upsertImage = `-- name: UpsertImage :one
INSERT INTO image (storage_key, sha256, mime, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (sha256) DO UPDATE SET mime = EXCLUDED.mime
RETURNING id
`

type UpsertImageParams struct {
	StorageKey string `json:"storage_key"`
	Sha256     string `json:"sha256"`
	Mime       string `json:"mime"`
	Source     string `json:"source"`
}

func (q *Queries) UpsertImage(ctx context.Context, arg UpsertImageParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertImage,
		arg.StorageKey,
		arg.Sha256,
		arg.Mime,
		arg.Source,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertQuestion = `-- name: UpsertQuestion :one
INSERT INTO question (source_ext_id, category_id, image_id, content_hash, source, validation_status, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (source_ext_id) DO UPDATE
  SET category_id = EXCLUDED.category_id,
      image_id = EXCLUDED.image_id,
      content_hash = EXCLUDED.content_hash,
      source = EXCLUDED.source,
      validation_status = EXCLUDED.validation_status,
      correct_answer_id = NULL,
      updated_at = now()
RETURNING id
`

type UpsertQuestionParams struct {
	SourceExtID      string        `json:"source_ext_id"`
	CategoryID       uuid.UUID     `json:"category_id"`
	ImageID          uuid.NullUUID `json:"image_id"`
	ContentHash      string        `json:"content_hash"`
	Source           string        `json:"source"`
	ValidationStatus string        `json:"validation_status"`
}

func (q *Queries) UpsertQuestion(ctx context.Context, arg UpsertQuestionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertQuestion,
		arg.SourceExtID,
		arg.CategoryID,
		arg.ImageID,
		arg.ContentHash,
		arg.Source,
		arg.ValidationStatus,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertQuestionTranslation = `-- name: UpsertQuestionTranslation :exec
INSERT INTO question_translation (question_id, locale, text, status, source)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (question_id, locale) DO UPDATE
  SET text = EXCLUDED.text, status = EXCLUDED.status, source = EXCLUDED.source
`

type UpsertQuestionTranslationParams struct {
	QuestionID uuid.UUID `json:"question_id"`
	Locale     string    `json:"locale"`
	Text       string    `json:"text"`
	Status     string    `json:"status"`
	Source     string    `json:"source"`
}

func (q *Queries) UpsertQuestionTranslation(ctx context.Context, arg UpsertQuestionTranslationParams) error {
	_, err := q.db.Exec(ctx, upsertQuestionTranslation,
		arg.QuestionID,
		arg.Locale,
		arg.Text,
		arg.Status,
		arg.Source,
	)
	return err
}

const upsertSign = `-- name: UpsertSign :one
INSERT INTO sign (group_id, code, image_id, sort_order)
VALUES ($1, $2, $3, $4)
ON CONFLICT (code) DO UPDATE
  SET group_id = EXCLUDED.group_id, image_id = EXCLUDED.image_id, sort_order = EXCLUDED.sort_order
RETURNING id
`

type UpsertSignParams struct {
	GroupID   uuid.UUID     `json:"group_id"`
	Code      string        `json:"code"`
	ImageID   uuid.NullUUID `json:"image_id"`
	SortOrder int32         `json:"sort_order"`
}

func (q *Queries) UpsertSign(ctx context.Context, arg UpsertSignParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertSign,
		arg.GroupID,
		arg.Code,
		arg.ImageID,
		arg.SortOrder,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertSignGroup = `-- name: UpsertSignGroup :one
INSERT INTO sign_group (code, sort_order)
VALUES ($1, $2)
ON CONFLICT (code) DO UPDATE SET sort_order = EXCLUDED.sort_order
RETURNING id
`

type UpsertSignGroupParams struct {
	Code      string `json:"code"`
	SortOrder int32  `json:"sort_order"`
}

func (q *Queries) UpsertSignGroup(ctx context.Context, arg UpsertSignGroupParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertSignGroup, arg.Code, arg.SortOrder)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertSignGroupTranslation = `-- name: UpsertSignGroupTranslation :exec
INSERT INTO sign_group_translation (sign_group_id, locale, name, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (sign_group_id, locale) DO UPDATE SET name = EXCLUDED.name, status = EXCLUDED.status
`

type UpsertSignGroupTranslationParams struct {
	SignGroupID uuid.UUID `json:"sign_group_id"`
	Locale      string    `json:"locale"`
	Name        string    `json:"name"`
	Status      string    `json:"status"`
}

func (q *Queries) UpsertSignGroupTranslation(ctx context.Context, arg UpsertSignGroupTranslationParams) error {
	_, err := q.db.Exec(ctx, upsertSignGroupTranslation,
		arg.SignGroupID,
		arg.Locale,
		arg.Name,
		arg.Status,
	)
	return err
}

const upsertSignTranslation = `-- name: UpsertSignTranslation :exec
INSERT INTO sign_translation (sign_id, locale, name, description, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (sign_id, locale) DO UPDATE
  SET name = EXCLUDED.name, description = EXCLUDED.description, status = EXCLUDED.status
`

type UpsertSignTranslationParams struct {
	SignID      uuid.UUID `json:"sign_id"`
	Locale      string    `json:"locale"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
}

func (q *Queries) UpsertSignTranslation(ctx context.Context, arg UpsertSignTranslationParams) error {
	_, err := q.db.Exec(ctx, upsertSignTranslation,
		arg.SignID,
		arg.Locale,
		arg.Name,
		arg.Description,
		arg.Status,
	)
	return err
}

const upsertVariant = `-- name: UpsertVariant :one
INSERT INTO variant (number, sort_order)
VALUES ($1, $2)
ON CONFLICT (number) DO UPDATE SET sort_order = EXCLUDED.sort_order
RETURNING id
`

type UpsertVariantParams struct {
	Number    int32 `json:"number"`
	SortOrder int32 `json:"sort_order"`
}

func (q *Queries) UpsertVariant(ctx context.Context, arg UpsertVariantParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertVariant, arg.Number, arg.SortOrder)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
