// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCorrectAnswersByProfileByDayInRange = `-- name: CountCorrectAnswersByProfileByDayInRange :many
SELECT
  es.profile_id,
  date_trunc('day', sa.answered_at AT TIME ZONE 'UTC')::timestamptz AS day,
  count(*)::int AS correct_count,
  max(sa.answered_at)::timestamptz AS last_answered_at
FROM session_answer sa
JOIN exam_session es ON es.id = sa.session_id
JOIN profile p ON p.id = es.profile_id AND p.kind = 'user'
WHERE sa.is_correct
  AND sa.answered_at >= $1
  AND sa.answered_at < $2
GROUP BY es.profile_id, date_trunc('day', sa.answered_at AT TIME ZONE 'UTC')
`

type CountCorrectAnswersByProfileByDayInRangeParams struct {
	FromTs pgtype.Timestamptz `json:"from_ts"`
	ToTs   pgtype.Timestamptz `json:"to_ts"`
}

type CountCorrectAnswersByProfileByDayInRangeRow struct {
	ProfileID      uuid.UUID          `json:"profile_id"`
	Day            pgtype.Timestamptz `json:"day"`
	CorrectCount   int32              `json:"correct_count"`
	LastAnsweredAt pgtype.Timestamptz `json:"last_answered_at"`
}

// Per-profile, per-day correct-answer counts within [from_ts, to_ts) —
// used by RebuildPeriod to reapply the daily point cap when reconstructing
// a period's leaderboard from Postgres (the single per-profile total from
// CountCorrectAnswersByProfileInRange can't distinguish "30 in one day"
// from "10 a day for 3 days," and only the former should ever be capped).
func (q *Queries) CountCorrectAnswersByProfileByDayInRange(ctx context.Context, arg CountCorrectAnswersByProfileByDayInRangeParams) ([]CountCorrectAnswersByProfileByDayInRangeRow, error) {
	rows, err := q.db.Query(ctx, countCorrectAnswersByProfileByDayInRange, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountCorrectAnswersByProfileByDayInRangeRow
	for rows.Next() {
		var i CountCorrectAnswersByProfileByDayInRangeRow
		if err := rows.Scan(
			&i.ProfileID,
			&i.Day,
			&i.CorrectCount,
			&i.LastAnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCorrectAnswersByProfileInRange = `-- name: CountCorrectAnswersByProfileInRange :many
SELECT
  es.profile_id,
  count(*)::int AS correct_count,
  max(sa.answered_at)::timestamptz AS last_answered_at
FROM session_answer sa
JOIN exam_session es ON es.id = sa.session_id
JOIN profile p ON p.id = es.profile_id AND p.kind = 'user'
WHERE sa.is_correct
  AND sa.answered_at >= $1
  AND sa.answered_at < $2
GROUP BY es.profile_id
`

type CountCorrectAnswersByProfileInRangeParams struct {
	FromTs pgtype.Timestamptz `json:"from_ts"`
	ToTs   pgtype.Timestamptz `json:"to_ts"`
}

type CountCorrectAnswersByProfileInRangeRow struct {
	ProfileID      uuid.UUID          `json:"profile_id"`
	CorrectCount   int32              `json:"correct_count"`
	LastAnsweredAt pgtype.Timestamptz `json:"last_answered_at"`
}

// Used by leaderboard.Service.RebuildPeriod to recompute a Redis sorted
// set from the durable session_answer table. from_ts is inclusive, to_ts
// is exclusive.
func (q *Queries) CountCorrectAnswersByProfileInRange(ctx context.Context, arg CountCorrectAnswersByProfileInRangeParams) ([]CountCorrectAnswersByProfileInRangeRow, error) {
	rows, err := q.db.Query(ctx, countCorrectAnswersByProfileInRange, arg.FromTs, arg.ToTs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountCorrectAnswersByProfileInRangeRow
	for rows.Next() {
		var i CountCorrectAnswersByProfileInRangeRow
		if err := rows.Scan(&i.ProfileID, &i.CorrectCount, &i.LastAnsweredAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileNamesByIDs = `-- name: ListProfileNamesByIDs :many
SELECT id, name FROM profile WHERE id = ANY($1::uuid[])
`

type ListProfileNamesByIDsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// Batch name resolution for leaderboard display (top-N + around-you +
// the requesting profile). Never exposes phone numbers.
func (q *Queries) ListProfileNamesByIDs(ctx context.Context, ids []uuid.UUID) ([]ListProfileNamesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listProfileNamesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProfileNamesByIDsRow
	for rows.Next() {
		var i ListProfileNamesByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
