// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDueQuestions = `-- name: CountDueQuestions :one
SELECT count(*)::int FROM question_memory
WHERE profile_id = $1 AND due_at <= now()
`

func (q *Queries) CountDueQuestions(ctx context.Context, profileID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countDueQuestions, profileID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countValidQuestionsByCategory = `-- name: CountValidQuestionsByCategory :many
SELECT category_id, count(*)::int AS question_count
FROM question WHERE validation_status = 'valid'
GROUP BY category_id
`

type CountValidQuestionsByCategoryRow struct {
	CategoryID    uuid.UUID `json:"category_id"`
	QuestionCount int32     `json:"question_count"`
}

func (q *Queries) CountValidQuestionsByCategory(ctx context.Context) ([]CountValidQuestionsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, countValidQuestionsByCategory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountValidQuestionsByCategoryRow
	for rows.Next() {
		var i CountValidQuestionsByCategoryRow
		if err := rows.Scan(&i.CategoryID, &i.QuestionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryMastery = `-- name: GetCategoryMastery :one
SELECT profile_id, category_id, mastery, seen, correct, updated_at FROM category_mastery
WHERE profile_id = $1 AND category_id = $2
`

type GetCategoryMasteryParams struct {
	ProfileID  uuid.UUID `json:"profile_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) GetCategoryMastery(ctx context.Context, arg GetCategoryMasteryParams) (CategoryMastery, error) {
	row := q.db.QueryRow(ctx, getCategoryMastery, arg.ProfileID, arg.CategoryID)
	var i CategoryMastery
	err := row.Scan(
		&i.ProfileID,
		&i.CategoryID,
		&i.Mastery,
		&i.Seen,
		&i.Correct,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestionCategoryID = `-- name: GetQuestionCategoryID :one
SELECT category_id FROM question WHERE id = $1
`

func (q *Queries) GetQuestionCategoryID(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getQuestionCategoryID, id)
	var category_id uuid.UUID
	err := row.Scan(&category_id)
	return category_id, err
}

const getQuestionMemory = `-- name: GetQuestionMemory :one
SELECT profile_id, question_id, stability, difficulty, due_at, last_reviewed_at, reps, lapses, state FROM question_memory
WHERE profile_id = $1 AND question_id = $2
`

type GetQuestionMemoryParams struct {
	ProfileID  uuid.UUID `json:"profile_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) GetQuestionMemory(ctx context.Context, arg GetQuestionMemoryParams) (QuestionMemory, error) {
	row := q.db.QueryRow(ctx, getQuestionMemory, arg.ProfileID, arg.QuestionID)
	var i QuestionMemory
	err := row.Scan(
		&i.ProfileID,
		&i.QuestionID,
		&i.Stability,
		&i.Difficulty,
		&i.DueAt,
		&i.LastReviewedAt,
		&i.Reps,
		&i.Lapses,
		&i.State,
	)
	return i, err
}

const listCategoryMasteryForProfile = `-- name: ListCategoryMasteryForProfile :many
SELECT profile_id, category_id, mastery, seen, correct, updated_at FROM category_mastery WHERE profile_id = $1
`

func (q *Queries) ListCategoryMasteryForProfile(ctx context.Context, profileID uuid.UUID) ([]CategoryMastery, error) {
	rows, err := q.db.Query(ctx, listCategoryMasteryForProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryMastery
	for rows.Next() {
		var i CategoryMastery
		if err := rows.Scan(
			&i.ProfileID,
			&i.CategoryID,
			&i.Mastery,
			&i.Seen,
			&i.Correct,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueQuestions = `-- name: ListDueQuestions :many
SELECT qm.question_id, q.category_id
FROM question_memory qm
JOIN question q ON q.id = qm.question_id AND q.validation_status = 'valid'
WHERE qm.profile_id = $1 AND qm.due_at <= now()
ORDER BY qm.due_at ASC
LIMIT $2
`

type ListDueQuestionsParams struct {
	ProfileID  uuid.UUID `json:"profile_id"`
	LimitCount int32     `json:"limit_count"`
}

type ListDueQuestionsRow struct {
	QuestionID uuid.UUID `json:"question_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) ListDueQuestions(ctx context.Context, arg ListDueQuestionsParams) ([]ListDueQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listDueQuestions, arg.ProfileID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueQuestionsRow
	for rows.Next() {
		var i ListDueQuestionsRow
		if err := rows.Scan(&i.QuestionID, &i.CategoryID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCategoryMastery = `-- name: UpsertCategoryMastery :one
INSERT INTO category_mastery (profile_id, category_id, mastery, seen, correct, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (profile_id, category_id) DO UPDATE SET
  mastery    = EXCLUDED.mastery,
  seen       = EXCLUDED.seen,
  correct    = EXCLUDED.correct,
  updated_at = now()
RETURNING profile_id, category_id, mastery, seen, correct, updated_at
`

type UpsertCategoryMasteryParams struct {
	ProfileID  uuid.UUID `json:"profile_id"`
	CategoryID uuid.UUID `json:"category_id"`
	Mastery    float32   `json:"mastery"`
	Seen       int32     `json:"seen"`
	Correct    int32     `json:"correct"`
}

func (q *Queries) UpsertCategoryMastery(ctx context.Context, arg UpsertCategoryMasteryParams) (CategoryMastery, error) {
	row := q.db.QueryRow(ctx, upsertCategoryMastery,
		arg.ProfileID,
		arg.CategoryID,
		arg.Mastery,
		arg.Seen,
		arg.Correct,
	)
	var i CategoryMastery
	err := row.Scan(
		&i.ProfileID,
		&i.CategoryID,
		&i.Mastery,
		&i.Seen,
		&i.Correct,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertQuestionMemory = `-- name: UpsertQuestionMemory :one
INSERT INTO question_memory
  (profile_id, question_id, stability, difficulty, due_at, last_reviewed_at, reps, lapses, state)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (profile_id, question_id) DO UPDATE SET
  stability        = EXCLUDED.stability,
  difficulty       = EXCLUDED.difficulty,
  due_at           = EXCLUDED.due_at,
  last_reviewed_at = EXCLUDED.last_reviewed_at,
  reps             = EXCLUDED.reps,
  lapses           = EXCLUDED.lapses,
  state            = EXCLUDED.state
RETURNING profile_id, question_id, stability, difficulty, due_at, last_reviewed_at, reps, lapses, state
`

type UpsertQuestionMemoryParams struct {
	ProfileID      uuid.UUID          `json:"profile_id"`
	QuestionID     uuid.UUID          `json:"question_id"`
	Stability      float32            `json:"stability"`
	Difficulty     float32            `json:"difficulty"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	LastReviewedAt pgtype.Timestamptz `json:"last_reviewed_at"`
	Reps           int32              `json:"reps"`
	Lapses         int32              `json:"lapses"`
	State          int16              `json:"state"`
}

func (q *Queries) UpsertQuestionMemory(ctx context.Context, arg UpsertQuestionMemoryParams) (QuestionMemory, error) {
	row := q.db.QueryRow(ctx, upsertQuestionMemory,
		arg.ProfileID,
		arg.QuestionID,
		arg.Stability,
		arg.Difficulty,
		arg.DueAt,
		arg.LastReviewedAt,
		arg.Reps,
		arg.Lapses,
		arg.State,
	)
	var i QuestionMemory
	err := row.Scan(
		&i.ProfileID,
		&i.QuestionID,
		&i.Stability,
		&i.Difficulty,
		&i.DueAt,
		&i.LastReviewedAt,
		&i.Reps,
		&i.Lapses,
		&i.State,
	)
	return i, err
}
