// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manual_pay.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimManualPayAssignment = `-- name: ClaimManualPayAssignment :exec
UPDATE manual_pay_assignment
SET manual_state = CASE
      WHEN manual_state = 'awaiting_transfer' THEN 'claimed'
      ELSE manual_state
    END,
    claimed_at = COALESCE(claimed_at, now())
WHERE payment_id = $1
  AND manual_state IN ('awaiting_transfer', 'claimed', 'awaiting_review')
`

func (q *Queries) ClaimManualPayAssignment(ctx context.Context, paymentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, claimManualPayAssignment, paymentID)
	return err
}

const deleteManualPayCard = `-- name: DeleteManualPayCard :exec
DELETE FROM manual_pay_card WHERE id = $1
`

func (q *Queries) DeleteManualPayCard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteManualPayCard, id)
	return err
}

const findManualPayMatchCandidate = `-- name: FindManualPayMatchCandidate :one
SELECT a.payment_id, a.id AS assignment_id, a.assigned_at, a.amount_uzs, a.manual_state
FROM manual_pay_assignment a
JOIN manual_pay_card c ON c.id = a.card_id
JOIN payment p ON p.id = a.payment_id
WHERE c.pan_last4 = $1
  AND a.amount_uzs = $2
  AND a.manual_state IN ('awaiting_transfer', 'claimed', 'awaiting_review')
  AND p.status IN ('created', 'pending')
  AND $3::timestamptz
      BETWEEN a.assigned_at - interval '90 seconds'
          AND a.hold_until + interval '24 hours'
ORDER BY a.assigned_at DESC
LIMIT 1
`

type FindManualPayMatchCandidateParams struct {
	PanLast4   string             `json:"pan_last4"`
	AmountUzs  int64              `json:"amount_uzs"`
	TransferAt pgtype.Timestamptz `json:"transfer_at"`
}

type FindManualPayMatchCandidateRow struct {
	PaymentID    uuid.UUID          `json:"payment_id"`
	AssignmentID uuid.UUID          `json:"assignment_id"`
	AssignedAt   pgtype.Timestamptz `json:"assigned_at"`
	AmountUzs    int64              `json:"amount_uzs"`
	ManualState  string             `json:"manual_state"`
}

// Match an open assignment by (last4, exact amount) inside a bounded window.
//
// Amounts are unique per card among open assignments (see
// ListOpenManualAmountsForCard), so at most one row can match and the old
// "newest assignment on the card wins" tie-break is gone. That tie-break was
// exploitable: with only 4 cards x 3 tariff prices, an attacker could loop
// checkouts to always own the newest assignment on a card and have a genuine
// late payer's transfer confirm HIS payment instead.
//
// The window is bounded at both ends. Lower: the bank push carries only
// HH:MM, so transfer_at has its seconds zeroed and can legitimately read up
// to 59s before assigned_at — without the tolerance, anyone paying in the
// same minute they checked out failed to auto-confirm. Upper: hold_until
// plus a day of grace keeps genuinely late transfers working while stopping
// an abandoned assignment from staying claimable forever and capturing an
// unrelated future credit.
func (q *Queries) FindManualPayMatchCandidate(ctx context.Context, arg FindManualPayMatchCandidateParams) (FindManualPayMatchCandidateRow, error) {
	row := q.db.QueryRow(ctx, findManualPayMatchCandidate, arg.PanLast4, arg.AmountUzs, arg.TransferAt)
	var i FindManualPayMatchCandidateRow
	err := row.Scan(
		&i.PaymentID,
		&i.AssignmentID,
		&i.AssignedAt,
		&i.AmountUzs,
		&i.ManualState,
	)
	return i, err
}

const getManualPayAssignmentByPayment = `-- name: GetManualPayAssignmentByPayment :one
SELECT a.id, a.payment_id, a.card_id, a.amount_uzs, a.assigned_at, a.hold_until, a.released_at,
       a.manual_state, a.claimed_at, a.confirmed_by, a.confirmed_at, a.admin_note, a.created_at,
       c.pan_full, c.pan_last4, c.holder_name, c.network
FROM manual_pay_assignment a
JOIN manual_pay_card c ON c.id = a.card_id
WHERE a.payment_id = $1
`

type GetManualPayAssignmentByPaymentRow struct {
	ID          uuid.UUID          `json:"id"`
	PaymentID   uuid.UUID          `json:"payment_id"`
	CardID      uuid.UUID          `json:"card_id"`
	AmountUzs   int64              `json:"amount_uzs"`
	AssignedAt  pgtype.Timestamptz `json:"assigned_at"`
	HoldUntil   pgtype.Timestamptz `json:"hold_until"`
	ReleasedAt  pgtype.Timestamptz `json:"released_at"`
	ManualState string             `json:"manual_state"`
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
	ConfirmedBy pgtype.Text        `json:"confirmed_by"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
	AdminNote   pgtype.Text        `json:"admin_note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PanFull     string             `json:"pan_full"`
	PanLast4    string             `json:"pan_last4"`
	HolderName  string             `json:"holder_name"`
	Network     string             `json:"network"`
}

func (q *Queries) GetManualPayAssignmentByPayment(ctx context.Context, paymentID uuid.UUID) (GetManualPayAssignmentByPaymentRow, error) {
	row := q.db.QueryRow(ctx, getManualPayAssignmentByPayment, paymentID)
	var i GetManualPayAssignmentByPaymentRow
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.CardID,
		&i.AmountUzs,
		&i.AssignedAt,
		&i.HoldUntil,
		&i.ReleasedAt,
		&i.ManualState,
		&i.ClaimedAt,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.AdminNote,
		&i.CreatedAt,
		&i.PanFull,
		&i.PanLast4,
		&i.HolderName,
		&i.Network,
	)
	return i, err
}

const getManualPayAssignmentByPaymentForUpdate = `-- name: GetManualPayAssignmentByPaymentForUpdate :one
SELECT a.id, a.payment_id, a.card_id, a.amount_uzs, a.assigned_at, a.hold_until, a.released_at,
       a.manual_state, a.claimed_at, a.confirmed_by, a.confirmed_at, a.admin_note, a.created_at
FROM manual_pay_assignment a
WHERE a.payment_id = $1
FOR UPDATE
`

func (q *Queries) GetManualPayAssignmentByPaymentForUpdate(ctx context.Context, paymentID uuid.UUID) (ManualPayAssignment, error) {
	row := q.db.QueryRow(ctx, getManualPayAssignmentByPaymentForUpdate, paymentID)
	var i ManualPayAssignment
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.CardID,
		&i.AmountUzs,
		&i.AssignedAt,
		&i.HoldUntil,
		&i.ReleasedAt,
		&i.ManualState,
		&i.ClaimedAt,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.AdminNote,
		&i.CreatedAt,
	)
	return i, err
}

const getManualPayCard = `-- name: GetManualPayCard :one
SELECT id, network, pan_full, pan_last4, holder_name, sort_order, enabled, created_at, updated_at
FROM manual_pay_card
WHERE id = $1
`

func (q *Queries) GetManualPayCard(ctx context.Context, id uuid.UUID) (ManualPayCard, error) {
	row := q.db.QueryRow(ctx, getManualPayCard, id)
	var i ManualPayCard
	err := row.Scan(
		&i.ID,
		&i.Network,
		&i.PanFull,
		&i.PanLast4,
		&i.HolderName,
		&i.SortOrder,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getManualPayEventByFingerprint = `-- name: GetManualPayEventByFingerprint :one
SELECT id, fingerprint, telegram_msg_id, raw_text, amount_uzs, pan_last4, transfer_at, balance_uzs,
       status, matched_payment_id, parse_ok, created_at
FROM manual_pay_event
WHERE fingerprint = $1
`

func (q *Queries) GetManualPayEventByFingerprint(ctx context.Context, fingerprint string) (ManualPayEvent, error) {
	row := q.db.QueryRow(ctx, getManualPayEventByFingerprint, fingerprint)
	var i ManualPayEvent
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.TelegramMsgID,
		&i.RawText,
		&i.AmountUzs,
		&i.PanLast4,
		&i.TransferAt,
		&i.BalanceUzs,
		&i.Status,
		&i.MatchedPaymentID,
		&i.ParseOk,
		&i.CreatedAt,
	)
	return i, err
}

const getManualTgSettings = `-- name: GetManualTgSettings :one
SELECT id, api_id_enc, api_hash_enc, session_enc, humo_bot_username,
       last_test_ok, last_test_at, last_test_detail, updated_at
FROM manual_tg_settings
WHERE id = 1
`

func (q *Queries) GetManualTgSettings(ctx context.Context) (ManualTgSetting, error) {
	row := q.db.QueryRow(ctx, getManualTgSettings)
	var i ManualTgSetting
	err := row.Scan(
		&i.ID,
		&i.ApiIDEnc,
		&i.ApiHashEnc,
		&i.SessionEnc,
		&i.HumoBotUsername,
		&i.LastTestOk,
		&i.LastTestAt,
		&i.LastTestDetail,
		&i.UpdatedAt,
	)
	return i, err
}

const insertManualPayAssignment = `-- name: InsertManualPayAssignment :one
INSERT INTO manual_pay_assignment (
  payment_id, card_id, amount_uzs, assigned_at, hold_until, manual_state
) VALUES ($1, $2, $3, $4, $5, 'awaiting_transfer')
RETURNING id, payment_id, card_id, amount_uzs, assigned_at, hold_until, released_at,
          manual_state, claimed_at, confirmed_by, confirmed_at, admin_note, created_at
`

type InsertManualPayAssignmentParams struct {
	PaymentID  uuid.UUID          `json:"payment_id"`
	CardID     uuid.UUID          `json:"card_id"`
	AmountUzs  int64              `json:"amount_uzs"`
	AssignedAt pgtype.Timestamptz `json:"assigned_at"`
	HoldUntil  pgtype.Timestamptz `json:"hold_until"`
}

func (q *Queries) InsertManualPayAssignment(ctx context.Context, arg InsertManualPayAssignmentParams) (ManualPayAssignment, error) {
	row := q.db.QueryRow(ctx, insertManualPayAssignment,
		arg.PaymentID,
		arg.CardID,
		arg.AmountUzs,
		arg.AssignedAt,
		arg.HoldUntil,
	)
	var i ManualPayAssignment
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.CardID,
		&i.AmountUzs,
		&i.AssignedAt,
		&i.HoldUntil,
		&i.ReleasedAt,
		&i.ManualState,
		&i.ClaimedAt,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.AdminNote,
		&i.CreatedAt,
	)
	return i, err
}

const insertManualPayCard = `-- name: InsertManualPayCard :one
INSERT INTO manual_pay_card (network, pan_full, pan_last4, holder_name, sort_order, enabled)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, network, pan_full, pan_last4, holder_name, sort_order, enabled, created_at, updated_at
`

type InsertManualPayCardParams struct {
	Network    string `json:"network"`
	PanFull    string `json:"pan_full"`
	PanLast4   string `json:"pan_last4"`
	HolderName string `json:"holder_name"`
	SortOrder  int32  `json:"sort_order"`
	Enabled    bool   `json:"enabled"`
}

func (q *Queries) InsertManualPayCard(ctx context.Context, arg InsertManualPayCardParams) (ManualPayCard, error) {
	row := q.db.QueryRow(ctx, insertManualPayCard,
		arg.Network,
		arg.PanFull,
		arg.PanLast4,
		arg.HolderName,
		arg.SortOrder,
		arg.Enabled,
	)
	var i ManualPayCard
	err := row.Scan(
		&i.ID,
		&i.Network,
		&i.PanFull,
		&i.PanLast4,
		&i.HolderName,
		&i.SortOrder,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertManualPayEvent = `-- name: InsertManualPayEvent :one
INSERT INTO manual_pay_event (
  fingerprint, telegram_msg_id, raw_text, amount_uzs, pan_last4, transfer_at, balance_uzs, status, matched_payment_id, parse_ok
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, fingerprint, telegram_msg_id, raw_text, amount_uzs, pan_last4, transfer_at, balance_uzs,
          status, matched_payment_id, parse_ok, created_at
`

type InsertManualPayEventParams struct {
	Fingerprint      string             `json:"fingerprint"`
	TelegramMsgID    pgtype.Int8        `json:"telegram_msg_id"`
	RawText          string             `json:"raw_text"`
	AmountUzs        pgtype.Int8        `json:"amount_uzs"`
	PanLast4         pgtype.Text        `json:"pan_last4"`
	TransferAt       pgtype.Timestamptz `json:"transfer_at"`
	BalanceUzs       pgtype.Int8        `json:"balance_uzs"`
	Status           string             `json:"status"`
	MatchedPaymentID uuid.NullUUID      `json:"matched_payment_id"`
	ParseOk          bool               `json:"parse_ok"`
}

func (q *Queries) InsertManualPayEvent(ctx context.Context, arg InsertManualPayEventParams) (ManualPayEvent, error) {
	row := q.db.QueryRow(ctx, insertManualPayEvent,
		arg.Fingerprint,
		arg.TelegramMsgID,
		arg.RawText,
		arg.AmountUzs,
		arg.PanLast4,
		arg.TransferAt,
		arg.BalanceUzs,
		arg.Status,
		arg.MatchedPaymentID,
		arg.ParseOk,
	)
	var i ManualPayEvent
	err := row.Scan(
		&i.ID,
		&i.Fingerprint,
		&i.TelegramMsgID,
		&i.RawText,
		&i.AmountUzs,
		&i.PanLast4,
		&i.TransferAt,
		&i.BalanceUzs,
		&i.Status,
		&i.MatchedPaymentID,
		&i.ParseOk,
		&i.CreatedAt,
	)
	return i, err
}

const listEnabledManualPayCards = `-- name: ListEnabledManualPayCards :many
SELECT id, network, pan_full, pan_last4, holder_name, sort_order, enabled, created_at, updated_at
FROM manual_pay_card
WHERE enabled = true
ORDER BY sort_order, created_at
`

func (q *Queries) ListEnabledManualPayCards(ctx context.Context) ([]ManualPayCard, error) {
	rows, err := q.db.Query(ctx, listEnabledManualPayCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManualPayCard
	for rows.Next() {
		var i ManualPayCard
		if err := rows.Scan(
			&i.ID,
			&i.Network,
			&i.PanFull,
			&i.PanLast4,
			&i.HolderName,
			&i.SortOrder,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManualPayCards = `-- name: ListManualPayCards :many
SELECT id, network, pan_full, pan_last4, holder_name, sort_order, enabled, created_at, updated_at
FROM manual_pay_card
ORDER BY sort_order, created_at
`

func (q *Queries) ListManualPayCards(ctx context.Context) ([]ManualPayCard, error) {
	rows, err := q.db.Query(ctx, listManualPayCards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManualPayCard
	for rows.Next() {
		var i ManualPayCard
		if err := rows.Scan(
			&i.ID,
			&i.Network,
			&i.PanFull,
			&i.PanLast4,
			&i.HolderName,
			&i.SortOrder,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenManualAmountsForCard = `-- name: ListOpenManualAmountsForCard :many
SELECT a.amount_uzs
FROM manual_pay_assignment a
JOIN payment p ON p.id = a.payment_id
WHERE a.card_id = $1
  AND a.manual_state IN ('awaiting_transfer', 'claimed', 'awaiting_review')
  AND p.status IN ('created', 'pending')
`

// Amounts currently claimable on one card. StartManualCheckout picks an
// amount not in this set so every open assignment on a card is uniquely
// identifiable by the transferred sum. The predicate must stay identical to
// FindManualPayMatchCandidate's, or a "free" amount could collide with an
// assignment that is in fact still matchable.
func (q *Queries) ListOpenManualAmountsForCard(ctx context.Context, cardID uuid.UUID) ([]int64, error) {
	rows, err := q.db.Query(ctx, listOpenManualAmountsForCard, cardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var amount_uzs int64
		if err := rows.Scan(&amount_uzs); err != nil {
			return nil, err
		}
		items = append(items, amount_uzs)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenManualPayAssignments = `-- name: ListOpenManualPayAssignments :many
SELECT a.id, a.payment_id, a.card_id, a.amount_uzs, a.assigned_at, a.hold_until, a.released_at,
       a.manual_state, a.claimed_at, a.confirmed_by, a.confirmed_at, a.admin_note, a.created_at,
       c.pan_last4, c.holder_name, c.network,
       p.profile_id, p.status AS payment_status, p.provider,
       pr.phone AS profile_phone
FROM manual_pay_assignment a
JOIN manual_pay_card c ON c.id = a.card_id
JOIN payment p ON p.id = a.payment_id
JOIN profile pr ON pr.id = p.profile_id
WHERE a.manual_state IN ('awaiting_transfer', 'claimed', 'awaiting_review')
ORDER BY a.assigned_at DESC
LIMIT $1
`

type ListOpenManualPayAssignmentsRow struct {
	ID            uuid.UUID          `json:"id"`
	PaymentID     uuid.UUID          `json:"payment_id"`
	CardID        uuid.UUID          `json:"card_id"`
	AmountUzs     int64              `json:"amount_uzs"`
	AssignedAt    pgtype.Timestamptz `json:"assigned_at"`
	HoldUntil     pgtype.Timestamptz `json:"hold_until"`
	ReleasedAt    pgtype.Timestamptz `json:"released_at"`
	ManualState   string             `json:"manual_state"`
	ClaimedAt     pgtype.Timestamptz `json:"claimed_at"`
	ConfirmedBy   pgtype.Text        `json:"confirmed_by"`
	ConfirmedAt   pgtype.Timestamptz `json:"confirmed_at"`
	AdminNote     pgtype.Text        `json:"admin_note"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PanLast4      string             `json:"pan_last4"`
	HolderName    string             `json:"holder_name"`
	Network       string             `json:"network"`
	ProfileID     uuid.UUID          `json:"profile_id"`
	PaymentStatus string             `json:"payment_status"`
	Provider      string             `json:"provider"`
	ProfilePhone  string             `json:"profile_phone"`
}

func (q *Queries) ListOpenManualPayAssignments(ctx context.Context, limit int32) ([]ListOpenManualPayAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listOpenManualPayAssignments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOpenManualPayAssignmentsRow
	for rows.Next() {
		var i ListOpenManualPayAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.CardID,
			&i.AmountUzs,
			&i.AssignedAt,
			&i.HoldUntil,
			&i.ReleasedAt,
			&i.ManualState,
			&i.ClaimedAt,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
			&i.AdminNote,
			&i.CreatedAt,
			&i.PanLast4,
			&i.HolderName,
			&i.Network,
			&i.ProfileID,
			&i.PaymentStatus,
			&i.Provider,
			&i.ProfilePhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnmatchedManualPayEvents = `-- name: ListUnmatchedManualPayEvents :many
SELECT id, fingerprint, telegram_msg_id, raw_text, amount_uzs, pan_last4, transfer_at, balance_uzs,
       status, matched_payment_id, parse_ok, created_at
FROM manual_pay_event
WHERE status = 'unmatched'
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListUnmatchedManualPayEvents(ctx context.Context, limit int32) ([]ManualPayEvent, error) {
	rows, err := q.db.Query(ctx, listUnmatchedManualPayEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ManualPayEvent
	for rows.Next() {
		var i ManualPayEvent
		if err := rows.Scan(
			&i.ID,
			&i.Fingerprint,
			&i.TelegramMsgID,
			&i.RawText,
			&i.AmountUzs,
			&i.PanLast4,
			&i.TransferAt,
			&i.BalanceUzs,
			&i.Status,
			&i.MatchedPaymentID,
			&i.ParseOk,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFreeManualPayCard = `-- name: LockFreeManualPayCard :one
SELECT c.id, c.network, c.pan_full, c.pan_last4, c.holder_name, c.sort_order, c.enabled, c.created_at, c.updated_at
FROM manual_pay_card c
WHERE c.enabled = true
  AND NOT EXISTS (
    SELECT 1 FROM manual_pay_assignment a
    WHERE a.card_id = c.id AND a.released_at IS NULL
  )
ORDER BY c.sort_order, c.created_at
FOR UPDATE OF c SKIP LOCKED
LIMIT 1
`

// Pick an enabled card with no active (unreleased) hold. Caller must run
// ReleaseExpiredManualHolds first in the same transaction.
func (q *Queries) LockFreeManualPayCard(ctx context.Context) (ManualPayCard, error) {
	row := q.db.QueryRow(ctx, lockFreeManualPayCard)
	var i ManualPayCard
	err := row.Scan(
		&i.ID,
		&i.Network,
		&i.PanFull,
		&i.PanLast4,
		&i.HolderName,
		&i.SortOrder,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markManualPayAssignmentConsumed = `-- name: MarkManualPayAssignmentConsumed :exec
UPDATE manual_pay_assignment
SET manual_state = 'consumed',
    confirmed_by = $2,
    confirmed_at = now(),
    released_at = COALESCE(released_at, now())
WHERE payment_id = $1
`

type MarkManualPayAssignmentConsumedParams struct {
	PaymentID   uuid.UUID   `json:"payment_id"`
	ConfirmedBy pgtype.Text `json:"confirmed_by"`
}

func (q *Queries) MarkManualPayAssignmentConsumed(ctx context.Context, arg MarkManualPayAssignmentConsumedParams) error {
	_, err := q.db.Exec(ctx, markManualPayAssignmentConsumed, arg.PaymentID, arg.ConfirmedBy)
	return err
}

const markManualPayEventIgnored = `-- name: MarkManualPayEventIgnored :exec
UPDATE manual_pay_event
SET status = 'ignored'
WHERE id = $1
`

func (q *Queries) MarkManualPayEventIgnored(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markManualPayEventIgnored, id)
	return err
}

const markManualPayEventMatched = `-- name: MarkManualPayEventMatched :exec
UPDATE manual_pay_event
SET status = 'matched', matched_payment_id = $2
WHERE id = $1
`

type MarkManualPayEventMatchedParams struct {
	ID               uuid.UUID     `json:"id"`
	MatchedPaymentID uuid.NullUUID `json:"matched_payment_id"`
}

func (q *Queries) MarkManualPayEventMatched(ctx context.Context, arg MarkManualPayEventMatchedParams) error {
	_, err := q.db.Exec(ctx, markManualPayEventMatched, arg.ID, arg.MatchedPaymentID)
	return err
}

const rejectManualPayAssignment = `-- name: RejectManualPayAssignment :exec
UPDATE manual_pay_assignment
SET manual_state = 'rejected',
    confirmed_by = 'admin',
    confirmed_at = now(),
    released_at = COALESCE(released_at, now()),
    admin_note = $2
WHERE payment_id = $1
  AND manual_state IN ('awaiting_transfer', 'claimed', 'awaiting_review')
`

type RejectManualPayAssignmentParams struct {
	PaymentID uuid.UUID   `json:"payment_id"`
	AdminNote pgtype.Text `json:"admin_note"`
}

func (q *Queries) RejectManualPayAssignment(ctx context.Context, arg RejectManualPayAssignmentParams) error {
	_, err := q.db.Exec(ctx, rejectManualPayAssignment, arg.PaymentID, arg.AdminNote)
	return err
}

const releaseExpiredManualHolds = `-- name: ReleaseExpiredManualHolds :exec
UPDATE manual_pay_assignment
SET released_at = now(),
    manual_state = CASE
      WHEN manual_state IN ('awaiting_transfer', 'claimed') THEN 'awaiting_review'
      ELSE manual_state
    END
WHERE released_at IS NULL
  AND hold_until <= now()
  AND manual_state IN ('awaiting_transfer', 'claimed')
`

// Path B: free the card after hold_until; keep assignment open for late push / admin.
func (q *Queries) ReleaseExpiredManualHolds(ctx context.Context) error {
	_, err := q.db.Exec(ctx, releaseExpiredManualHolds)
	return err
}

const setManualTgTestResult = `-- name: SetManualTgTestResult :exec
UPDATE manual_tg_settings
SET last_test_ok = $1,
    last_test_at = now(),
    last_test_detail = $2,
    updated_at = now()
WHERE id = 1
`

type SetManualTgTestResultParams struct {
	LastTestOk     pgtype.Bool `json:"last_test_ok"`
	LastTestDetail pgtype.Text `json:"last_test_detail"`
}

func (q *Queries) SetManualTgTestResult(ctx context.Context, arg SetManualTgTestResultParams) error {
	_, err := q.db.Exec(ctx, setManualTgTestResult, arg.LastTestOk, arg.LastTestDetail)
	return err
}

const setPaymentCanceled = `-- name: SetPaymentCanceled :exec
UPDATE payment SET status = 'canceled' WHERE id = $1 AND status IN ('created', 'pending')
`

func (q *Queries) SetPaymentCanceled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setPaymentCanceled, id)
	return err
}

const setPaymentPending = `-- name: SetPaymentPending :exec
UPDATE payment SET status = 'pending' WHERE id = $1 AND status = 'created'
`

func (q *Queries) SetPaymentPending(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setPaymentPending, id)
	return err
}

const updateManualPayCard = `-- name: UpdateManualPayCard :one
UPDATE manual_pay_card
SET pan_full = $2,
    pan_last4 = $3,
    holder_name = $4,
    sort_order = $5,
    enabled = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, network, pan_full, pan_last4, holder_name, sort_order, enabled, created_at, updated_at
`

type UpdateManualPayCardParams struct {
	ID         uuid.UUID `json:"id"`
	PanFull    string    `json:"pan_full"`
	PanLast4   string    `json:"pan_last4"`
	HolderName string    `json:"holder_name"`
	SortOrder  int32     `json:"sort_order"`
	Enabled    bool      `json:"enabled"`
}

func (q *Queries) UpdateManualPayCard(ctx context.Context, arg UpdateManualPayCardParams) (ManualPayCard, error) {
	row := q.db.QueryRow(ctx, updateManualPayCard,
		arg.ID,
		arg.PanFull,
		arg.PanLast4,
		arg.HolderName,
		arg.SortOrder,
		arg.Enabled,
	)
	var i ManualPayCard
	err := row.Scan(
		&i.ID,
		&i.Network,
		&i.PanFull,
		&i.PanLast4,
		&i.HolderName,
		&i.SortOrder,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertManualTgSettings = `-- name: UpsertManualTgSettings :one
UPDATE manual_tg_settings
SET api_id_enc = CASE WHEN $1::bool THEN $2 ELSE api_id_enc END,
    api_hash_enc = CASE WHEN $3::bool THEN $4 ELSE api_hash_enc END,
    session_enc = CASE WHEN $5::bool THEN $6 ELSE session_enc END,
    humo_bot_username = CASE WHEN $7::bool THEN $8 ELSE humo_bot_username END,
    updated_at = now()
WHERE id = 1
RETURNING id, api_id_enc, api_hash_enc, session_enc, humo_bot_username,
          last_test_ok, last_test_at, last_test_detail, updated_at
`

type UpsertManualTgSettingsParams struct {
	SetApiID        bool        `json:"set_api_id"`
	ApiIDEnc        pgtype.Text `json:"api_id_enc"`
	SetApiHash      bool        `json:"set_api_hash"`
	ApiHashEnc      pgtype.Text `json:"api_hash_enc"`
	SetSession      bool        `json:"set_session"`
	SessionEnc      pgtype.Text `json:"session_enc"`
	SetBotUsername  bool        `json:"set_bot_username"`
	HumoBotUsername string      `json:"humo_bot_username"`
}

func (q *Queries) UpsertManualTgSettings(ctx context.Context, arg UpsertManualTgSettingsParams) (ManualTgSetting, error) {
	row := q.db.QueryRow(ctx, upsertManualTgSettings,
		arg.SetApiID,
		arg.ApiIDEnc,
		arg.SetApiHash,
		arg.ApiHashEnc,
		arg.SetSession,
		arg.SessionEnc,
		arg.SetBotUsername,
		arg.HumoBotUsername,
	)
	var i ManualTgSetting
	err := row.Scan(
		&i.ID,
		&i.ApiIDEnc,
		&i.ApiHashEnc,
		&i.SessionEnc,
		&i.HumoBotUsername,
		&i.LastTestOk,
		&i.LastTestAt,
		&i.LastTestDetail,
		&i.UpdatedAt,
	)
	return i, err
}
