// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminAuditLog struct {
	ID          uuid.UUID          `json:"id"`
	AdminUserID uuid.NullUUID      `json:"admin_user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.Text        `json:"entity_id"`
	BeforeJson  []byte             `json:"before_json"`
	AfterJson   []byte             `json:"after_json"`
	Ip          *netip.Addr        `json:"ip"`
	Ua          string             `json:"ua"`
	RequestID   string             `json:"request_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AdminPermission struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	Description string    `json:"description"`
}

type AdminRole struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

type AdminRolePermission struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type AdminSession struct {
	ID          uuid.UUID          `json:"id"`
	AdminUserID uuid.UUID          `json:"admin_user_id"`
	RefreshHash string             `json:"refresh_hash"`
	Ip          *netip.Addr        `json:"ip"`
	Ua          string             `json:"ua"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AdminUser struct {
	ID            uuid.UUID          `json:"id"`
	Email         string             `json:"email"`
	Phone         pgtype.Text        `json:"phone"`
	DisplayName   string             `json:"display_name"`
	PasswordHash  string             `json:"password_hash"`
	Status        string             `json:"status"`
	TotpSecretEnc pgtype.Text        `json:"totp_secret_enc"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AdminUserRole struct {
	AdminUserID uuid.UUID `json:"admin_user_id"`
	RoleID      uuid.UUID `json:"role_id"`
}

type AlertRule struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Kind        string             `json:"kind"`
	Enabled     bool               `json:"enabled"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Answer struct {
	ID         uuid.UUID     `json:"id"`
	QuestionID uuid.UUID     `json:"question_id"`
	Position   int16         `json:"position"`
	IsCorrect  bool          `json:"is_correct"`
	ImageID    uuid.NullUUID `json:"image_id"`
}

type AnswerTranslation struct {
	AnswerID uuid.UUID `json:"answer_id"`
	Locale   string    `json:"locale"`
	Text     string    `json:"text"`
	Status   string    `json:"status"`
}

type ArenaAnswer struct {
	MatchID    uuid.UUID          `json:"match_id"`
	ProfileID  uuid.UUID          `json:"profile_id"`
	QuestionID uuid.UUID          `json:"question_id"`
	Position   int16              `json:"position"`
	AnswerID   uuid.NullUUID      `json:"answer_id"`
	IsCorrect  bool               `json:"is_correct"`
	ResponseMs pgtype.Int4        `json:"response_ms"`
	Points     int16              `json:"points"`
	AnsweredAt pgtype.Timestamptz `json:"answered_at"`
}

type ArenaMatch struct {
	ID              uuid.UUID          `json:"id"`
	Status          string             `json:"status"`
	QuestionIds     []uuid.UUID        `json:"question_ids"`
	QuestionTimeSec int16              `json:"question_time_sec"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	FinishedAt      pgtype.Timestamptz `json:"finished_at"`
	EndReason       pgtype.Text        `json:"end_reason"`
}

type ArenaMatchPlayer struct {
	MatchID         uuid.UUID          `json:"match_id"`
	ProfileID       uuid.UUID          `json:"profile_id"`
	Slot            int16              `json:"slot"`
	Locale          string             `json:"locale"`
	Score           int32              `json:"score"`
	CorrectCount    int16              `json:"correct_count"`
	TotalResponseMs int32              `json:"total_response_ms"`
	Outcome         pgtype.Text        `json:"outcome"`
	RatingBefore    pgtype.Int4        `json:"rating_before"`
	RatingAfter     pgtype.Int4        `json:"rating_after"`
	RatingDelta     pgtype.Int4        `json:"rating_delta"`
	DisconnectedAt  pgtype.Timestamptz `json:"disconnected_at"`
	JoinedAt        pgtype.Timestamptz `json:"joined_at"`
}

type AuditLog struct {
	ID        uuid.UUID          `json:"id"`
	ActorID   uuid.NullUUID      `json:"actor_id"`
	Action    string             `json:"action"`
	Entity    string             `json:"entity"`
	EntityID  uuid.NullUUID      `json:"entity_id"`
	Before    []byte             `json:"before"`
	After     []byte             `json:"after"`
	Ip        *netip.Addr        `json:"ip"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type B2bInvite struct {
	ID         uuid.UUID          `json:"id"`
	Token      string             `json:"token"`
	OrgID      uuid.UUID          `json:"org_id"`
	Phone      string             `json:"phone"`
	Role       string             `json:"role"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedBy  uuid.NullUUID      `json:"created_by"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	AcceptedBy uuid.NullUUID      `json:"accepted_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type B2bOrg struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type B2bOrgLicense struct {
	ID        uuid.UUID          `json:"id"`
	OrgID     uuid.UUID          `json:"org_id"`
	Seats     int32              `json:"seats"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	Note      string             `json:"note"`
	CreatedBy string             `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type B2bOrgMember struct {
	OrgID     uuid.UUID          `json:"org_id"`
	ProfileID uuid.UUID          `json:"profile_id"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID        uuid.UUID          `json:"id"`
	Code      string             `json:"code"`
	SortOrder int32              `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CategoryMastery struct {
	ProfileID  uuid.UUID          `json:"profile_id"`
	CategoryID uuid.UUID          `json:"category_id"`
	Mastery    float32            `json:"mastery"`
	Seen       int32              `json:"seen"`
	Correct    int32              `json:"correct"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type CategoryTranslation struct {
	CategoryID uuid.UUID `json:"category_id"`
	Locale     string    `json:"locale"`
	Name       string    `json:"name"`
	Status     string    `json:"status"`
}

type ClickTransaction struct {
	ID            uuid.UUID          `json:"id"`
	ClickTransID  string             `json:"click_trans_id"`
	ClickPaydocID pgtype.Text        `json:"click_paydoc_id"`
	PaymentID     uuid.UUID          `json:"payment_id"`
	AmountUzs     int64              `json:"amount_uzs"`
	State         int32              `json:"state"`
	Reason        pgtype.Text        `json:"reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ConfirmedAt   pgtype.Timestamptz `json:"confirmed_at"`
	RejectedAt    pgtype.Timestamptz `json:"rejected_at"`
}

type ContentRevision struct {
	ID           uuid.UUID          `json:"id"`
	EntityType   string             `json:"entity_type"`
	EntityID     uuid.UUID          `json:"entity_id"`
	SnapshotJson json.RawMessage    `json:"snapshot_json"`
	EditorID     uuid.NullUUID      `json:"editor_id"`
	Note         string             `json:"note"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Device struct {
	ID          uuid.UUID          `json:"id"`
	ProfileID   uuid.UUID          `json:"profile_id"`
	Fingerprint string             `json:"fingerprint"`
	FirstSeen   pgtype.Timestamptz `json:"first_seen"`
	LastSeen    pgtype.Timestamptz `json:"last_seen"`
}

type Entitlement struct {
	ID        uuid.UUID          `json:"id"`
	ProfileID uuid.UUID          `json:"profile_id"`
	Source    string             `json:"source"`
	StartsAt  pgtype.Timestamptz `json:"starts_at"`
	EndsAt    pgtype.Timestamptz `json:"ends_at"`
	PaymentID uuid.NullUUID      `json:"payment_id"`
	CreatedBy uuid.NullUUID      `json:"created_by"`
	Note      string             `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID        int64              `json:"id"`
	ProfileID uuid.NullUUID      `json:"profile_id"`
	AnonID    pgtype.Text        `json:"anon_id"`
	Name      string             `json:"name"`
	Props     json.RawMessage    `json:"props"`
	Ts        pgtype.Timestamptz `json:"ts"`
}

type EventDefault struct {
	ID        int64              `json:"id"`
	ProfileID uuid.NullUUID      `json:"profile_id"`
	AnonID    pgtype.Text        `json:"anon_id"`
	Name      string             `json:"name"`
	Props     json.RawMessage    `json:"props"`
	Ts        pgtype.Timestamptz `json:"ts"`
}

type ExamSession struct {
	ID            uuid.UUID          `json:"id"`
	ProfileID     uuid.UUID          `json:"profile_id"`
	Mode          string             `json:"mode"`
	VariantID     uuid.NullUUID      `json:"variant_id"`
	CategoryID    uuid.NullUUID      `json:"category_id"`
	SignID        uuid.NullUUID      `json:"sign_id"`
	Locale        string             `json:"locale"`
	TimeLimitSec  pgtype.Int4        `json:"time_limit_sec"`
	ErrorsAllowed pgtype.Int4        `json:"errors_allowed"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
	Status        string             `json:"status"`
	Score         pgtype.Int4        `json:"score"`
	Total         int32              `json:"total"`
	StoppedReason pgtype.Text        `json:"stopped_reason"`
	// Bank-honest readiness_pct captured at FinishSession for exam/grand_mock/placement calibration.
	ReadinessPctAtFinish pgtype.Int4 `json:"readiness_pct_at_finish"`
}

type Explanation struct {
	ID         uuid.UUID          `json:"id"`
	QuestionID uuid.UUID          `json:"question_id"`
	LegalRefs  json.RawMessage    `json:"legal_refs"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type ExplanationFeedback struct {
	ProfileID     uuid.UUID          `json:"profile_id"`
	ExplanationID uuid.UUID          `json:"explanation_id"`
	Helpful       bool               `json:"helpful"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ExplanationTranslation struct {
	ExplanationID uuid.UUID          `json:"explanation_id"`
	Locale        string             `json:"locale"`
	Blocks        json.RawMessage    `json:"blocks"`
	Status        string             `json:"status"`
	VerifiedBy    uuid.NullUUID      `json:"verified_by"`
	VerifiedAt    pgtype.Timestamptz `json:"verified_at"`
	Source        string             `json:"source"`
}

type FeatureFlag struct {
	Key         string             `json:"key"`
	Type        string             `json:"type"`
	ValueJson   json.RawMessage    `json:"value_json"`
	Description string             `json:"description"`
	UpdatedBy   string             `json:"updated_by"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GrandMockCertificate struct {
	ID        uuid.UUID          `json:"id"`
	SessionID uuid.UUID          `json:"session_id"`
	ProfileID uuid.UUID          `json:"profile_id"`
	ShareCode string             `json:"share_code"`
	Score     int32              `json:"score"`
	Total     int32              `json:"total"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Image struct {
	ID         uuid.UUID          `json:"id"`
	StorageKey string             `json:"storage_key"`
	Sha256     string             `json:"sha256"`
	Width      int32              `json:"width"`
	Height     int32              `json:"height"`
	Mime       string             `json:"mime"`
	Source     string             `json:"source"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type LimitConfig struct {
	Key       string             `json:"key"`
	FreeValue int32              `json:"free_value"`
	VipValue  int32              `json:"vip_value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy uuid.NullUUID      `json:"updated_by"`
}

type Notification struct {
	ID        uuid.UUID          `json:"id"`
	ProfileID uuid.UUID          `json:"profile_id"`
	Kind      string             `json:"kind"`
	Payload   json.RawMessage    `json:"payload"`
	Channel   string             `json:"channel"`
	SentAt    pgtype.Timestamptz `json:"sent_at"`
	ReadAt    pgtype.Timestamptz `json:"read_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OtpChallenge struct {
	ID        uuid.UUID          `json:"id"`
	Phone     string             `json:"phone"`
	CodeHash  string             `json:"code_hash"`
	Channel   string             `json:"channel"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Attempts  int16              `json:"attempts"`
	Consumed  bool               `json:"consumed"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PaymeTransaction struct {
	PaymeID     string             `json:"payme_id"`
	PaymentID   uuid.UUID          `json:"payment_id"`
	AmountTiyin int64              `json:"amount_tiyin"`
	State       int32              `json:"state"`
	Reason      pgtype.Int4        `json:"reason"`
	CreateTime  int64              `json:"create_time"`
	PerformTime int64              `json:"perform_time"`
	CancelTime  int64              `json:"cancel_time"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Payment struct {
	ID                     uuid.UUID          `json:"id"`
	ProfileID              uuid.UUID          `json:"profile_id"`
	TariffID               uuid.UUID          `json:"tariff_id"`
	AmountUzs              int64              `json:"amount_uzs"`
	Provider               string             `json:"provider"`
	Status                 string             `json:"status"`
	ProviderTxnID          pgtype.Text        `json:"provider_txn_id"`
	IdempotencyKey         string             `json:"idempotency_key"`
	PromoCodeID            uuid.NullUUID      `json:"promo_code_id"`
	Meta                   json.RawMessage    `json:"meta"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	PaidAt                 pgtype.Timestamptz `json:"paid_at"`
	TariffDaysSnapshot     int32              `json:"tariff_days_snapshot"`
	TariffPriceUzsSnapshot int64              `json:"tariff_price_uzs_snapshot"`
}

type PaymentProviderStatus struct {
	Provider  string             `json:"provider"`
	Enabled   bool               `json:"enabled"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.Text        `json:"updated_by"`
}

type Profile struct {
	ID                        uuid.UUID          `json:"id"`
	Phone                     string             `json:"phone"`
	Name                      string             `json:"name"`
	Region                    string             `json:"region"`
	District                  string             `json:"district"`
	BirthDate                 pgtype.Date        `json:"birth_date"`
	LocalePref                string             `json:"locale_pref"`
	ThemePref                 string             `json:"theme_pref"`
	Role                      string             `json:"role"`
	ReferralCode              pgtype.Text        `json:"referral_code"`
	ReferredBy                uuid.NullUUID      `json:"referred_by"`
	Status                    string             `json:"status"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	PasswordHash              pgtype.Text        `json:"password_hash"`
	ReferralCommissionPercent int32              `json:"referral_commission_percent"`
}

type PromoCode struct {
	ID           uuid.UUID          `json:"id"`
	Code         string             `json:"code"`
	Kind         string             `json:"kind"`
	Value        int32              `json:"value"`
	MaxUses      pgtype.Int4        `json:"max_uses"`
	PerUserLimit int32              `json:"per_user_limit"`
	ValidFrom    pgtype.Timestamptz `json:"valid_from"`
	ValidTo      pgtype.Timestamptz `json:"valid_to"`
	Active       bool               `json:"active"`
	CreatedBy    uuid.NullUUID      `json:"created_by"`
}

type PromoRedemption struct {
	ID          uuid.UUID          `json:"id"`
	PromoCodeID uuid.UUID          `json:"promo_code_id"`
	ProfileID   uuid.UUID          `json:"profile_id"`
	PaymentID   uuid.NullUUID      `json:"payment_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type PushSubscription struct {
	ID        uuid.UUID          `json:"id"`
	ProfileID uuid.UUID          `json:"profile_id"`
	Endpoint  string             `json:"endpoint"`
	P256dh    string             `json:"p256dh"`
	Auth      string             `json:"auth"`
	UserAgent string             `json:"user_agent"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
}

type Question struct {
	ID               uuid.UUID          `json:"id"`
	SourceExtID      string             `json:"source_ext_id"`
	CategoryID       uuid.UUID          `json:"category_id"`
	ImageID          uuid.NullUUID      `json:"image_id"`
	CorrectAnswerID  uuid.NullUUID      `json:"correct_answer_id"`
	ContentHash      string             `json:"content_hash"`
	Source           string             `json:"source"`
	ValidationStatus string             `json:"validation_status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type QuestionMemory struct {
	ProfileID      uuid.UUID          `json:"profile_id"`
	QuestionID     uuid.UUID          `json:"question_id"`
	Stability      float32            `json:"stability"`
	Difficulty     float32            `json:"difficulty"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	LastReviewedAt pgtype.Timestamptz `json:"last_reviewed_at"`
	Reps           int32              `json:"reps"`
	Lapses         int32              `json:"lapses"`
	State          int16              `json:"state"`
}

type QuestionSign struct {
	QuestionID uuid.UUID `json:"question_id"`
	SignID     uuid.UUID `json:"sign_id"`
}

type QuestionTranslation struct {
	QuestionID uuid.UUID `json:"question_id"`
	Locale     string    `json:"locale"`
	Text       string    `json:"text"`
	Status     string    `json:"status"`
	Source     string    `json:"source"`
}

type Referral struct {
	ID           uuid.UUID          `json:"id"`
	ReferrerID   uuid.UUID          `json:"referrer_id"`
	RefereeID    uuid.UUID          `json:"referee_id"`
	ReferralCode string             `json:"referral_code"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	RewardedAt   pgtype.Timestamptz `json:"rewarded_at"`
}

type ReferralLedger struct {
	ID        uuid.UUID          `json:"id"`
	ProfileID uuid.UUID          `json:"profile_id"`
	EntryType string             `json:"entry_type"`
	AmountUzs int64              `json:"amount_uzs"`
	PaymentID uuid.NullUUID      `json:"payment_id"`
	PayoutID  uuid.NullUUID      `json:"payout_id"`
	Meta      json.RawMessage    `json:"meta"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ReferralPayout struct {
	ID          uuid.UUID          `json:"id"`
	ProfileID   uuid.UUID          `json:"profile_id"`
	AmountUzs   int64              `json:"amount_uzs"`
	CardNumber  string             `json:"card_number"`
	CardNetwork string             `json:"card_network"`
	Status      string             `json:"status"`
	AdminNote   string             `json:"admin_note"`
	ProcessedBy uuid.NullUUID      `json:"processed_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	ProfileID uuid.UUID          `json:"profile_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SavedQuestion struct {
	ProfileID  uuid.UUID          `json:"profile_id"`
	QuestionID uuid.UUID          `json:"question_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type SessionAnswer struct {
	SessionID  uuid.UUID          `json:"session_id"`
	QuestionID uuid.UUID          `json:"question_id"`
	AnswerID   uuid.UUID          `json:"answer_id"`
	IsCorrect  bool               `json:"is_correct"`
	Position   int16              `json:"position"`
	AnsweredAt pgtype.Timestamptz `json:"answered_at"`
}

type SessionQuestion struct {
	SessionID  uuid.UUID `json:"session_id"`
	QuestionID uuid.UUID `json:"question_id"`
	Position   int16     `json:"position"`
}

type Sign struct {
	ID        uuid.UUID     `json:"id"`
	GroupID   uuid.UUID     `json:"group_id"`
	Code      string        `json:"code"`
	ImageID   uuid.NullUUID `json:"image_id"`
	SortOrder int32         `json:"sort_order"`
}

type SignGroup struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	SortOrder int32     `json:"sort_order"`
}

type SignGroupTranslation struct {
	SignGroupID uuid.UUID `json:"sign_group_id"`
	Locale      string    `json:"locale"`
	Name        string    `json:"name"`
	Status      string    `json:"status"`
}

type SignTranslation struct {
	SignID      uuid.UUID `json:"sign_id"`
	Locale      string    `json:"locale"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Status      string    `json:"status"`
}

type SiteSetting struct {
	Key       string             `json:"key"`
	ValueJson json.RawMessage    `json:"value_json"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy pgtype.Text        `json:"updated_by"`
}

type Streak struct {
	ProfileID      uuid.UUID   `json:"profile_id"`
	Current        int32       `json:"current"`
	Best           int32       `json:"best"`
	LastActiveDate pgtype.Date `json:"last_active_date"`
	DailyGoal      int32       `json:"daily_goal"`
	TodayDone      int32       `json:"today_done"`
}

type SupportTicket struct {
	ID           uuid.UUID          `json:"id"`
	ProfileID    uuid.NullUUID      `json:"profile_id"`
	ContactEmail string             `json:"contact_email"`
	ContactPhone string             `json:"contact_phone"`
	Subject      string             `json:"subject"`
	Body         string             `json:"body"`
	Status       string             `json:"status"`
	Locale       string             `json:"locale"`
	Source       string             `json:"source"`
	AdminNote    string             `json:"admin_note"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Tariff struct {
	ID          uuid.UUID   `json:"id"`
	Code        string      `json:"code"`
	Days        int32       `json:"days"`
	PriceUzs    int64       `json:"price_uzs"`
	OldPriceUzs pgtype.Int8 `json:"old_price_uzs"`
	Badge       pgtype.Text `json:"badge"`
	SortOrder   int32       `json:"sort_order"`
	Active      bool        `json:"active"`
}

type TariffTranslation struct {
	TariffID    uuid.UUID `json:"tariff_id"`
	Locale      string    `json:"locale"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

type TelegramAccount struct {
	ProfileID uuid.UUID          `json:"profile_id"`
	TgUserID  int64              `json:"tg_user_id"`
	Username  string             `json:"username"`
	LinkedAt  pgtype.Timestamptz `json:"linked_at"`
}

type TelegramChat struct {
	ChatID    int64              `json:"chat_id"`
	Title     string             `json:"title"`
	ChatType  string             `json:"chat_type"`
	BotStatus string             `json:"bot_status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TelegramLinkToken struct {
	ID        uuid.UUID          `json:"id"`
	ProfileID uuid.UUID          `json:"profile_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type TelegramQuizSession struct {
	ID                uuid.UUID          `json:"id"`
	ChatID            int64              `json:"chat_id"`
	StartedByTgUserID int64              `json:"started_by_tg_user_id"`
	Active            bool               `json:"active"`
	QuestionID        uuid.NullUUID      `json:"question_id"`
	AwaitingAnswer    bool               `json:"awaiting_answer"`
	AnswerMessageID   int64              `json:"answer_message_id"`
	AskedCount        int32              `json:"asked_count"`
	CorrectCount      int32              `json:"correct_count"`
	LastActivityAt    pgtype.Timestamptz `json:"last_activity_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type UserReferralCode struct {
	UserID    uuid.UUID          `json:"user_id"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Variant struct {
	ID        uuid.UUID `json:"id"`
	Number    int32     `json:"number"`
	SortOrder int32     `json:"sort_order"`
}

type VariantProgress struct {
	ProfileID   uuid.UUID          `json:"profile_id"`
	VariantID   uuid.UUID          `json:"variant_id"`
	BestCorrect int32              `json:"best_correct"`
	Attempts    int32              `json:"attempts"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type VariantQuestion struct {
	VariantID  uuid.UUID `json:"variant_id"`
	QuestionID uuid.UUID `json:"question_id"`
	Position   int16     `json:"position"`
}
