// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPasswordReset = `-- name: CancelPasswordReset :exec
UPDATE password_reset_token
SET used_at = now(),
    pending_tg_user_id = NULL,
    confirm_nonce_hash = NULL
WHERE id = $1 AND used_at IS NULL
`

// «Yo'q» in the bot: the reset is spent, so the website tab sees "invalid"
// and CompletePasswordReset refuses it.
func (q *Queries) CancelPasswordReset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelPasswordReset, id)
	return err
}

const clearAllPasswordResetPendingForTg = `-- name: ClearAllPasswordResetPendingForTg :exec
UPDATE password_reset_token
SET pending_tg_user_id = NULL,
    confirm_nonce_hash = NULL
WHERE pending_tg_user_id = $1 AND used_at IS NULL
`

func (q *Queries) ClearAllPasswordResetPendingForTg(ctx context.Context, pendingTgUserID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, clearAllPasswordResetPendingForTg, pendingTgUserID)
	return err
}

const clearPasswordResetPendingForTg = `-- name: ClearPasswordResetPendingForTg :exec
UPDATE password_reset_token
SET pending_tg_user_id = NULL,
    confirm_nonce_hash = NULL
WHERE pending_tg_user_id = $1 AND used_at IS NULL AND id <> $2
`

type ClearPasswordResetPendingForTgParams struct {
	PendingTgUserID pgtype.Int8 `json:"pending_tg_user_id"`
	ID              uuid.UUID   `json:"id"`
}

func (q *Queries) ClearPasswordResetPendingForTg(ctx context.Context, arg ClearPasswordResetPendingForTgParams) error {
	_, err := q.db.Exec(ctx, clearPasswordResetPendingForTg, arg.PendingTgUserID, arg.ID)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_token (profile_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, expires_at
`

type CreatePasswordResetTokenParams struct {
	ProfileID uuid.UUID          `json:"profile_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreatePasswordResetTokenRow struct {
	ID        uuid.UUID          `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (CreatePasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.ProfileID, arg.TokenHash, arg.ExpiresAt)
	var i CreatePasswordResetTokenRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const deleteUnusedPasswordResetTokensForProfile = `-- name: DeleteUnusedPasswordResetTokensForProfile :exec
DELETE FROM password_reset_token
WHERE profile_id = $1 AND used_at IS NULL
`

func (q *Queries) DeleteUnusedPasswordResetTokensForProfile(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnusedPasswordResetTokensForProfile, profileID)
	return err
}

const getLivePasswordResetByPendingTgForUpdate = `-- name: GetLivePasswordResetByPendingTgForUpdate :one
SELECT id, profile_id, token_hash, expires_at, used_at, verified_at, pending_tg_user_id, created_at, confirm_nonce_hash, verified_tg_user_id
FROM password_reset_token
WHERE pending_tg_user_id = $1 AND used_at IS NULL
ORDER BY created_at DESC
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetLivePasswordResetByPendingTgForUpdate(ctx context.Context, pendingTgUserID pgtype.Int8) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getLivePasswordResetByPendingTgForUpdate, pendingTgUserID)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.VerifiedAt,
		&i.PendingTgUserID,
		&i.CreatedAt,
		&i.ConfirmNonceHash,
		&i.VerifiedTgUserID,
	)
	return i, err
}

const getPasswordResetByConfirmNonceForUpdate = `-- name: GetPasswordResetByConfirmNonceForUpdate :one
SELECT id, profile_id, token_hash, expires_at, used_at, verified_at, pending_tg_user_id, created_at, confirm_nonce_hash, verified_tg_user_id
FROM password_reset_token
WHERE confirm_nonce_hash = $1
FOR UPDATE
`

func (q *Queries) GetPasswordResetByConfirmNonceForUpdate(ctx context.Context, confirmNonceHash pgtype.Text) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByConfirmNonceForUpdate, confirmNonceHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.VerifiedAt,
		&i.PendingTgUserID,
		&i.CreatedAt,
		&i.ConfirmNonceHash,
		&i.VerifiedTgUserID,
	)
	return i, err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, profile_id, token_hash, expires_at, used_at, verified_at, pending_tg_user_id, created_at, confirm_nonce_hash, verified_tg_user_id
FROM password_reset_token
WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.VerifiedAt,
		&i.PendingTgUserID,
		&i.CreatedAt,
		&i.ConfirmNonceHash,
		&i.VerifiedTgUserID,
	)
	return i, err
}

const getPasswordResetTokenByHashForUpdate = `-- name: GetPasswordResetTokenByHashForUpdate :one
SELECT id, profile_id, token_hash, expires_at, used_at, verified_at, pending_tg_user_id, created_at, confirm_nonce_hash, verified_tg_user_id
FROM password_reset_token
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) GetPasswordResetTokenByHashForUpdate(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHashForUpdate, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.VerifiedAt,
		&i.PendingTgUserID,
		&i.CreatedAt,
		&i.ConfirmNonceHash,
		&i.VerifiedTgUserID,
	)
	return i, err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_reset_token
SET used_at = now(),
    pending_tg_user_id = NULL,
    confirm_nonce_hash = NULL
WHERE id = $1
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetUsed, id)
	return err
}

const markPasswordResetVerified = `-- name: MarkPasswordResetVerified :exec
UPDATE password_reset_token
SET verified_at = now(),
    verified_tg_user_id = pending_tg_user_id,
    pending_tg_user_id = NULL,
    confirm_nonce_hash = NULL
WHERE id = $1 AND used_at IS NULL
`

// The right-hand side reads the pre-update row, so the confirming Telegram
// user moves from pending_tg_user_id (whose unique index must free up) into
// verified_tg_user_id for CompletePasswordReset.
func (q *Queries) MarkPasswordResetVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetVerified, id)
	return err
}

const setPasswordResetConfirmNonce = `-- name: SetPasswordResetConfirmNonce :exec
UPDATE password_reset_token
SET confirm_nonce_hash = $2
WHERE id = $1 AND used_at IS NULL AND verified_at IS NULL
`

type SetPasswordResetConfirmNonceParams struct {
	ID               uuid.UUID   `json:"id"`
	ConfirmNonceHash pgtype.Text `json:"confirm_nonce_hash"`
}

func (q *Queries) SetPasswordResetConfirmNonce(ctx context.Context, arg SetPasswordResetConfirmNonceParams) error {
	_, err := q.db.Exec(ctx, setPasswordResetConfirmNonce, arg.ID, arg.ConfirmNonceHash)
	return err
}

const setPasswordResetPendingTg = `-- name: SetPasswordResetPendingTg :exec
UPDATE password_reset_token
SET pending_tg_user_id = $2,
    confirm_nonce_hash = NULL
WHERE id = $1 AND used_at IS NULL
`

type SetPasswordResetPendingTgParams struct {
	ID              uuid.UUID   `json:"id"`
	PendingTgUserID pgtype.Int8 `json:"pending_tg_user_id"`
}

// A new /start re-arms the reset for this Telegram user: any confirm question
// asked before it is void.
func (q *Queries) SetPasswordResetPendingTg(ctx context.Context, arg SetPasswordResetPendingTgParams) error {
	_, err := q.db.Exec(ctx, setPasswordResetPendingTg, arg.ID, arg.PendingTgUserID)
	return err
}
