// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearPasswordResetPendingForTg = `-- name: ClearPasswordResetPendingForTg :exec
UPDATE password_reset_token
SET pending_tg_user_id = NULL
WHERE pending_tg_user_id = $1 AND used_at IS NULL AND id <> $2
`

type ClearPasswordResetPendingForTgParams struct {
	PendingTgUserID pgtype.Int8 `json:"pending_tg_user_id"`
	ID              uuid.UUID   `json:"id"`
}

func (q *Queries) ClearPasswordResetPendingForTg(ctx context.Context, arg ClearPasswordResetPendingForTgParams) error {
	_, err := q.db.Exec(ctx, clearPasswordResetPendingForTg, arg.PendingTgUserID, arg.ID)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one
INSERT INTO password_reset_token (profile_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, expires_at
`

type CreatePasswordResetTokenParams struct {
	ProfileID uuid.UUID          `json:"profile_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreatePasswordResetTokenRow struct {
	ID        uuid.UUID          `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (CreatePasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.ProfileID, arg.TokenHash, arg.ExpiresAt)
	var i CreatePasswordResetTokenRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const deleteUnusedPasswordResetTokensForProfile = `-- name: DeleteUnusedPasswordResetTokensForProfile :exec
DELETE FROM password_reset_token
WHERE profile_id = $1 AND used_at IS NULL
`

func (q *Queries) DeleteUnusedPasswordResetTokensForProfile(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnusedPasswordResetTokensForProfile, profileID)
	return err
}

const getLivePasswordResetByPendingTgForUpdate = `-- name: GetLivePasswordResetByPendingTgForUpdate :one
SELECT id, profile_id, token_hash, expires_at, used_at, verified_at, pending_tg_user_id, created_at
FROM password_reset_token
WHERE pending_tg_user_id = $1 AND used_at IS NULL
ORDER BY created_at DESC
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetLivePasswordResetByPendingTgForUpdate(ctx context.Context, pendingTgUserID pgtype.Int8) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getLivePasswordResetByPendingTgForUpdate, pendingTgUserID)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.VerifiedAt,
		&i.PendingTgUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetTokenByHash = `-- name: GetPasswordResetTokenByHash :one
SELECT id, profile_id, token_hash, expires_at, used_at, verified_at, pending_tg_user_id, created_at
FROM password_reset_token
WHERE token_hash = $1
`

func (q *Queries) GetPasswordResetTokenByHash(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHash, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.VerifiedAt,
		&i.PendingTgUserID,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetTokenByHashForUpdate = `-- name: GetPasswordResetTokenByHashForUpdate :one
SELECT id, profile_id, token_hash, expires_at, used_at, verified_at, pending_tg_user_id, created_at
FROM password_reset_token
WHERE token_hash = $1
FOR UPDATE
`

func (q *Queries) GetPasswordResetTokenByHashForUpdate(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetTokenByHashForUpdate, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.VerifiedAt,
		&i.PendingTgUserID,
		&i.CreatedAt,
	)
	return i, err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_reset_token
SET used_at = now(),
    pending_tg_user_id = NULL
WHERE id = $1
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetUsed, id)
	return err
}

const markPasswordResetVerified = `-- name: MarkPasswordResetVerified :exec
UPDATE password_reset_token
SET verified_at = now(),
    pending_tg_user_id = NULL
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) MarkPasswordResetVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetVerified, id)
	return err
}

const setPasswordResetPendingTg = `-- name: SetPasswordResetPendingTg :exec
UPDATE password_reset_token
SET pending_tg_user_id = $2
WHERE id = $1 AND used_at IS NULL
`

type SetPasswordResetPendingTgParams struct {
	ID              uuid.UUID   `json:"id"`
	PendingTgUserID pgtype.Int8 `json:"pending_tg_user_id"`
}

func (q *Queries) SetPasswordResetPendingTg(ctx context.Context, arg SetPasswordResetPendingTgParams) error {
	_, err := q.db.Exec(ctx, setPasswordResetPendingTg, arg.ID, arg.PendingTgUserID)
	return err
}
