// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getStreak = `-- name: GetStreak :one
SELECT profile_id, current, best, last_active_date, daily_goal, today_done FROM streak WHERE profile_id = $1
`

func (q *Queries) GetStreak(ctx context.Context, profileID uuid.UUID) (Streak, error) {
	row := q.db.QueryRow(ctx, getStreak, profileID)
	var i Streak
	err := row.Scan(
		&i.ProfileID,
		&i.Current,
		&i.Best,
		&i.LastActiveDate,
		&i.DailyGoal,
		&i.TodayDone,
	)
	return i, err
}

const listSavedQuestions = `-- name: ListSavedQuestions :many
SELECT sq.question_id, sq.created_at
FROM saved_question sq
JOIN question q ON q.id = sq.question_id AND q.validation_status = 'valid'
WHERE sq.profile_id = $1
ORDER BY sq.created_at DESC
`

type ListSavedQuestionsRow struct {
	QuestionID uuid.UUID          `json:"question_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSavedQuestions(ctx context.Context, profileID uuid.UUID) ([]ListSavedQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listSavedQuestions, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSavedQuestionsRow
	for rows.Next() {
		var i ListSavedQuestionsRow
		if err := rows.Scan(&i.QuestionID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveQuestion = `-- name: SaveQuestion :exec
INSERT INTO saved_question (profile_id, question_id)
VALUES ($1, $2)
ON CONFLICT (profile_id, question_id) DO NOTHING
`

type SaveQuestionParams struct {
	ProfileID  uuid.UUID `json:"profile_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) SaveQuestion(ctx context.Context, arg SaveQuestionParams) error {
	_, err := q.db.Exec(ctx, saveQuestion, arg.ProfileID, arg.QuestionID)
	return err
}

const unsaveQuestion = `-- name: UnsaveQuestion :exec
DELETE FROM saved_question WHERE profile_id = $1 AND question_id = $2
`

type UnsaveQuestionParams struct {
	ProfileID  uuid.UUID `json:"profile_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) UnsaveQuestion(ctx context.Context, arg UnsaveQuestionParams) error {
	_, err := q.db.Exec(ctx, unsaveQuestion, arg.ProfileID, arg.QuestionID)
	return err
}

const upsertStreak = `-- name: UpsertStreak :one
INSERT INTO streak (profile_id, current, best, last_active_date, daily_goal, today_done)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (profile_id) DO UPDATE SET
  current = EXCLUDED.current,
  best = EXCLUDED.best,
  last_active_date = EXCLUDED.last_active_date,
  daily_goal = EXCLUDED.daily_goal,
  today_done = EXCLUDED.today_done
RETURNING profile_id, current, best, last_active_date, daily_goal, today_done
`

type UpsertStreakParams struct {
	ProfileID      uuid.UUID   `json:"profile_id"`
	Current        int32       `json:"current"`
	Best           int32       `json:"best"`
	LastActiveDate pgtype.Date `json:"last_active_date"`
	DailyGoal      int32       `json:"daily_goal"`
	TodayDone      int32       `json:"today_done"`
}

func (q *Queries) UpsertStreak(ctx context.Context, arg UpsertStreakParams) (Streak, error) {
	row := q.db.QueryRow(ctx, upsertStreak,
		arg.ProfileID,
		arg.Current,
		arg.Best,
		arg.LastActiveDate,
		arg.DailyGoal,
		arg.TodayDone,
	)
	var i Streak
	err := row.Scan(
		&i.ProfileID,
		&i.Current,
		&i.Best,
		&i.LastActiveDate,
		&i.DailyGoal,
		&i.TodayDone,
	)
	return i, err
}
