// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countPushSubscriptions = `-- name: CountPushSubscriptions :one
SELECT count(*)::int AS count
FROM push_subscription
WHERE profile_id = $1
`

func (q *Queries) CountPushSubscriptions(ctx context.Context, profileID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPushSubscriptions, profileID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const deletePushSubscription = `-- name: DeletePushSubscription :execrows
DELETE FROM push_subscription
WHERE profile_id = $1 AND endpoint = $2
`

type DeletePushSubscriptionParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Endpoint  string    `json:"endpoint"`
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushSubscription, arg.ProfileID, arg.Endpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePushSubscriptionByEndpoint = `-- name: DeletePushSubscriptionByEndpoint :execrows
DELETE FROM push_subscription
WHERE endpoint = $1
`

func (q *Queries) DeletePushSubscriptionByEndpoint(ctx context.Context, endpoint string) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushSubscriptionByEndpoint, endpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertNotification = `-- name: InsertNotification :one
INSERT INTO notification (profile_id, kind, payload, channel)
VALUES ($1, $2, $3, $4)
RETURNING id, profile_id, kind, payload, channel, sent_at, read_at, created_at, campaign_id
`

type InsertNotificationParams struct {
	ProfileID uuid.UUID       `json:"profile_id"`
	Kind      string          `json:"kind"`
	Payload   json.RawMessage `json:"payload"`
	Channel   string          `json:"channel"`
}

func (q *Queries) InsertNotification(ctx context.Context, arg InsertNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, insertNotification,
		arg.ProfileID,
		arg.Kind,
		arg.Payload,
		arg.Channel,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Kind,
		&i.Payload,
		&i.Channel,
		&i.SentAt,
		&i.ReadAt,
		&i.CreatedAt,
		&i.CampaignID,
	)
	return i, err
}

const listPushSubscriptions = `-- name: ListPushSubscriptions :many
SELECT id, profile_id, endpoint, p256dh, auth, user_agent, created_at, last_seen
FROM push_subscription
WHERE profile_id = $1
ORDER BY last_seen DESC
`

func (q *Queries) ListPushSubscriptions(ctx context.Context, profileID uuid.UUID) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, listPushSubscriptions, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationSent = `-- name: MarkNotificationSent :exec
UPDATE notification
SET sent_at = now()
WHERE id = $1
`

func (q *Queries) MarkNotificationSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markNotificationSent, id)
	return err
}

const upsertPushSubscription = `-- name: UpsertPushSubscription :one
INSERT INTO push_subscription (profile_id, endpoint, p256dh, auth, user_agent)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (endpoint) DO UPDATE SET
  profile_id = EXCLUDED.profile_id,
  p256dh = EXCLUDED.p256dh,
  auth = EXCLUDED.auth,
  user_agent = EXCLUDED.user_agent,
  last_seen = now()
RETURNING id, profile_id, endpoint, p256dh, auth, user_agent, created_at, last_seen
`

type UpsertPushSubscriptionParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Endpoint  string    `json:"endpoint"`
	P256dh    string    `json:"p256dh"`
	Auth      string    `json:"auth"`
	UserAgent string    `json:"user_agent"`
}

func (q *Queries) UpsertPushSubscription(ctx context.Context, arg UpsertPushSubscriptionParams) (PushSubscription, error) {
	row := q.db.QueryRow(ctx, upsertPushSubscription,
		arg.ProfileID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
		arg.UserAgent,
	)
	var i PushSubscription
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Endpoint,
		&i.P256dh,
		&i.Auth,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}
