// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: referral.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const claimPendingReferralForReferee = `-- name: ClaimPendingReferralForReferee :one
UPDATE referral
SET status = 'rewarded', rewarded_at = NOW()
WHERE referee_id = $1 AND status = 'pending'
RETURNING id, referrer_id, referee_id, referral_code, status, created_at, rewarded_at
`

// Atomically claims (marks rewarded) the referee's pending referral in one
// statement. The UPDATE takes a row lock as part of the write: under READ
// COMMITTED, a concurrent claim for the same referee blocks until the first
// commits, then re-evaluates WHERE status = 'pending' against the now-
// committed row and returns zero rows (pgx.ErrNoRows) since it was already
// claimed. This makes claim-then-grant safe without a separate SELECT FOR
// UPDATE round trip.
func (q *Queries) ClaimPendingReferralForReferee(ctx context.Context, refereeID uuid.UUID) (Referral, error) {
	row := q.db.QueryRow(ctx, claimPendingReferralForReferee, refereeID)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.RefereeID,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.RewardedAt,
	)
	return i, err
}

const createReferral = `-- name: CreateReferral :one
INSERT INTO referral (referrer_id, referee_id, referral_code, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, referrer_id, referee_id, referral_code, status, created_at, rewarded_at
`

type CreateReferralParams struct {
	ReferrerID   uuid.UUID `json:"referrer_id"`
	RefereeID    uuid.UUID `json:"referee_id"`
	ReferralCode string    `json:"referral_code"`
}

func (q *Queries) CreateReferral(ctx context.Context, arg CreateReferralParams) (Referral, error) {
	row := q.db.QueryRow(ctx, createReferral, arg.ReferrerID, arg.RefereeID, arg.ReferralCode)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.RefereeID,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.RewardedAt,
	)
	return i, err
}

const createUserReferralCode = `-- name: CreateUserReferralCode :one
INSERT INTO user_referral_code (user_id, code)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING user_id, code, created_at
`

type CreateUserReferralCodeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Code   string    `json:"code"`
}

func (q *Queries) CreateUserReferralCode(ctx context.Context, arg CreateUserReferralCodeParams) (UserReferralCode, error) {
	row := q.db.QueryRow(ctx, createUserReferralCode, arg.UserID, arg.Code)
	var i UserReferralCode
	err := row.Scan(&i.UserID, &i.Code, &i.CreatedAt)
	return i, err
}

const getReferralCodeOwner = `-- name: GetReferralCodeOwner :one
SELECT user_id, code, created_at
FROM user_referral_code
WHERE LOWER(code) = LOWER($1)
`

func (q *Queries) GetReferralCodeOwner(ctx context.Context, lower string) (UserReferralCode, error) {
	row := q.db.QueryRow(ctx, getReferralCodeOwner, lower)
	var i UserReferralCode
	err := row.Scan(&i.UserID, &i.Code, &i.CreatedAt)
	return i, err
}

const getReferralStatsForUser = `-- name: GetReferralStatsForUser :one
SELECT 
    COUNT(*)::bigint AS total_invited,
    COUNT(CASE WHEN status = 'rewarded' THEN 1 END)::bigint AS total_rewarded
FROM referral
WHERE referrer_id = $1
`

type GetReferralStatsForUserRow struct {
	TotalInvited  int64 `json:"total_invited"`
	TotalRewarded int64 `json:"total_rewarded"`
}

func (q *Queries) GetReferralStatsForUser(ctx context.Context, referrerID uuid.UUID) (GetReferralStatsForUserRow, error) {
	row := q.db.QueryRow(ctx, getReferralStatsForUser, referrerID)
	var i GetReferralStatsForUserRow
	err := row.Scan(&i.TotalInvited, &i.TotalRewarded)
	return i, err
}

const getUserReferralCode = `-- name: GetUserReferralCode :one
SELECT user_id, code, created_at
FROM user_referral_code
WHERE user_id = $1
`

func (q *Queries) GetUserReferralCode(ctx context.Context, userID uuid.UUID) (UserReferralCode, error) {
	row := q.db.QueryRow(ctx, getUserReferralCode, userID)
	var i UserReferralCode
	err := row.Scan(&i.UserID, &i.Code, &i.CreatedAt)
	return i, err
}
