// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: referral_wallet.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countReferralPayouts = `-- name: CountReferralPayouts :one
SELECT COUNT(*)::bigint
FROM referral_payout
WHERE ($1::text = '' OR status = $1)
`

func (q *Queries) CountReferralPayouts(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countReferralPayouts, dollar_1)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createReferralPayout = `-- name: CreateReferralPayout :one
INSERT INTO referral_payout (profile_id, amount_uzs, card_number, card_network)
VALUES ($1, $2, $3, $4)
RETURNING id, profile_id, amount_uzs, card_number, card_network, status, admin_note, processed_by, created_at, processed_at
`

type CreateReferralPayoutParams struct {
	ProfileID   uuid.UUID `json:"profile_id"`
	AmountUzs   int64     `json:"amount_uzs"`
	CardNumber  string    `json:"card_number"`
	CardNetwork string    `json:"card_network"`
}

func (q *Queries) CreateReferralPayout(ctx context.Context, arg CreateReferralPayoutParams) (ReferralPayout, error) {
	row := q.db.QueryRow(ctx, createReferralPayout,
		arg.ProfileID,
		arg.AmountUzs,
		arg.CardNumber,
		arg.CardNetwork,
	)
	var i ReferralPayout
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.AmountUzs,
		&i.CardNumber,
		&i.CardNetwork,
		&i.Status,
		&i.AdminNote,
		&i.ProcessedBy,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getAdminReferralUserStats = `-- name: GetAdminReferralUserStats :one
SELECT
  (SELECT COUNT(*)::bigint FROM referral r WHERE r.referrer_id = pr.id) AS total_invited,
  (SELECT COUNT(*)::bigint FROM referral r WHERE r.referrer_id = pr.id AND r.status = 'rewarded') AS total_rewarded,
  (SELECT COALESCE(SUM(l.amount_uzs), 0)::bigint FROM referral_ledger l WHERE l.profile_id = pr.id AND l.entry_type = 'commission') AS earned_uzs,
  (SELECT COALESCE(SUM(l.amount_uzs), 0)::bigint FROM referral_ledger l WHERE l.profile_id = pr.id) AS balance_uzs,
  pr.referral_commission_percent AS commission_percent
FROM profile pr
WHERE pr.id = $1
`

type GetAdminReferralUserStatsRow struct {
	TotalInvited      int64 `json:"total_invited"`
	TotalRewarded     int64 `json:"total_rewarded"`
	EarnedUzs         int64 `json:"earned_uzs"`
	BalanceUzs        int64 `json:"balance_uzs"`
	CommissionPercent int32 `json:"commission_percent"`
}

func (q *Queries) GetAdminReferralUserStats(ctx context.Context, id uuid.UUID) (GetAdminReferralUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getAdminReferralUserStats, id)
	var i GetAdminReferralUserStatsRow
	err := row.Scan(
		&i.TotalInvited,
		&i.TotalRewarded,
		&i.EarnedUzs,
		&i.BalanceUzs,
		&i.CommissionPercent,
	)
	return i, err
}

const getClawbackByPaymentID = `-- name: GetClawbackByPaymentID :one
SELECT id, profile_id, entry_type, amount_uzs, payment_id, payout_id, meta, created_at
FROM referral_ledger
WHERE payment_id = $1 AND entry_type = 'clawback'
`

func (q *Queries) GetClawbackByPaymentID(ctx context.Context, paymentID uuid.NullUUID) (ReferralLedger, error) {
	row := q.db.QueryRow(ctx, getClawbackByPaymentID, paymentID)
	var i ReferralLedger
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.EntryType,
		&i.AmountUzs,
		&i.PaymentID,
		&i.PayoutID,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const getCommissionByPaymentID = `-- name: GetCommissionByPaymentID :one
SELECT id, profile_id, entry_type, amount_uzs, payment_id, payout_id, meta, created_at
FROM referral_ledger
WHERE payment_id = $1 AND entry_type = 'commission'
`

func (q *Queries) GetCommissionByPaymentID(ctx context.Context, paymentID uuid.NullUUID) (ReferralLedger, error) {
	row := q.db.QueryRow(ctx, getCommissionByPaymentID, paymentID)
	var i ReferralLedger
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.EntryType,
		&i.AmountUzs,
		&i.PaymentID,
		&i.PayoutID,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const getReferralBalance = `-- name: GetReferralBalance :one
SELECT COALESCE(SUM(amount_uzs), 0)::bigint AS balance_uzs
FROM referral_ledger
WHERE profile_id = $1
`

func (q *Queries) GetReferralBalance(ctx context.Context, profileID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getReferralBalance, profileID)
	var balance_uzs int64
	err := row.Scan(&balance_uzs)
	return balance_uzs, err
}

const getReferralCommissionPercent = `-- name: GetReferralCommissionPercent :one
SELECT referral_commission_percent FROM profile WHERE id = $1
`

func (q *Queries) GetReferralCommissionPercent(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getReferralCommissionPercent, id)
	var referral_commission_percent int32
	err := row.Scan(&referral_commission_percent)
	return referral_commission_percent, err
}

const getReferralEarnedCommission = `-- name: GetReferralEarnedCommission :one
SELECT COALESCE(SUM(amount_uzs), 0)::bigint AS earned_uzs
FROM referral_ledger
WHERE profile_id = $1 AND entry_type = 'commission'
`

func (q *Queries) GetReferralEarnedCommission(ctx context.Context, profileID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getReferralEarnedCommission, profileID)
	var earned_uzs int64
	err := row.Scan(&earned_uzs)
	return earned_uzs, err
}

const getReferralPayoutForUpdate = `-- name: GetReferralPayoutForUpdate :one
SELECT id, profile_id, amount_uzs, card_number, card_network, status, admin_note, processed_by, created_at, processed_at
FROM referral_payout
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetReferralPayoutForUpdate(ctx context.Context, id uuid.UUID) (ReferralPayout, error) {
	row := q.db.QueryRow(ctx, getReferralPayoutForUpdate, id)
	var i ReferralPayout
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.AmountUzs,
		&i.CardNumber,
		&i.CardNetwork,
		&i.Status,
		&i.AdminNote,
		&i.ProcessedBy,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const getReferralPayoutSummaryForProfile = `-- name: GetReferralPayoutSummaryForProfile :one
SELECT
  COUNT(*) FILTER (WHERE status = 'pending')::bigint AS pending_count,
  COALESCE(SUM(amount_uzs) FILTER (WHERE status = 'pending'), 0)::bigint AS pending_uzs,
  COUNT(*) FILTER (WHERE status = 'paid')::bigint AS paid_count,
  COALESCE(SUM(amount_uzs) FILTER (WHERE status = 'paid'), 0)::bigint AS paid_uzs,
  COUNT(*) FILTER (WHERE status = 'rejected')::bigint AS rejected_count,
  COALESCE(SUM(amount_uzs) FILTER (WHERE status = 'rejected'), 0)::bigint AS rejected_uzs
FROM referral_payout
WHERE profile_id = $1
`

type GetReferralPayoutSummaryForProfileRow struct {
	PendingCount  int64 `json:"pending_count"`
	PendingUzs    int64 `json:"pending_uzs"`
	PaidCount     int64 `json:"paid_count"`
	PaidUzs       int64 `json:"paid_uzs"`
	RejectedCount int64 `json:"rejected_count"`
	RejectedUzs   int64 `json:"rejected_uzs"`
}

func (q *Queries) GetReferralPayoutSummaryForProfile(ctx context.Context, profileID uuid.UUID) (GetReferralPayoutSummaryForProfileRow, error) {
	row := q.db.QueryRow(ctx, getReferralPayoutSummaryForProfile, profileID)
	var i GetReferralPayoutSummaryForProfileRow
	err := row.Scan(
		&i.PendingCount,
		&i.PendingUzs,
		&i.PaidCount,
		&i.PaidUzs,
		&i.RejectedCount,
		&i.RejectedUzs,
	)
	return i, err
}

const insertReferralLedger = `-- name: InsertReferralLedger :one
INSERT INTO referral_ledger (profile_id, entry_type, amount_uzs, payment_id, payout_id, meta)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, profile_id, entry_type, amount_uzs, payment_id, payout_id, meta, created_at
`

type InsertReferralLedgerParams struct {
	ProfileID uuid.UUID       `json:"profile_id"`
	EntryType string          `json:"entry_type"`
	AmountUzs int64           `json:"amount_uzs"`
	PaymentID uuid.NullUUID   `json:"payment_id"`
	PayoutID  uuid.NullUUID   `json:"payout_id"`
	Meta      json.RawMessage `json:"meta"`
}

func (q *Queries) InsertReferralLedger(ctx context.Context, arg InsertReferralLedgerParams) (ReferralLedger, error) {
	row := q.db.QueryRow(ctx, insertReferralLedger,
		arg.ProfileID,
		arg.EntryType,
		arg.AmountUzs,
		arg.PaymentID,
		arg.PayoutID,
		arg.Meta,
	)
	var i ReferralLedger
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.EntryType,
		&i.AmountUzs,
		&i.PaymentID,
		&i.PayoutID,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const listRefereesForReferrer = `-- name: ListRefereesForReferrer :many
SELECT r.id, r.referee_id, r.referral_code, r.status, r.created_at, r.rewarded_at,
       p.phone AS referee_phone, p.name AS referee_name,
       COALESCE((
         SELECT SUM(l.amount_uzs)
         FROM referral_ledger l
         WHERE l.profile_id = r.referrer_id
           AND l.entry_type = 'commission'
           AND (l.meta->>'referee_id') = r.referee_id::text
       ), 0)::bigint AS commission_uzs
FROM referral r
JOIN profile p ON p.id = r.referee_id
WHERE r.referrer_id = $1
ORDER BY r.created_at DESC
LIMIT $2
`

type ListRefereesForReferrerParams struct {
	ReferrerID uuid.UUID `json:"referrer_id"`
	Limit      int32     `json:"limit"`
}

type ListRefereesForReferrerRow struct {
	ID            uuid.UUID          `json:"id"`
	RefereeID     uuid.UUID          `json:"referee_id"`
	ReferralCode  string             `json:"referral_code"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	RewardedAt    pgtype.Timestamptz `json:"rewarded_at"`
	RefereePhone  string             `json:"referee_phone"`
	RefereeName   string             `json:"referee_name"`
	CommissionUzs int64              `json:"commission_uzs"`
}

func (q *Queries) ListRefereesForReferrer(ctx context.Context, arg ListRefereesForReferrerParams) ([]ListRefereesForReferrerRow, error) {
	rows, err := q.db.Query(ctx, listRefereesForReferrer, arg.ReferrerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRefereesForReferrerRow
	for rows.Next() {
		var i ListRefereesForReferrerRow
		if err := rows.Scan(
			&i.ID,
			&i.RefereeID,
			&i.ReferralCode,
			&i.Status,
			&i.CreatedAt,
			&i.RewardedAt,
			&i.RefereePhone,
			&i.RefereeName,
			&i.CommissionUzs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferralEarningsDetail = `-- name: ListReferralEarningsDetail :many
SELECT
  l.id AS ledger_id,
  l.amount_uzs AS commission_uzs,
  l.created_at AS rewarded_at,
  l.payment_id,
  COALESCE(pay.amount_uzs, 0)::bigint AS payment_amount_uzs,
  COALESCE(pay.tariff_days_snapshot, 0)::int AS tariff_days,
  COALESCE(t.code, '') AS tariff_code,
  COALESCE(ref.name, '') AS referee_name,
  COALESCE(ref.phone, '') AS referee_phone,
  COALESCE((l.meta->>'percent')::int, 0)::int AS percent_snapshot
FROM referral_ledger l
LEFT JOIN payment pay ON pay.id = l.payment_id
LEFT JOIN tariff t ON t.id = pay.tariff_id
LEFT JOIN profile ref ON ref.id = NULLIF(l.meta->>'referee_id', '')::uuid
WHERE l.profile_id = $1 AND l.entry_type = 'commission'
ORDER BY l.created_at DESC
LIMIT $2
`

type ListReferralEarningsDetailParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Limit     int32     `json:"limit"`
}

type ListReferralEarningsDetailRow struct {
	LedgerID         uuid.UUID          `json:"ledger_id"`
	CommissionUzs    int64              `json:"commission_uzs"`
	RewardedAt       pgtype.Timestamptz `json:"rewarded_at"`
	PaymentID        uuid.NullUUID      `json:"payment_id"`
	PaymentAmountUzs int64              `json:"payment_amount_uzs"`
	TariffDays       int32              `json:"tariff_days"`
	TariffCode       string             `json:"tariff_code"`
	RefereeName      string             `json:"referee_name"`
	RefereePhone     string             `json:"referee_phone"`
	PercentSnapshot  int32              `json:"percent_snapshot"`
}

// Honest transparency: each commission with payment/tariff/referee context.
func (q *Queries) ListReferralEarningsDetail(ctx context.Context, arg ListReferralEarningsDetailParams) ([]ListReferralEarningsDetailRow, error) {
	rows, err := q.db.Query(ctx, listReferralEarningsDetail, arg.ProfileID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReferralEarningsDetailRow
	for rows.Next() {
		var i ListReferralEarningsDetailRow
		if err := rows.Scan(
			&i.LedgerID,
			&i.CommissionUzs,
			&i.RewardedAt,
			&i.PaymentID,
			&i.PaymentAmountUzs,
			&i.TariffDays,
			&i.TariffCode,
			&i.RefereeName,
			&i.RefereePhone,
			&i.PercentSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferralLedgerForUser = `-- name: ListReferralLedgerForUser :many
SELECT id, profile_id, entry_type, amount_uzs, payment_id, payout_id, meta, created_at
FROM referral_ledger
WHERE profile_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListReferralLedgerForUserParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) ListReferralLedgerForUser(ctx context.Context, arg ListReferralLedgerForUserParams) ([]ReferralLedger, error) {
	rows, err := q.db.Query(ctx, listReferralLedgerForUser, arg.ProfileID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferralLedger
	for rows.Next() {
		var i ReferralLedger
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.EntryType,
			&i.AmountUzs,
			&i.PaymentID,
			&i.PayoutID,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferralPayouts = `-- name: ListReferralPayouts :many
SELECT p.id, p.profile_id, p.amount_uzs, p.card_number, p.card_network, p.status,
       p.admin_note, p.processed_by, p.created_at, p.processed_at,
       pr.phone AS profile_phone, pr.name AS profile_name
FROM referral_payout p
JOIN profile pr ON pr.id = p.profile_id
WHERE ($1::text = '' OR p.status = $1)
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListReferralPayoutsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type ListReferralPayoutsRow struct {
	ID           uuid.UUID          `json:"id"`
	ProfileID    uuid.UUID          `json:"profile_id"`
	AmountUzs    int64              `json:"amount_uzs"`
	CardNumber   string             `json:"card_number"`
	CardNetwork  string             `json:"card_network"`
	Status       string             `json:"status"`
	AdminNote    string             `json:"admin_note"`
	ProcessedBy  uuid.NullUUID      `json:"processed_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	ProfilePhone string             `json:"profile_phone"`
	ProfileName  string             `json:"profile_name"`
}

func (q *Queries) ListReferralPayouts(ctx context.Context, arg ListReferralPayoutsParams) ([]ListReferralPayoutsRow, error) {
	rows, err := q.db.Query(ctx, listReferralPayouts, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReferralPayoutsRow
	for rows.Next() {
		var i ListReferralPayoutsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.AmountUzs,
			&i.CardNumber,
			&i.CardNetwork,
			&i.Status,
			&i.AdminNote,
			&i.ProcessedBy,
			&i.CreatedAt,
			&i.ProcessedAt,
			&i.ProfilePhone,
			&i.ProfileName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferralPayoutsForProfile = `-- name: ListReferralPayoutsForProfile :many
SELECT id, amount_uzs, card_number, card_network, status, admin_note, created_at, processed_at
FROM referral_payout
WHERE profile_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListReferralPayoutsForProfileParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	Limit     int32     `json:"limit"`
}

type ListReferralPayoutsForProfileRow struct {
	ID          uuid.UUID          `json:"id"`
	AmountUzs   int64              `json:"amount_uzs"`
	CardNumber  string             `json:"card_number"`
	CardNetwork string             `json:"card_network"`
	Status      string             `json:"status"`
	AdminNote   string             `json:"admin_note"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ProcessedAt pgtype.Timestamptz `json:"processed_at"`
}

func (q *Queries) ListReferralPayoutsForProfile(ctx context.Context, arg ListReferralPayoutsForProfileParams) ([]ListReferralPayoutsForProfileRow, error) {
	rows, err := q.db.Query(ctx, listReferralPayoutsForProfile, arg.ProfileID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReferralPayoutsForProfileRow
	for rows.Next() {
		var i ListReferralPayoutsForProfileRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountUzs,
			&i.CardNumber,
			&i.CardNetwork,
			&i.Status,
			&i.AdminNote,
			&i.CreatedAt,
			&i.ProcessedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReferralPayoutPaid = `-- name: MarkReferralPayoutPaid :one
UPDATE referral_payout
SET status = 'paid',
    processed_by = $1,
    processed_at = NOW(),
    admin_note = COALESCE(NULLIF($2::text, ''), admin_note)
WHERE id = $3 AND status = 'pending'
RETURNING id, profile_id, amount_uzs, card_number, card_network, status, admin_note, processed_by, created_at, processed_at
`

type MarkReferralPayoutPaidParams struct {
	ProcessedBy uuid.NullUUID `json:"processed_by"`
	AdminNote   string        `json:"admin_note"`
	ID          uuid.UUID     `json:"id"`
}

func (q *Queries) MarkReferralPayoutPaid(ctx context.Context, arg MarkReferralPayoutPaidParams) (ReferralPayout, error) {
	row := q.db.QueryRow(ctx, markReferralPayoutPaid, arg.ProcessedBy, arg.AdminNote, arg.ID)
	var i ReferralPayout
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.AmountUzs,
		&i.CardNumber,
		&i.CardNetwork,
		&i.Status,
		&i.AdminNote,
		&i.ProcessedBy,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const markReferralPayoutRejected = `-- name: MarkReferralPayoutRejected :one
UPDATE referral_payout
SET status = 'rejected',
    processed_by = $1,
    processed_at = NOW(),
    admin_note = COALESCE(NULLIF($2::text, ''), admin_note)
WHERE id = $3 AND status = 'pending'
RETURNING id, profile_id, amount_uzs, card_number, card_network, status, admin_note, processed_by, created_at, processed_at
`

type MarkReferralPayoutRejectedParams struct {
	ProcessedBy uuid.NullUUID `json:"processed_by"`
	AdminNote   string        `json:"admin_note"`
	ID          uuid.UUID     `json:"id"`
}

func (q *Queries) MarkReferralPayoutRejected(ctx context.Context, arg MarkReferralPayoutRejectedParams) (ReferralPayout, error) {
	row := q.db.QueryRow(ctx, markReferralPayoutRejected, arg.ProcessedBy, arg.AdminNote, arg.ID)
	var i ReferralPayout
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.AmountUzs,
		&i.CardNumber,
		&i.CardNetwork,
		&i.Status,
		&i.AdminNote,
		&i.ProcessedBy,
		&i.CreatedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const updateReferralCommissionPercent = `-- name: UpdateReferralCommissionPercent :one
UPDATE profile
SET referral_commission_percent = $2
WHERE id = $1
RETURNING id, referral_commission_percent
`

type UpdateReferralCommissionPercentParams struct {
	ID                        uuid.UUID `json:"id"`
	ReferralCommissionPercent int32     `json:"referral_commission_percent"`
}

type UpdateReferralCommissionPercentRow struct {
	ID                        uuid.UUID `json:"id"`
	ReferralCommissionPercent int32     `json:"referral_commission_percent"`
}

func (q *Queries) UpdateReferralCommissionPercent(ctx context.Context, arg UpdateReferralCommissionPercentParams) (UpdateReferralCommissionPercentRow, error) {
	row := q.db.QueryRow(ctx, updateReferralCommissionPercent, arg.ID, arg.ReferralCommissionPercent)
	var i UpdateReferralCommissionPercentRow
	err := row.Scan(&i.ID, &i.ReferralCommissionPercent)
	return i, err
}
