// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: referral.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createReferral = `-- name: CreateReferral :one
INSERT INTO referral (referrer_id, referee_id, referral_code, status)
VALUES ($1, $2, $3, 'pending')
RETURNING id, referrer_id, referee_id, referral_code, status, created_at, rewarded_at
`

type CreateReferralParams struct {
	ReferrerID   uuid.UUID `json:"referrer_id"`
	RefereeID    uuid.UUID `json:"referee_id"`
	ReferralCode string    `json:"referral_code"`
}

func (q *Queries) CreateReferral(ctx context.Context, arg CreateReferralParams) (Referral, error) {
	row := q.db.QueryRow(ctx, createReferral, arg.ReferrerID, arg.RefereeID, arg.ReferralCode)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.RefereeID,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.RewardedAt,
	)
	return i, err
}

const createUserReferralCode = `-- name: CreateUserReferralCode :one
INSERT INTO user_referral_code (user_id, code)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET user_id = EXCLUDED.user_id
RETURNING user_id, code, created_at
`

type CreateUserReferralCodeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Code   string    `json:"code"`
}

func (q *Queries) CreateUserReferralCode(ctx context.Context, arg CreateUserReferralCodeParams) (UserReferralCode, error) {
	row := q.db.QueryRow(ctx, createUserReferralCode, arg.UserID, arg.Code)
	var i UserReferralCode
	err := row.Scan(&i.UserID, &i.Code, &i.CreatedAt)
	return i, err
}

const getPendingReferralForReferee = `-- name: GetPendingReferralForReferee :one
SELECT id, referrer_id, referee_id, referral_code, status, created_at, rewarded_at
FROM referral
WHERE referee_id = $1 AND status = 'pending'
`

func (q *Queries) GetPendingReferralForReferee(ctx context.Context, refereeID uuid.UUID) (Referral, error) {
	row := q.db.QueryRow(ctx, getPendingReferralForReferee, refereeID)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.ReferrerID,
		&i.RefereeID,
		&i.ReferralCode,
		&i.Status,
		&i.CreatedAt,
		&i.RewardedAt,
	)
	return i, err
}

const getReferralCodeOwner = `-- name: GetReferralCodeOwner :one
SELECT user_id, code, created_at
FROM user_referral_code
WHERE LOWER(code) = LOWER($1)
`

func (q *Queries) GetReferralCodeOwner(ctx context.Context, lower string) (UserReferralCode, error) {
	row := q.db.QueryRow(ctx, getReferralCodeOwner, lower)
	var i UserReferralCode
	err := row.Scan(&i.UserID, &i.Code, &i.CreatedAt)
	return i, err
}

const getReferralStatsForUser = `-- name: GetReferralStatsForUser :one
SELECT 
    COUNT(*)::bigint AS total_invited,
    COUNT(CASE WHEN status = 'rewarded' THEN 1 END)::bigint AS total_rewarded
FROM referral
WHERE referrer_id = $1
`

type GetReferralStatsForUserRow struct {
	TotalInvited  int64 `json:"total_invited"`
	TotalRewarded int64 `json:"total_rewarded"`
}

func (q *Queries) GetReferralStatsForUser(ctx context.Context, referrerID uuid.UUID) (GetReferralStatsForUserRow, error) {
	row := q.db.QueryRow(ctx, getReferralStatsForUser, referrerID)
	var i GetReferralStatsForUserRow
	err := row.Scan(&i.TotalInvited, &i.TotalRewarded)
	return i, err
}

const getUserReferralCode = `-- name: GetUserReferralCode :one
SELECT user_id, code, created_at
FROM user_referral_code
WHERE user_id = $1
`

func (q *Queries) GetUserReferralCode(ctx context.Context, userID uuid.UUID) (UserReferralCode, error) {
	row := q.db.QueryRow(ctx, getUserReferralCode, userID)
	var i UserReferralCode
	err := row.Scan(&i.UserID, &i.Code, &i.CreatedAt)
	return i, err
}

const markReferralRewarded = `-- name: MarkReferralRewarded :exec
UPDATE referral
SET status = 'rewarded', rewarded_at = NOW()
WHERE id = $1 AND status = 'pending'
`

func (q *Queries) MarkReferralRewarded(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markReferralRewarded, id)
	return err
}
