// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advancePracticeCursor = `-- name: AdvancePracticeCursor :exec
WITH prefix AS (
  SELECT COALESCE(MAX(position), 0)::int AS done
  FROM (
    SELECT position, position - (ROW_NUMBER() OVER (ORDER BY position))::int AS gap
    FROM session_answer WHERE session_id = $4
  ) runs
  WHERE gap = 0
), current AS (
  SELECT COALESCE((SELECT next_index FROM practice_cursor
                    WHERE profile_id = $1
                      AND category_id = $2), 0)::int AS at
)
INSERT INTO practice_cursor AS pc (profile_id, category_id, next_index)
SELECT $1, $2, $3::int + prefix.done
FROM prefix, current
WHERE $3::int <= current.at
ON CONFLICT (profile_id, category_id) DO UPDATE
SET next_index = GREATEST(pc.next_index, EXCLUDED.next_index),
    updated_at = now()
`

type AdvancePracticeCursorParams struct {
	ProfileID   uuid.UUID `json:"profile_id"`
	CategoryID  uuid.UUID `json:"category_id"`
	OrderedFrom int32     `json:"ordered_from"`
	SessionID   uuid.UUID `json:"session_id"`
}

// Moves a profile's place in a topic to the end of what it has actually worked
// through, which is not the same as the furthest question it has touched.
//
// `prefix` is the contiguous run of positions answered from the start of this
// session. position - row_number() is 0 for exactly that run: the first gap
// makes it positive and it never returns to 0. This is what stops a student who
// scrolls the question navigator to the end and answers the last chip from
// marking a 337-question topic complete -- which would wrap the walk and
// discard the class's real position -- and stops any forward jump from silently
// burying the questions it skipped over.
//
// The ordered_from <= current guard drops answers that belong to a walk the
// class has already left behind. Practice sessions are left open routinely and
// the history makes them reopenable, so without it one answer in a month-old
// session would write that old walk's position over today's and skip
// everything in between. A session of the current walk always satisfies it:
// ordered_from is the cursor as it stood when the session was drawn, and the
// cursor only ever moves forward from there.
//
// GREATEST keeps the write monotone, so answering out of order within the
// current session, or two answers racing, can never rewind the class.
func (q *Queries) AdvancePracticeCursor(ctx context.Context, arg AdvancePracticeCursorParams) error {
	_, err := q.db.Exec(ctx, advancePracticeCursor,
		arg.ProfileID,
		arg.CategoryID,
		arg.OrderedFrom,
		arg.SessionID,
	)
	return err
}

const countPracticeAnswersToday = `-- name: CountPracticeAnswersToday :one
SELECT count(*)::int FROM session_answer sa
JOIN exam_session es ON es.id = sa.session_id
WHERE es.profile_id = $1 AND es.mode = 'practice'
  AND sa.answered_at >= $2
`

type CountPracticeAnswersTodayParams struct {
	ProfileID uuid.UUID          `json:"profile_id"`
	Since     pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountPracticeAnswersToday(ctx context.Context, arg CountPracticeAnswersTodayParams) (int32, error) {
	row := q.db.QueryRow(ctx, countPracticeAnswersToday, arg.ProfileID, arg.Since)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countSessionAnswers = `-- name: CountSessionAnswers :one
SELECT
  count(*)::int AS total_answered,
  count(*) FILTER (WHERE is_correct)::int AS correct_count
FROM session_answer WHERE session_id = $1
`

type CountSessionAnswersRow struct {
	TotalAnswered int32 `json:"total_answered"`
	CorrectCount  int32 `json:"correct_count"`
}

func (q *Queries) CountSessionAnswers(ctx context.Context, sessionID uuid.UUID) (CountSessionAnswersRow, error) {
	row := q.db.QueryRow(ctx, countSessionAnswers, sessionID)
	var i CountSessionAnswersRow
	err := row.Scan(&i.TotalAnswered, &i.CorrectCount)
	return i, err
}

const countValidQuestionsInCategory = `-- name: CountValidQuestionsInCategory :one
SELECT count(*)::int FROM question
WHERE category_id = $1 AND validation_status = 'valid'
`

// Named "InCategory", not "ByCategory": learning.sql already owns
// CountValidQuestionsByCategory, which counts every category at once for the
// practice screen. This one answers about a single topic, which is what the
// ordered draw needs to know before it can decide whether the cursor has run
// off the end and should wrap.
func (q *Queries) CountValidQuestionsInCategory(ctx context.Context, categoryID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countValidQuestionsInCategory, categoryID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createExamSession = `-- name: CreateExamSession :one
WITH created AS (
  INSERT INTO exam_session
    (profile_id, mode, variant_id, category_id, sign_id, locale, time_limit_sec, errors_allowed, total, ordered_from)
  VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    COALESCE(cardinality($9::uuid[]), 0),
    $10
  )
  RETURNING id, profile_id, mode, variant_id, category_id, sign_id, locale, time_limit_sec, errors_allowed, started_at, finished_at, status, score, total, stopped_reason, readiness_pct_at_finish, ordered_from
), assigned AS (
  INSERT INTO session_question (session_id, question_id, position)
  SELECT created.id, questions.question_id, questions.position::smallint
  FROM created
  CROSS JOIN unnest($9::uuid[])
    WITH ORDINALITY AS questions(question_id, position)
  RETURNING session_id
)
SELECT created.id, created.profile_id, created.mode, created.variant_id, created.category_id, created.sign_id, created.locale, created.time_limit_sec, created.errors_allowed, created.started_at, created.finished_at, created.status, created.score, created.total, created.stopped_reason, created.readiness_pct_at_finish, created.ordered_from
FROM created
CROSS JOIN (SELECT count(*) FROM assigned) persisted
`

type CreateExamSessionParams struct {
	ProfileID     uuid.UUID     `json:"profile_id"`
	Mode          string        `json:"mode"`
	VariantID     uuid.NullUUID `json:"variant_id"`
	CategoryID    uuid.NullUUID `json:"category_id"`
	SignID        uuid.NullUUID `json:"sign_id"`
	Locale        string        `json:"locale"`
	TimeLimitSec  pgtype.Int4   `json:"time_limit_sec"`
	ErrorsAllowed pgtype.Int4   `json:"errors_allowed"`
	QuestionIds   []uuid.UUID   `json:"question_ids"`
	OrderedFrom   pgtype.Int4   `json:"ordered_from"`
}

type CreateExamSessionRow struct {
	ID                   uuid.UUID          `json:"id"`
	ProfileID            uuid.UUID          `json:"profile_id"`
	Mode                 string             `json:"mode"`
	VariantID            uuid.NullUUID      `json:"variant_id"`
	CategoryID           uuid.NullUUID      `json:"category_id"`
	SignID               uuid.NullUUID      `json:"sign_id"`
	Locale               string             `json:"locale"`
	TimeLimitSec         pgtype.Int4        `json:"time_limit_sec"`
	ErrorsAllowed        pgtype.Int4        `json:"errors_allowed"`
	StartedAt            pgtype.Timestamptz `json:"started_at"`
	FinishedAt           pgtype.Timestamptz `json:"finished_at"`
	Status               string             `json:"status"`
	Score                pgtype.Int4        `json:"score"`
	Total                int32              `json:"total"`
	StoppedReason        pgtype.Text        `json:"stopped_reason"`
	ReadinessPctAtFinish pgtype.Int4        `json:"readiness_pct_at_finish"`
	OrderedFrom          pgtype.Int4        `json:"ordered_from"`
}

func (q *Queries) CreateExamSession(ctx context.Context, arg CreateExamSessionParams) (CreateExamSessionRow, error) {
	row := q.db.QueryRow(ctx, createExamSession,
		arg.ProfileID,
		arg.Mode,
		arg.VariantID,
		arg.CategoryID,
		arg.SignID,
		arg.Locale,
		arg.TimeLimitSec,
		arg.ErrorsAllowed,
		arg.QuestionIds,
		arg.OrderedFrom,
	)
	var i CreateExamSessionRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Mode,
		&i.VariantID,
		&i.CategoryID,
		&i.SignID,
		&i.Locale,
		&i.TimeLimitSec,
		&i.ErrorsAllowed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Score,
		&i.Total,
		&i.StoppedReason,
		&i.ReadinessPctAtFinish,
		&i.OrderedFrom,
	)
	return i, err
}

const finishExamSession = `-- name: FinishExamSession :one
UPDATE exam_session
SET finished_at = now(),
    status = $2,
    score = $3,
    stopped_reason = $4,
    readiness_pct_at_finish = COALESCE($5, readiness_pct_at_finish)
WHERE id = $1
RETURNING id, profile_id, mode, variant_id, category_id, sign_id, locale, time_limit_sec, errors_allowed, started_at, finished_at, status, score, total, stopped_reason, readiness_pct_at_finish, ordered_from
`

type FinishExamSessionParams struct {
	ID                   uuid.UUID   `json:"id"`
	Status               string      `json:"status"`
	Score                pgtype.Int4 `json:"score"`
	StoppedReason        pgtype.Text `json:"stopped_reason"`
	ReadinessPctAtFinish pgtype.Int4 `json:"readiness_pct_at_finish"`
}

func (q *Queries) FinishExamSession(ctx context.Context, arg FinishExamSessionParams) (ExamSession, error) {
	row := q.db.QueryRow(ctx, finishExamSession,
		arg.ID,
		arg.Status,
		arg.Score,
		arg.StoppedReason,
		arg.ReadinessPctAtFinish,
	)
	var i ExamSession
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Mode,
		&i.VariantID,
		&i.CategoryID,
		&i.SignID,
		&i.Locale,
		&i.TimeLimitSec,
		&i.ErrorsAllowed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Score,
		&i.Total,
		&i.StoppedReason,
		&i.ReadinessPctAtFinish,
		&i.OrderedFrom,
	)
	return i, err
}

const getAnswerForScoring = `-- name: GetAnswerForScoring :one
SELECT id, question_id, is_correct FROM answer
WHERE id = $1 AND question_id = $2
`

type GetAnswerForScoringParams struct {
	ID         uuid.UUID `json:"id"`
	QuestionID uuid.UUID `json:"question_id"`
}

type GetAnswerForScoringRow struct {
	ID         uuid.UUID `json:"id"`
	QuestionID uuid.UUID `json:"question_id"`
	IsCorrect  bool      `json:"is_correct"`
}

// Also validates that answer_id truly belongs to question_id.
func (q *Queries) GetAnswerForScoring(ctx context.Context, arg GetAnswerForScoringParams) (GetAnswerForScoringRow, error) {
	row := q.db.QueryRow(ctx, getAnswerForScoring, arg.ID, arg.QuestionID)
	var i GetAnswerForScoringRow
	err := row.Scan(&i.ID, &i.QuestionID, &i.IsCorrect)
	return i, err
}

const getCategoryIDByCode = `-- name: GetCategoryIDByCode :one
SELECT id FROM category WHERE code = $1
`

func (q *Queries) GetCategoryIDByCode(ctx context.Context, code string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCategoryIDByCode, code)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getCorrectAnswerID = `-- name: GetCorrectAnswerID :one
SELECT id FROM answer WHERE question_id = $1 AND is_correct = true
`

func (q *Queries) GetCorrectAnswerID(ctx context.Context, questionID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCorrectAnswerID, questionID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getExamSession = `-- name: GetExamSession :one
SELECT id, profile_id, mode, variant_id, category_id, sign_id, locale, time_limit_sec, errors_allowed, started_at, finished_at, status, score, total, stopped_reason, readiness_pct_at_finish, ordered_from FROM exam_session WHERE id = $1
`

func (q *Queries) GetExamSession(ctx context.Context, id uuid.UUID) (ExamSession, error) {
	row := q.db.QueryRow(ctx, getExamSession, id)
	var i ExamSession
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Mode,
		&i.VariantID,
		&i.CategoryID,
		&i.SignID,
		&i.Locale,
		&i.TimeLimitSec,
		&i.ErrorsAllowed,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.Score,
		&i.Total,
		&i.StoppedReason,
		&i.ReadinessPctAtFinish,
		&i.OrderedFrom,
	)
	return i, err
}

const getLimitConfig = `-- name: GetLimitConfig :one
SELECT key, free_value, vip_value, updated_at, updated_by FROM limit_config WHERE key = $1
`

func (q *Queries) GetLimitConfig(ctx context.Context, key string) (LimitConfig, error) {
	row := q.db.QueryRow(ctx, getLimitConfig, key)
	var i LimitConfig
	err := row.Scan(
		&i.Key,
		&i.FreeValue,
		&i.VipValue,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getPracticeCursor = `-- name: GetPracticeCursor :one
SELECT next_index FROM practice_cursor
WHERE profile_id = $1 AND category_id = $2
`

type GetPracticeCursorParams struct {
	ProfileID  uuid.UUID `json:"profile_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) GetPracticeCursor(ctx context.Context, arg GetPracticeCursorParams) (int32, error) {
	row := q.db.QueryRow(ctx, getPracticeCursor, arg.ProfileID, arg.CategoryID)
	var next_index int32
	err := row.Scan(&next_index)
	return next_index, err
}

const getSessionAnswer = `-- name: GetSessionAnswer :one
SELECT session_id, question_id, answer_id, is_correct, position, answered_at FROM session_answer
WHERE session_id = $1 AND question_id = $2
`

type GetSessionAnswerParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) GetSessionAnswer(ctx context.Context, arg GetSessionAnswerParams) (SessionAnswer, error) {
	row := q.db.QueryRow(ctx, getSessionAnswer, arg.SessionID, arg.QuestionID)
	var i SessionAnswer
	err := row.Scan(
		&i.SessionID,
		&i.QuestionID,
		&i.AnswerID,
		&i.IsCorrect,
		&i.Position,
		&i.AnsweredAt,
	)
	return i, err
}

const getSessionQuestion = `-- name: GetSessionQuestion :one
SELECT session_id, question_id, position FROM session_question
WHERE session_id = $1 AND question_id = $2
`

type GetSessionQuestionParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) GetSessionQuestion(ctx context.Context, arg GetSessionQuestionParams) (SessionQuestion, error) {
	row := q.db.QueryRow(ctx, getSessionQuestion, arg.SessionID, arg.QuestionID)
	var i SessionQuestion
	err := row.Scan(&i.SessionID, &i.QuestionID, &i.Position)
	return i, err
}

const getSignIDByCode = `-- name: GetSignIDByCode :one
SELECT id FROM sign WHERE code = $1
`

func (q *Queries) GetSignIDByCode(ctx context.Context, code string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSignIDByCode, code)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getVariantByID = `-- name: GetVariantByID :one
SELECT id, number, sort_order FROM variant WHERE id = $1
`

func (q *Queries) GetVariantByID(ctx context.Context, id uuid.UUID) (Variant, error) {
	row := q.db.QueryRow(ctx, getVariantByID, id)
	var i Variant
	err := row.Scan(&i.ID, &i.Number, &i.SortOrder)
	return i, err
}

const getVariantProgress = `-- name: GetVariantProgress :one
SELECT profile_id, variant_id, best_correct, attempts, completed_at FROM variant_progress
WHERE profile_id = $1 AND variant_id = $2
`

type GetVariantProgressParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	VariantID uuid.UUID `json:"variant_id"`
}

func (q *Queries) GetVariantProgress(ctx context.Context, arg GetVariantProgressParams) (VariantProgress, error) {
	row := q.db.QueryRow(ctx, getVariantProgress, arg.ProfileID, arg.VariantID)
	var i VariantProgress
	err := row.Scan(
		&i.ProfileID,
		&i.VariantID,
		&i.BestCorrect,
		&i.Attempts,
		&i.CompletedAt,
	)
	return i, err
}

const insertSessionAnswer = `-- name: InsertSessionAnswer :one
INSERT INTO session_answer (session_id, question_id, answer_id, is_correct, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING session_id, question_id, answer_id, is_correct, position, answered_at
`

type InsertSessionAnswerParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	QuestionID uuid.UUID `json:"question_id"`
	AnswerID   uuid.UUID `json:"answer_id"`
	IsCorrect  bool      `json:"is_correct"`
	Position   int16     `json:"position"`
}

func (q *Queries) InsertSessionAnswer(ctx context.Context, arg InsertSessionAnswerParams) (SessionAnswer, error) {
	row := q.db.QueryRow(ctx, insertSessionAnswer,
		arg.SessionID,
		arg.QuestionID,
		arg.AnswerID,
		arg.IsCorrect,
		arg.Position,
	)
	var i SessionAnswer
	err := row.Scan(
		&i.SessionID,
		&i.QuestionID,
		&i.AnswerID,
		&i.IsCorrect,
		&i.Position,
		&i.AnsweredAt,
	)
	return i, err
}

const listMistakeBankQuestionIDs = `-- name: ListMistakeBankQuestionIDs :many
SELECT qm.question_id
FROM question_memory qm
JOIN question q ON q.id = qm.question_id AND q.validation_status = 'valid'
WHERE qm.profile_id = $1 AND qm.lapses > 0 AND qm.due_at <= now()
ORDER BY qm.due_at ASC
LIMIT $2
`

type ListMistakeBankQuestionIDsParams struct {
	ProfileID  uuid.UUID `json:"profile_id"`
	LimitCount int32     `json:"limit_count"`
}

func (q *Queries) ListMistakeBankQuestionIDs(ctx context.Context, arg ListMistakeBankQuestionIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMistakeBankQuestionIDs, arg.ProfileID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var question_id uuid.UUID
		if err := rows.Scan(&question_id); err != nil {
			return nil, err
		}
		items = append(items, question_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMySessions = `-- name: ListMySessions :many
SELECT id, profile_id, mode, variant_id, category_id, sign_id, locale, time_limit_sec, errors_allowed, started_at, finished_at, status, score, total, stopped_reason, readiness_pct_at_finish, ordered_from FROM exam_session
WHERE profile_id = $1
ORDER BY started_at DESC LIMIT $2
`

type ListMySessionsParams struct {
	ProfileID  uuid.UUID `json:"profile_id"`
	LimitCount int32     `json:"limit_count"`
}

func (q *Queries) ListMySessions(ctx context.Context, arg ListMySessionsParams) ([]ExamSession, error) {
	rows, err := q.db.Query(ctx, listMySessions, arg.ProfileID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExamSession
	for rows.Next() {
		var i ExamSession
		if err := rows.Scan(
			&i.ID,
			&i.ProfileID,
			&i.Mode,
			&i.VariantID,
			&i.CategoryID,
			&i.SignID,
			&i.Locale,
			&i.TimeLimitSec,
			&i.ErrorsAllowed,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.Score,
			&i.Total,
			&i.StoppedReason,
			&i.ReadinessPctAtFinish,
			&i.OrderedFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPracticeProgress = `-- name: ListPracticeProgress :many
SELECT pc.category_id,
       c.code AS category_code,
       pc.next_index,
       (SELECT count(*) FROM question q
         WHERE q.category_id = pc.category_id AND q.validation_status = 'valid')::int AS total
FROM practice_cursor pc
JOIN category c ON c.id = pc.category_id
WHERE pc.profile_id = $1
ORDER BY c.sort_order, c.code
`

type ListPracticeProgressRow struct {
	CategoryID   uuid.UUID `json:"category_id"`
	CategoryCode string    `json:"category_code"`
	NextIndex    int32     `json:"next_index"`
	Total        int32     `json:"total"`
}

// Returns the category's code as well as its id, because the code is the only
// identifier the practice screen holds: GET /categories answers with code,
// name, sort_order and question_count and no uuid at all (content.CategoryDTO).
// A progress list keyed only by uuid would be unmatchable by the one screen
// that needs it.
func (q *Queries) ListPracticeProgress(ctx context.Context, profileID uuid.UUID) ([]ListPracticeProgressRow, error) {
	rows, err := q.db.Query(ctx, listPracticeProgress, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPracticeProgressRow
	for rows.Next() {
		var i ListPracticeProgressRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryCode,
			&i.NextIndex,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionAnswers = `-- name: ListSessionAnswers :many
SELECT session_id, question_id, answer_id, is_correct, position, answered_at FROM session_answer WHERE session_id = $1 ORDER BY position
`

func (q *Queries) ListSessionAnswers(ctx context.Context, sessionID uuid.UUID) ([]SessionAnswer, error) {
	rows, err := q.db.Query(ctx, listSessionAnswers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionAnswer
	for rows.Next() {
		var i SessionAnswer
		if err := rows.Scan(
			&i.SessionID,
			&i.QuestionID,
			&i.AnswerID,
			&i.IsCorrect,
			&i.Position,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionQuestionsWithAnswers = `-- name: ListSessionQuestionsWithAnswers :many
SELECT
  sq.question_id,
  sq.position,
  sa.answer_id AS user_answer_id,
  sa.is_correct,
  q.correct_answer_id
FROM session_question sq
JOIN question q ON q.id = sq.question_id
LEFT JOIN session_answer sa
  ON sa.session_id = sq.session_id AND sa.question_id = sq.question_id
WHERE sq.session_id = $1
ORDER BY sq.position
`

type ListSessionQuestionsWithAnswersRow struct {
	QuestionID      uuid.UUID     `json:"question_id"`
	Position        int16         `json:"position"`
	UserAnswerID    uuid.NullUUID `json:"user_answer_id"`
	IsCorrect       pgtype.Bool   `json:"is_correct"`
	CorrectAnswerID uuid.NullUUID `json:"correct_answer_id"`
}

func (q *Queries) ListSessionQuestionsWithAnswers(ctx context.Context, sessionID uuid.UUID) ([]ListSessionQuestionsWithAnswersRow, error) {
	rows, err := q.db.Query(ctx, listSessionQuestionsWithAnswers, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionQuestionsWithAnswersRow
	for rows.Next() {
		var i ListSessionQuestionsWithAnswersRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.Position,
			&i.UserAnswerID,
			&i.IsCorrect,
			&i.CorrectAnswerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantProgressForProfile = `-- name: ListVariantProgressForProfile :many
SELECT profile_id, variant_id, best_correct, attempts, completed_at FROM variant_progress WHERE profile_id = $1
`

func (q *Queries) ListVariantProgressForProfile(ctx context.Context, profileID uuid.UUID) ([]VariantProgress, error) {
	rows, err := q.db.Query(ctx, listVariantProgressForProfile, profileID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VariantProgress
	for rows.Next() {
		var i VariantProgress
		if err := rows.Scan(
			&i.ProfileID,
			&i.VariantID,
			&i.BestCorrect,
			&i.Attempts,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantQuestionIDsOrdered = `-- name: ListVariantQuestionIDsOrdered :many
SELECT vq.question_id
FROM variant_question vq
JOIN question q ON q.id = vq.question_id AND q.validation_status = 'valid'
WHERE vq.variant_id = $1
ORDER BY vq.position
`

func (q *Queries) ListVariantQuestionIDsOrdered(ctx context.Context, variantID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listVariantQuestionIDsOrdered, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var question_id uuid.UUID
		if err := rows.Scan(&question_id); err != nil {
			return nil, err
		}
		items = append(items, question_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const orderedQuestionIDsByCategory = `-- name: OrderedQuestionIDsByCategory :many
SELECT q.id
FROM question q
WHERE q.validation_status = 'valid'
  AND q.category_id = $1
ORDER BY NULLIF(regexp_replace(q.source_ext_id, '\D', '', 'g'), '')::bigint NULLS LAST,
         q.source_ext_id,
         q.id
OFFSET $2
LIMIT $3
`

type OrderedQuestionIDsByCategoryParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	Skip       int32     `json:"skip"`
	LimitCount int32     `json:"limit_count"`
}

// The topic in its source order, so "all questions of one topic" is the same
// walk every time and can be resumed from an offset.
//
// source_ext_id is 'avtoimtihon-<N>' for all 1260 questions in the bank and
// every N is distinct, which makes the numeric suffix a total, unique ordering
// -- and the same numbering the source material itself uses, so it means
// something to the teacher reading it. NULLIF guards an id with no digits: it
// sorts last instead of failing the cast, and source_ext_id then id keep the
// order total even then. No index: the whole bank is 1260 rows.
func (q *Queries) OrderedQuestionIDsByCategory(ctx context.Context, arg OrderedQuestionIDsByCategoryParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, orderedQuestionIDsByCategory, arg.CategoryID, arg.Skip, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomQuestionIDs = `-- name: RandomQuestionIDs :many
WITH pivot AS MATERIALIZED (
  SELECT gen_random_uuid() AS id
), forward AS (
  SELECT q.id
  FROM question q CROSS JOIN pivot p
  WHERE q.validation_status = 'valid' AND q.id >= p.id
  ORDER BY q.id
  LIMIT $1
), wrapped AS (
  SELECT q.id
  FROM question q CROSS JOIN pivot p
  WHERE q.validation_status = 'valid' AND q.id < p.id
  ORDER BY q.id
  LIMIT $1
)
SELECT id FROM forward
UNION ALL
SELECT id FROM wrapped
LIMIT $1
`

func (q *Queries) RandomQuestionIDs(ctx context.Context, limit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, randomQuestionIDs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomQuestionIDsByCategory = `-- name: RandomQuestionIDsByCategory :many
WITH pivot AS MATERIALIZED (
  SELECT gen_random_uuid() AS id
), forward AS (
  SELECT q.id
  FROM question q CROSS JOIN pivot p
  WHERE q.validation_status = 'valid'
    AND q.category_id = $2
    AND q.id >= p.id
  ORDER BY q.id
  LIMIT $1
), wrapped AS (
  SELECT q.id
  FROM question q CROSS JOIN pivot p
  WHERE q.validation_status = 'valid'
    AND q.category_id = $2
    AND q.id < p.id
  ORDER BY q.id
  LIMIT $1
)
SELECT id FROM forward
UNION ALL
SELECT id FROM wrapped
LIMIT $1
`

type RandomQuestionIDsByCategoryParams struct {
	LimitCount int32     `json:"limit_count"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) RandomQuestionIDsByCategory(ctx context.Context, arg RandomQuestionIDsByCategoryParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, randomQuestionIDsByCategory, arg.LimitCount, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomQuestionIDsByImagePresence = `-- name: RandomQuestionIDsByImagePresence :many
WITH pivot AS MATERIALIZED (
  SELECT gen_random_uuid() AS id
), forward AS (
  SELECT q.id
  FROM question q CROSS JOIN pivot p
  WHERE q.validation_status = 'valid'
    AND (q.image_id IS NOT NULL) = $2::boolean
    AND q.id >= p.id
  ORDER BY q.id
  LIMIT $1
), wrapped AS (
  SELECT q.id
  FROM question q CROSS JOIN pivot p
  WHERE q.validation_status = 'valid'
    AND (q.image_id IS NOT NULL) = $2::boolean
    AND q.id < p.id
  ORDER BY q.id
  LIMIT $1
)
SELECT id FROM forward
UNION ALL
SELECT id FROM wrapped
LIMIT $1
`

type RandomQuestionIDsByImagePresenceParams struct {
	LimitCount int32 `json:"limit_count"`
	HasImage   bool  `json:"has_image"`
}

// has_image=true selects illustrated questions, false selects text-only ones.
func (q *Queries) RandomQuestionIDsByImagePresence(ctx context.Context, arg RandomQuestionIDsByImagePresenceParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, randomQuestionIDsByImagePresence, arg.LimitCount, arg.HasImage)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomQuestionIDsBySign = `-- name: RandomQuestionIDsBySign :many
WITH pivot AS MATERIALIZED (
  SELECT gen_random_uuid() AS id
), forward AS (
  SELECT q.id
  FROM question_sign qs
  JOIN question q ON q.id = qs.question_id
  CROSS JOIN pivot p
  WHERE q.validation_status = 'valid'
    AND qs.sign_id = $2
    AND q.id >= p.id
  ORDER BY q.id
  LIMIT $1
), wrapped AS (
  SELECT q.id
  FROM question_sign qs
  JOIN question q ON q.id = qs.question_id
  CROSS JOIN pivot p
  WHERE q.validation_status = 'valid'
    AND qs.sign_id = $2
    AND q.id < p.id
  ORDER BY q.id
  LIMIT $1
)
SELECT id FROM forward
UNION ALL
SELECT id FROM wrapped
LIMIT $1
`

type RandomQuestionIDsBySignParams struct {
	LimitCount int32     `json:"limit_count"`
	SignID     uuid.UUID `json:"sign_id"`
}

func (q *Queries) RandomQuestionIDsBySign(ctx context.Context, arg RandomQuestionIDsBySignParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, randomQuestionIDsBySign, arg.LimitCount, arg.SignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomQuestionIDsByVariantRange = `-- name: RandomQuestionIDsByVariantRange :many
WITH pivot AS MATERIALIZED (
  SELECT gen_random_uuid() AS id
), forward AS (
  SELECT q.id
  FROM question q CROSS JOIN pivot p
  WHERE q.validation_status = 'valid'
    AND q.id >= p.id
    AND EXISTS (
      SELECT 1
      FROM variant_question vq
      JOIN variant v ON v.id = vq.variant_id
      WHERE vq.question_id = q.id
        AND v.number BETWEEN $2 AND $3
    )
  ORDER BY q.id
  LIMIT $1
), wrapped AS (
  SELECT q.id
  FROM question q CROSS JOIN pivot p
  WHERE q.validation_status = 'valid'
    AND q.id < p.id
    AND EXISTS (
      SELECT 1
      FROM variant_question vq
      JOIN variant v ON v.id = vq.variant_id
      WHERE vq.question_id = q.id
        AND v.number BETWEEN $2 AND $3
    )
  ORDER BY q.id
  LIMIT $1
)
SELECT id FROM forward
UNION ALL
SELECT id FROM wrapped
LIMIT $1
`

type RandomQuestionIDsByVariantRangeParams struct {
	LimitCount int32 `json:"limit_count"`
	FromNumber int32 `json:"from_number"`
	ToNumber   int32 `json:"to_number"`
}

// Draws across a contiguous span of bilets so a learner can mix-review the
// range they have already worked through, which one-bilet-at-a-time cannot do.
func (q *Queries) RandomQuestionIDsByVariantRange(ctx context.Context, arg RandomQuestionIDsByVariantRangeParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, randomQuestionIDsByVariantRange, arg.LimitCount, arg.FromNumber, arg.ToNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetPracticeCursor = `-- name: ResetPracticeCursor :exec
DELETE FROM practice_cursor
WHERE profile_id = $1 AND category_id = $2
`

type ResetPracticeCursorParams struct {
	ProfileID  uuid.UUID `json:"profile_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

// Deleting rather than zeroing: no row IS the start, so this keeps the table
// free of rows that say nothing and makes ListPracticeProgress omit them
// without a filter.
func (q *Queries) ResetPracticeCursor(ctx context.Context, arg ResetPracticeCursorParams) error {
	_, err := q.db.Exec(ctx, resetPracticeCursor, arg.ProfileID, arg.CategoryID)
	return err
}

const upsertVariantProgress = `-- name: UpsertVariantProgress :one
INSERT INTO variant_progress (profile_id, variant_id, best_correct, attempts, completed_at)
VALUES ($1, $2, $3, 1, $4)
ON CONFLICT (profile_id, variant_id) DO UPDATE SET
  best_correct = GREATEST(variant_progress.best_correct, EXCLUDED.best_correct),
  attempts = variant_progress.attempts + 1,
  completed_at = COALESCE(variant_progress.completed_at, EXCLUDED.completed_at)
RETURNING profile_id, variant_id, best_correct, attempts, completed_at
`

type UpsertVariantProgressParams struct {
	ProfileID   uuid.UUID          `json:"profile_id"`
	VariantID   uuid.UUID          `json:"variant_id"`
	BestCorrect int32              `json:"best_correct"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpsertVariantProgress(ctx context.Context, arg UpsertVariantProgressParams) (VariantProgress, error) {
	row := q.db.QueryRow(ctx, upsertVariantProgress,
		arg.ProfileID,
		arg.VariantID,
		arg.BestCorrect,
		arg.CompletedAt,
	)
	var i VariantProgress
	err := row.Scan(
		&i.ProfileID,
		&i.VariantID,
		&i.BestCorrect,
		&i.Attempts,
		&i.CompletedAt,
	)
	return i, err
}
