// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram_quiz.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createQuizSession = `-- name: CreateQuizSession :one
INSERT INTO telegram_quiz_session (chat_id, started_by_tg_user_id)
VALUES ($1, $2)
RETURNING id, chat_id, started_by_tg_user_id, active, question_id, awaiting_answer,
          answer_message_id, asked_count, correct_count, last_activity_at, created_at
`

type CreateQuizSessionParams struct {
	ChatID            int64 `json:"chat_id"`
	StartedByTgUserID int64 `json:"started_by_tg_user_id"`
}

func (q *Queries) CreateQuizSession(ctx context.Context, arg CreateQuizSessionParams) (TelegramQuizSession, error) {
	row := q.db.QueryRow(ctx, createQuizSession, arg.ChatID, arg.StartedByTgUserID)
	var i TelegramQuizSession
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.StartedByTgUserID,
		&i.Active,
		&i.QuestionID,
		&i.AwaitingAnswer,
		&i.AnswerMessageID,
		&i.AskedCount,
		&i.CorrectCount,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateActiveQuizSessionsForChat = `-- name: DeactivateActiveQuizSessionsForChat :exec
UPDATE telegram_quiz_session
SET active = false, awaiting_answer = false, last_activity_at = now()
WHERE chat_id = $1 AND active = true
`

func (q *Queries) DeactivateActiveQuizSessionsForChat(ctx context.Context, chatID int64) error {
	_, err := q.db.Exec(ctx, deactivateActiveQuizSessionsForChat, chatID)
	return err
}

const deactivateQuizSession = `-- name: DeactivateQuizSession :exec
UPDATE telegram_quiz_session
SET active = false, awaiting_answer = false, last_activity_at = now()
WHERE id = $1 AND active = true
`

func (q *Queries) DeactivateQuizSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateQuizSession, id)
	return err
}

const deleteTelegramAccountByTgUserID = `-- name: DeleteTelegramAccountByTgUserID :execrows
DELETE FROM telegram_account WHERE tg_user_id = $1
`

func (q *Queries) DeleteTelegramAccountByTgUserID(ctx context.Context, tgUserID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTelegramAccountByTgUserID, tgUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveQuizSessionByChat = `-- name: GetActiveQuizSessionByChat :one
SELECT id, chat_id, started_by_tg_user_id, active, question_id, awaiting_answer,
       answer_message_id, asked_count, correct_count, last_activity_at, created_at
FROM telegram_quiz_session
WHERE chat_id = $1 AND active = true
`

func (q *Queries) GetActiveQuizSessionByChat(ctx context.Context, chatID int64) (TelegramQuizSession, error) {
	row := q.db.QueryRow(ctx, getActiveQuizSessionByChat, chatID)
	var i TelegramQuizSession
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.StartedByTgUserID,
		&i.Active,
		&i.QuestionID,
		&i.AwaitingAnswer,
		&i.AnswerMessageID,
		&i.AskedCount,
		&i.CorrectCount,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const getActiveQuizSessionByChatForUpdate = `-- name: GetActiveQuizSessionByChatForUpdate :one
SELECT id, chat_id, started_by_tg_user_id, active, question_id, awaiting_answer,
       answer_message_id, asked_count, correct_count, last_activity_at, created_at
FROM telegram_quiz_session
WHERE chat_id = $1 AND active = true
FOR UPDATE
`

func (q *Queries) GetActiveQuizSessionByChatForUpdate(ctx context.Context, chatID int64) (TelegramQuizSession, error) {
	row := q.db.QueryRow(ctx, getActiveQuizSessionByChatForUpdate, chatID)
	var i TelegramQuizSession
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.StartedByTgUserID,
		&i.Active,
		&i.QuestionID,
		&i.AwaitingAnswer,
		&i.AnswerMessageID,
		&i.AskedCount,
		&i.CorrectCount,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}

const listQuizAnswers = `-- name: ListQuizAnswers :many
SELECT a.id, a.position, a.is_correct,
       COALESCE(at.text, aft.text, '') AS text
FROM answer a
LEFT JOIN answer_translation at
       ON at.answer_id = a.id AND at.locale = $1 AND at.status = 'verified'
LEFT JOIN answer_translation aft
       ON aft.answer_id = a.id AND aft.locale = 'uz-Latn' AND aft.status = 'verified'
WHERE a.question_id = $2
ORDER BY a.position
`

type ListQuizAnswersParams struct {
	Locale     string    `json:"locale"`
	QuestionID uuid.UUID `json:"question_id"`
}

type ListQuizAnswersRow struct {
	ID        uuid.UUID `json:"id"`
	Position  int16     `json:"position"`
	IsCorrect bool      `json:"is_correct"`
	Text      string    `json:"text"`
}

// Includes is_correct for bot grading (never exposed on the public content API).
func (q *Queries) ListQuizAnswers(ctx context.Context, arg ListQuizAnswersParams) ([]ListQuizAnswersRow, error) {
	rows, err := q.db.Query(ctx, listQuizAnswers, arg.Locale, arg.QuestionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListQuizAnswersRow
	for rows.Next() {
		var i ListQuizAnswersRow
		if err := rows.Scan(
			&i.ID,
			&i.Position,
			&i.IsCorrect,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTelegramDigestCandidates = `-- name: ListTelegramDigestCandidates :many
SELECT ta.tg_user_id, p.id AS profile_id, p.locale_pref,
       COUNT(qm.question_id)::int AS due_count
FROM telegram_account ta
JOIN profile p ON p.id = ta.profile_id AND p.status = 'active'
JOIN question_memory qm ON qm.profile_id = p.id AND qm.due_at <= now()
JOIN question q ON q.id = qm.question_id AND q.validation_status = 'valid'
WHERE NOT EXISTS (
  SELECT 1 FROM notification n
  WHERE n.profile_id = p.id
    AND n.kind = $1
    AND n.channel = 'telegram'
    AND n.created_at > now() - ($2::text)::interval
)
GROUP BY ta.tg_user_id, p.id, p.locale_pref
HAVING COUNT(qm.question_id) > 0
ORDER BY due_count DESC, p.id
LIMIT $3
`

type ListTelegramDigestCandidatesParams struct {
	Kind       string `json:"kind"`
	Cooldown   string `json:"cooldown"`
	LimitCount int32  `json:"limit_count"`
}

type ListTelegramDigestCandidatesRow struct {
	TgUserID   int64     `json:"tg_user_id"`
	ProfileID  uuid.UUID `json:"profile_id"`
	LocalePref string    `json:"locale_pref"`
	DueCount   int32     `json:"due_count"`
}

// Linked profiles with ≥1 due FSRS card, excluding recent telegram digests.
func (q *Queries) ListTelegramDigestCandidates(ctx context.Context, arg ListTelegramDigestCandidatesParams) ([]ListTelegramDigestCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listTelegramDigestCandidates, arg.Kind, arg.Cooldown, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTelegramDigestCandidatesRow
	for rows.Next() {
		var i ListTelegramDigestCandidatesRow
		if err := rows.Scan(
			&i.TgUserID,
			&i.ProfileID,
			&i.LocalePref,
			&i.DueCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markQuizSessionAnswered = `-- name: MarkQuizSessionAnswered :execrows
UPDATE telegram_quiz_session
SET awaiting_answer = false,
    correct_count = correct_count + $1,
    last_activity_at = now()
WHERE id = $2 AND active = true AND awaiting_answer = true
`

type MarkQuizSessionAnsweredParams struct {
	CorrectDelta int32     `json:"correct_delta"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) MarkQuizSessionAnswered(ctx context.Context, arg MarkQuizSessionAnsweredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markQuizSessionAnswered, arg.CorrectDelta, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setQuizSessionQuestion = `-- name: SetQuizSessionQuestion :exec
UPDATE telegram_quiz_session
SET question_id = $2,
    awaiting_answer = true,
    answer_message_id = $3,
    asked_count = asked_count + 1,
    last_activity_at = now()
WHERE id = $1 AND active = true
`

type SetQuizSessionQuestionParams struct {
	ID              uuid.UUID     `json:"id"`
	QuestionID      uuid.NullUUID `json:"question_id"`
	AnswerMessageID int64         `json:"answer_message_id"`
}

func (q *Queries) SetQuizSessionQuestion(ctx context.Context, arg SetQuizSessionQuestionParams) error {
	_, err := q.db.Exec(ctx, setQuizSessionQuestion, arg.ID, arg.QuestionID, arg.AnswerMessageID)
	return err
}

const touchQuizSessionActivity = `-- name: TouchQuizSessionActivity :exec
UPDATE telegram_quiz_session
SET last_activity_at = now()
WHERE id = $1
`

func (q *Queries) TouchQuizSessionActivity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchQuizSessionActivity, id)
	return err
}

const upsertTelegramChat = `-- name: UpsertTelegramChat :exec
INSERT INTO telegram_chat (chat_id, title, chat_type, bot_status, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (chat_id) DO UPDATE SET
  title = EXCLUDED.title,
  chat_type = EXCLUDED.chat_type,
  bot_status = EXCLUDED.bot_status,
  updated_at = now()
`

type UpsertTelegramChatParams struct {
	ChatID    int64  `json:"chat_id"`
	Title     string `json:"title"`
	ChatType  string `json:"chat_type"`
	BotStatus string `json:"bot_status"`
}

func (q *Queries) UpsertTelegramChat(ctx context.Context, arg UpsertTelegramChatParams) error {
	_, err := q.db.Exec(ctx, upsertTelegramChat,
		arg.ChatID,
		arg.Title,
		arg.ChatType,
		arg.BotStatus,
	)
	return err
}
