// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLinkToken = `-- name: CreateLinkToken :one
INSERT INTO telegram_link_token (profile_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, expires_at
`

type CreateLinkTokenParams struct {
	ProfileID uuid.UUID          `json:"profile_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateLinkTokenRow struct {
	ID        uuid.UUID          `json:"id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateLinkToken(ctx context.Context, arg CreateLinkTokenParams) (CreateLinkTokenRow, error) {
	row := q.db.QueryRow(ctx, createLinkToken, arg.ProfileID, arg.TokenHash, arg.ExpiresAt)
	var i CreateLinkTokenRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const deleteUnusedLinkTokensForProfile = `-- name: DeleteUnusedLinkTokensForProfile :exec
DELETE FROM telegram_link_token WHERE profile_id = $1 AND used_at IS NULL
`

// Keeps the table to one live row per profile: a fresh generate() call makes
// any earlier, still-unused token for the same profile immediately
// unredeemable rather than leaving several tokens with confusingly
// different expiries alive at once.
func (q *Queries) DeleteUnusedLinkTokensForProfile(ctx context.Context, profileID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnusedLinkTokensForProfile, profileID)
	return err
}

const getLinkTokenByHashForUpdate = `-- name: GetLinkTokenByHashForUpdate :one
SELECT id, profile_id, expires_at, used_at
FROM telegram_link_token
WHERE token_hash = $1
FOR UPDATE
`

type GetLinkTokenByHashForUpdateRow struct {
	ID        uuid.UUID          `json:"id"`
	ProfileID uuid.UUID          `json:"profile_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
}

// Row-locking lookup for the redeem path (bot.LinkService.RedeemLinkToken):
// locks the token row for the duration of the check-then-act (status check,
// then telegram_account upsert, then mark-used) so two concurrent redeem
// attempts for the same token serialize instead of both passing the
// used_at IS NULL check before either writes it. Same shape as
// LockProfileForGrant in billing.
func (q *Queries) GetLinkTokenByHashForUpdate(ctx context.Context, tokenHash string) (GetLinkTokenByHashForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getLinkTokenByHashForUpdate, tokenHash)
	var i GetLinkTokenByHashForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getTelegramAccountByProfileID = `-- name: GetTelegramAccountByProfileID :one
SELECT profile_id, tg_user_id, username, linked_at
FROM telegram_account
WHERE profile_id = $1
`

func (q *Queries) GetTelegramAccountByProfileID(ctx context.Context, profileID uuid.UUID) (TelegramAccount, error) {
	row := q.db.QueryRow(ctx, getTelegramAccountByProfileID, profileID)
	var i TelegramAccount
	err := row.Scan(
		&i.ProfileID,
		&i.TgUserID,
		&i.Username,
		&i.LinkedAt,
	)
	return i, err
}

const getTelegramAccountByTgUserID = `-- name: GetTelegramAccountByTgUserID :one
SELECT profile_id, tg_user_id, username, linked_at
FROM telegram_account
WHERE tg_user_id = $1
`

func (q *Queries) GetTelegramAccountByTgUserID(ctx context.Context, tgUserID int64) (TelegramAccount, error) {
	row := q.db.QueryRow(ctx, getTelegramAccountByTgUserID, tgUserID)
	var i TelegramAccount
	err := row.Scan(
		&i.ProfileID,
		&i.TgUserID,
		&i.Username,
		&i.LinkedAt,
	)
	return i, err
}

const markLinkTokenUsed = `-- name: MarkLinkTokenUsed :exec
UPDATE telegram_link_token SET used_at = now() WHERE id = $1
`

func (q *Queries) MarkLinkTokenUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markLinkTokenUsed, id)
	return err
}

const upsertTelegramAccount = `-- name: UpsertTelegramAccount :exec
INSERT INTO telegram_account (profile_id, tg_user_id, username, linked_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (profile_id) DO UPDATE SET
  tg_user_id = EXCLUDED.tg_user_id,
  username   = EXCLUDED.username,
  linked_at  = now()
`

type UpsertTelegramAccountParams struct {
	ProfileID uuid.UUID `json:"profile_id"`
	TgUserID  int64     `json:"tg_user_id"`
	Username  string    `json:"username"`
}

// ON CONFLICT targets profile_id (the primary key) only: re-linking the same
// profile to a new tg_user_id is allowed (last link wins, see design §3.3).
// Binding a tg_user_id that already belongs to a DIFFERENT profile is not
// caught by this ON CONFLICT clause — it instead raises a unique_violation
// on telegram_account's tg_user_id constraint, which the caller must catch
// and translate to ErrTelegramAccountLinkedElsewhere. That's deliberate: it
// is the atomic backstop against a race between two concurrent redemptions
// targeting the same Telegram account for two different profiles.
func (q *Queries) UpsertTelegramAccount(ctx context.Context, arg UpsertTelegramAccountParams) error {
	_, err := q.db.Exec(ctx, upsertTelegramAccount, arg.ProfileID, arg.TgUserID, arg.Username)
	return err
}
