// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram_login.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveTelegramLoginRequest = `-- name: ApproveTelegramLoginRequest :execrows
UPDATE telegram_login_request
SET status = 'approved', profile_id = $2, approved_tg_user_id = $3, approved_at = now(),
    pending_tg_user_id = NULL, confirm_nonce_hash = NULL, contact_phone = NULL
WHERE id = $1 AND status = 'pending'
`

type ApproveTelegramLoginRequestParams struct {
	ID               uuid.UUID     `json:"id"`
	ProfileID        uuid.NullUUID `json:"profile_id"`
	ApprovedTgUserID pgtype.Int8   `json:"approved_tg_user_id"`
}

func (q *Queries) ApproveTelegramLoginRequest(ctx context.Context, arg ApproveTelegramLoginRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, approveTelegramLoginRequest, arg.ID, arg.ProfileID, arg.ApprovedTgUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const armTelegramLoginForTg = `-- name: ArmTelegramLoginForTg :exec
UPDATE telegram_login_request
SET pending_tg_user_id = $2, confirm_nonce_hash = $3, contact_phone = NULL,
    opened_tg_user_id = COALESCE(opened_tg_user_id, $2)
WHERE id = $1
`

type ArmTelegramLoginForTgParams struct {
	ID               uuid.UUID   `json:"id"`
	PendingTgUserID  pgtype.Int8 `json:"pending_tg_user_id"`
	ConfirmNonceHash pgtype.Text `json:"confirm_nonce_hash"`
}

// /start login_ by the request's (first) opener. A re-open starts the bot
// step over: any shared phone waiting for its tap is dropped.
func (q *Queries) ArmTelegramLoginForTg(ctx context.Context, arg ArmTelegramLoginForTgParams) error {
	_, err := q.db.Exec(ctx, armTelegramLoginForTg, arg.ID, arg.PendingTgUserID, arg.ConfirmNonceHash)
	return err
}

const askTelegramLoginConfirmAfterContact = `-- name: AskTelegramLoginConfirmAfterContact :execrows
UPDATE telegram_login_request
SET confirm_nonce_hash = $2, contact_phone = $3
WHERE id = $1 AND status = 'pending'
`

type AskTelegramLoginConfirmAfterContactParams struct {
	ID               uuid.UUID   `json:"id"`
	ConfirmNonceHash pgtype.Text `json:"confirm_nonce_hash"`
	ContactPhone     pgtype.Text `json:"contact_phone"`
}

// The opener shared their own number: remember it and open the «✅ Kirish»
// question. Only that tap approves.
func (q *Queries) AskTelegramLoginConfirmAfterContact(ctx context.Context, arg AskTelegramLoginConfirmAfterContactParams) (int64, error) {
	result, err := q.db.Exec(ctx, askTelegramLoginConfirmAfterContact, arg.ID, arg.ConfirmNonceHash, arg.ContactPhone)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const clearAllTelegramLoginPendingForTg = `-- name: ClearAllTelegramLoginPendingForTg :exec
UPDATE telegram_login_request
SET pending_tg_user_id = NULL, confirm_nonce_hash = NULL, contact_phone = NULL
WHERE pending_tg_user_id = $1 AND status = 'pending'
`

// Disarm: this Telegram user moved on to something else in the bot chat — a
// password reset (/start pwr_) or the Mini App's phone share — so a website
// login they opened earlier must not be answered by what they do next. The
// question already sent stops working; opened_tg_user_id stays, so only they
// can open the link again.
func (q *Queries) ClearAllTelegramLoginPendingForTg(ctx context.Context, pendingTgUserID pgtype.Int8) error {
	_, err := q.db.Exec(ctx, clearAllTelegramLoginPendingForTg, pendingTgUserID)
	return err
}

const clearTelegramBotUserPendingReferral = `-- name: ClearTelegramBotUserPendingReferral :exec
UPDATE telegram_bot_user
SET pending_referral_code = NULL, pending_referral_at = NULL
WHERE tg_user_id = $1
`

func (q *Queries) ClearTelegramBotUserPendingReferral(ctx context.Context, tgUserID int64) error {
	_, err := q.db.Exec(ctx, clearTelegramBotUserPendingReferral, tgUserID)
	return err
}

const clearTelegramLoginPendingForTg = `-- name: ClearTelegramLoginPendingForTg :exec
UPDATE telegram_login_request
SET pending_tg_user_id = NULL, confirm_nonce_hash = NULL, contact_phone = NULL
WHERE pending_tg_user_id = $1 AND id <> $2
`

type ClearTelegramLoginPendingForTgParams struct {
	PendingTgUserID pgtype.Int8 `json:"pending_tg_user_id"`
	ID              uuid.UUID   `json:"id"`
}

// A newer /start login_ of the same Telegram user owns their next contact
// share; older requests drop their claim (and any open «✅ Kirish» question).
func (q *Queries) ClearTelegramLoginPendingForTg(ctx context.Context, arg ClearTelegramLoginPendingForTgParams) error {
	_, err := q.db.Exec(ctx, clearTelegramLoginPendingForTg, arg.PendingTgUserID, arg.ID)
	return err
}

const consumeTelegramLoginRequest = `-- name: ConsumeTelegramLoginRequest :execrows
UPDATE telegram_login_request
SET status = 'consumed', consumed_at = now()
WHERE id = $1 AND status = 'approved'
`

func (q *Queries) ConsumeTelegramLoginRequest(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeTelegramLoginRequest, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createTelegramLoginRequest = `-- name: CreateTelegramLoginRequest :one
INSERT INTO telegram_login_request (token_hash, browser_secret_hash, device, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, token_hash, browser_secret_hash, device, status, pending_tg_user_id, confirm_nonce_hash, profile_id, approved_tg_user_id, expires_at, approved_at, consumed_at, created_at, opened_tg_user_id, contact_phone
`

type CreateTelegramLoginRequestParams struct {
	TokenHash         string             `json:"token_hash"`
	BrowserSecretHash string             `json:"browser_secret_hash"`
	Device            string             `json:"device"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateTelegramLoginRequest(ctx context.Context, arg CreateTelegramLoginRequestParams) (TelegramLoginRequest, error) {
	row := q.db.QueryRow(ctx, createTelegramLoginRequest,
		arg.TokenHash,
		arg.BrowserSecretHash,
		arg.Device,
		arg.ExpiresAt,
	)
	var i TelegramLoginRequest
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.BrowserSecretHash,
		&i.Device,
		&i.Status,
		&i.PendingTgUserID,
		&i.ConfirmNonceHash,
		&i.ProfileID,
		&i.ApprovedTgUserID,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.OpenedTgUserID,
		&i.ContactPhone,
	)
	return i, err
}

const deleteOtherRefreshTokens = `-- name: DeleteOtherRefreshTokens :execrows
DELETE FROM refresh_token
WHERE profile_id = $1 AND token_hash <> $2
`

type DeleteOtherRefreshTokensParams struct {
	ProfileID     uuid.UUID `json:"profile_id"`
	KeepTokenHash string    `json:"keep_token_hash"`
}

// A first password was set: every other session of the profile ends, the
// caller's (keep_token_hash; ” keeps none) stays. Deleted rather than
// revoked on purpose: a revoked refresh token presented later is treated as
// reuse and revokes the whole profile — which would sign the keeper out the
// next time any other device woke up.
func (q *Queries) DeleteOtherRefreshTokens(ctx context.Context, arg DeleteOtherRefreshTokensParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtherRefreshTokens, arg.ProfileID, arg.KeepTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleTelegramLoginRequests = `-- name: DeleteStaleTelegramLoginRequests :exec
DELETE FROM telegram_login_request
WHERE id IN (
  SELECT id FROM telegram_login_request
  WHERE expires_at < now() - interval '1 day'
  LIMIT 500
)
`

// Retention: a request is useless a day past its expiry. Bounded per call so
// a backlog never turns one website click into a long DELETE.
func (q *Queries) DeleteStaleTelegramLoginRequests(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteStaleTelegramLoginRequests)
	return err
}

const endTelegramLoginRequest = `-- name: EndTelegramLoginRequest :execrows
UPDATE telegram_login_request
SET status = $2, pending_tg_user_id = NULL, confirm_nonce_hash = NULL, contact_phone = NULL
WHERE id = $1 AND status = 'pending'
`

type EndTelegramLoginRequestParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// 'cancelled' (the learner said no) or 'blocked' (the account is banned).
func (q *Queries) EndTelegramLoginRequest(ctx context.Context, arg EndTelegramLoginRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, endTelegramLoginRequest, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLiveTelegramLoginByPendingTgForUpdate = `-- name: GetLiveTelegramLoginByPendingTgForUpdate :one
SELECT id, token_hash, browser_secret_hash, device, status, pending_tg_user_id, confirm_nonce_hash, profile_id, approved_tg_user_id, expires_at, approved_at, consumed_at, created_at, opened_tg_user_id, contact_phone FROM telegram_login_request
WHERE pending_tg_user_id = $1 AND status = 'pending' AND expires_at > now()
FOR UPDATE
`

func (q *Queries) GetLiveTelegramLoginByPendingTgForUpdate(ctx context.Context, pendingTgUserID pgtype.Int8) (TelegramLoginRequest, error) {
	row := q.db.QueryRow(ctx, getLiveTelegramLoginByPendingTgForUpdate, pendingTgUserID)
	var i TelegramLoginRequest
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.BrowserSecretHash,
		&i.Device,
		&i.Status,
		&i.PendingTgUserID,
		&i.ConfirmNonceHash,
		&i.ProfileID,
		&i.ApprovedTgUserID,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.OpenedTgUserID,
		&i.ContactPhone,
	)
	return i, err
}

const getTelegramBotUserPendingReferral = `-- name: GetTelegramBotUserPendingReferral :one
SELECT pending_referral_code::text AS code FROM telegram_bot_user
WHERE tg_user_id = $1
  AND pending_referral_code IS NOT NULL
  AND pending_referral_at > now() - interval '30 days'
`

func (q *Queries) GetTelegramBotUserPendingReferral(ctx context.Context, tgUserID int64) (string, error) {
	row := q.db.QueryRow(ctx, getTelegramBotUserPendingReferral, tgUserID)
	var code string
	err := row.Scan(&code)
	return code, err
}

const getTelegramLoginByConfirmNonceForUpdate = `-- name: GetTelegramLoginByConfirmNonceForUpdate :one
SELECT id, token_hash, browser_secret_hash, device, status, pending_tg_user_id, confirm_nonce_hash, profile_id, approved_tg_user_id, expires_at, approved_at, consumed_at, created_at, opened_tg_user_id, contact_phone FROM telegram_login_request WHERE confirm_nonce_hash = $1 FOR UPDATE
`

func (q *Queries) GetTelegramLoginByConfirmNonceForUpdate(ctx context.Context, confirmNonceHash pgtype.Text) (TelegramLoginRequest, error) {
	row := q.db.QueryRow(ctx, getTelegramLoginByConfirmNonceForUpdate, confirmNonceHash)
	var i TelegramLoginRequest
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.BrowserSecretHash,
		&i.Device,
		&i.Status,
		&i.PendingTgUserID,
		&i.ConfirmNonceHash,
		&i.ProfileID,
		&i.ApprovedTgUserID,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.OpenedTgUserID,
		&i.ContactPhone,
	)
	return i, err
}

const getTelegramLoginRequestByTokenHash = `-- name: GetTelegramLoginRequestByTokenHash :one
SELECT id, token_hash, browser_secret_hash, device, status, pending_tg_user_id, confirm_nonce_hash, profile_id, approved_tg_user_id, expires_at, approved_at, consumed_at, created_at, opened_tg_user_id, contact_phone FROM telegram_login_request WHERE token_hash = $1
`

func (q *Queries) GetTelegramLoginRequestByTokenHash(ctx context.Context, tokenHash string) (TelegramLoginRequest, error) {
	row := q.db.QueryRow(ctx, getTelegramLoginRequestByTokenHash, tokenHash)
	var i TelegramLoginRequest
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.BrowserSecretHash,
		&i.Device,
		&i.Status,
		&i.PendingTgUserID,
		&i.ConfirmNonceHash,
		&i.ProfileID,
		&i.ApprovedTgUserID,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.OpenedTgUserID,
		&i.ContactPhone,
	)
	return i, err
}

const getTelegramLoginRequestByTokenHashForUpdate = `-- name: GetTelegramLoginRequestByTokenHashForUpdate :one
SELECT id, token_hash, browser_secret_hash, device, status, pending_tg_user_id, confirm_nonce_hash, profile_id, approved_tg_user_id, expires_at, approved_at, consumed_at, created_at, opened_tg_user_id, contact_phone FROM telegram_login_request WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) GetTelegramLoginRequestByTokenHashForUpdate(ctx context.Context, tokenHash string) (TelegramLoginRequest, error) {
	row := q.db.QueryRow(ctx, getTelegramLoginRequestByTokenHashForUpdate, tokenHash)
	var i TelegramLoginRequest
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.BrowserSecretHash,
		&i.Device,
		&i.Status,
		&i.PendingTgUserID,
		&i.ConfirmNonceHash,
		&i.ProfileID,
		&i.ApprovedTgUserID,
		&i.ExpiresAt,
		&i.ApprovedAt,
		&i.ConsumedAt,
		&i.CreatedAt,
		&i.OpenedTgUserID,
		&i.ContactPhone,
	)
	return i, err
}

const getUserProfileByPhone = `-- name: GetUserProfileByPhone :one
SELECT id, phone, name, region, district, birth_date, locale_pref, theme_pref, role, referral_code, referred_by, status, created_at, password_hash, referral_commission_percent, bypass_variant_progress, kind, must_change_password, variant_unlock_ceiling, avatar_key, avatar_source, avatar_updated_at FROM profile WHERE phone = $1 AND kind = 'user'
`

// Telegram login / Mini App phone sign-in only ever match learners: a B2B
// station's shadow profile (kind = 'station', phone 'st:<uuid>') must be
// impossible to sign in to this way, whatever its phone column holds.
func (q *Queries) GetUserProfileByPhone(ctx context.Context, phone string) (Profile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByPhone, phone)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Region,
		&i.District,
		&i.BirthDate,
		&i.LocalePref,
		&i.ThemePref,
		&i.Role,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.Status,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.ReferralCommissionPercent,
		&i.BypassVariantProgress,
		&i.Kind,
		&i.MustChangePassword,
		&i.VariantUnlockCeiling,
		&i.AvatarKey,
		&i.AvatarSource,
		&i.AvatarUpdatedAt,
	)
	return i, err
}

const setProfilePasswordIfUnset = `-- name: SetProfilePasswordIfUnset :one
UPDATE profile
SET password_hash = $2, must_change_password = false
WHERE id = $1 AND kind = 'user' AND (password_hash IS NULL OR password_hash = '')
RETURNING id, phone, name, region, district, birth_date, locale_pref, theme_pref, role, referral_code, referred_by, status, created_at, password_hash, referral_commission_percent, bypass_variant_progress, kind, must_change_password, variant_unlock_ceiling, avatar_key, avatar_source, avatar_updated_at
`

type SetProfilePasswordIfUnsetParams struct {
	ID           uuid.UUID   `json:"id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

// First password for an account created through Telegram. The WHERE makes it
// a no-op (no row) once any password exists: that one is changed with the
// current password instead (POST /me/password).
// Learners only: a B2B station's shadow profile never gets a password.
func (q *Queries) SetProfilePasswordIfUnset(ctx context.Context, arg SetProfilePasswordIfUnsetParams) (Profile, error) {
	row := q.db.QueryRow(ctx, setProfilePasswordIfUnset, arg.ID, arg.PasswordHash)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Name,
		&i.Region,
		&i.District,
		&i.BirthDate,
		&i.LocalePref,
		&i.ThemePref,
		&i.Role,
		&i.ReferralCode,
		&i.ReferredBy,
		&i.Status,
		&i.CreatedAt,
		&i.PasswordHash,
		&i.ReferralCommissionPercent,
		&i.BypassVariantProgress,
		&i.Kind,
		&i.MustChangePassword,
		&i.VariantUnlockCeiling,
		&i.AvatarKey,
		&i.AvatarSource,
		&i.AvatarUpdatedAt,
	)
	return i, err
}

const setTelegramBotUserPendingReferral = `-- name: SetTelegramBotUserPendingReferral :exec
INSERT INTO telegram_bot_user (tg_user_id, pending_referral_code, pending_referral_at)
VALUES ($1, $2, now())
ON CONFLICT (tg_user_id) DO UPDATE
  SET pending_referral_code = EXCLUDED.pending_referral_code,
      pending_referral_at   = now()
`

type SetTelegramBotUserPendingReferralParams struct {
	TgUserID            int64       `json:"tg_user_id"`
	PendingReferralCode pgtype.Text `json:"pending_referral_code"`
}

func (q *Queries) SetTelegramBotUserPendingReferral(ctx context.Context, arg SetTelegramBotUserPendingReferralParams) error {
	_, err := q.db.Exec(ctx, setTelegramBotUserPendingReferral, arg.TgUserID, arg.PendingReferralCode)
	return err
}
