// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: telegram_daily.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimTelegramReminderRecipient = `-- name: ClaimTelegramReminderRecipient :one
UPDATE telegram_bot_user u
SET last_reminder_on = $1::date
WHERE u.tg_user_id = (
  SELECT c.tg_user_id FROM telegram_bot_user c
  WHERE c.reminders_enabled
    AND c.blocked_at IS NULL
    AND c.last_reminder_on IS DISTINCT FROM $1::date
  ORDER BY c.tg_user_id
  LIMIT 1
  FOR UPDATE SKIP LOCKED
)
RETURNING u.tg_user_id
`

// Claims one recipient for the day and records the claim in the same
// statement: a crash after this never sends to them twice, and SKIP LOCKED
// lets a second pass (another replica) take a different user.
func (q *Queries) ClaimTelegramReminderRecipient(ctx context.Context, day pgtype.Date) (int64, error) {
	row := q.db.QueryRow(ctx, claimTelegramReminderRecipient, day)
	var tg_user_id int64
	err := row.Scan(&tg_user_id)
	return tg_user_id, err
}

const countTelegramReminderAudience = `-- name: CountTelegramReminderAudience :one
SELECT COUNT(*)::int AS total,
       COUNT(*) FILTER (WHERE NOT reminders_enabled)::int AS opted_out,
       COUNT(*) FILTER (WHERE reminders_enabled AND blocked_at IS NOT NULL)::int AS blocked,
       COUNT(*) FILTER (WHERE reminders_enabled AND blocked_at IS NULL)::int AS eligible,
       COUNT(*) FILTER (WHERE reminders_enabled AND blocked_at IS NULL
                          AND last_reminder_on IS DISTINCT FROM $1::date)::int AS pending
FROM telegram_bot_user
`

type CountTelegramReminderAudienceRow struct {
	Total    int32 `json:"total"`
	OptedOut int32 `json:"opted_out"`
	Blocked  int32 `json:"blocked"`
	Eligible int32 `json:"eligible"`
	Pending  int32 `json:"pending"`
}

func (q *Queries) CountTelegramReminderAudience(ctx context.Context, day pgtype.Date) (CountTelegramReminderAudienceRow, error) {
	row := q.db.QueryRow(ctx, countTelegramReminderAudience, day)
	var i CountTelegramReminderAudienceRow
	err := row.Scan(
		&i.Total,
		&i.OptedOut,
		&i.Blocked,
		&i.Eligible,
		&i.Pending,
	)
	return i, err
}

const disableTelegramReminders = `-- name: DisableTelegramReminders :exec
INSERT INTO telegram_bot_user (tg_user_id, reminders_enabled)
VALUES ($1, false)
ON CONFLICT (tg_user_id) DO UPDATE SET reminders_enabled = false
`

func (q *Queries) DisableTelegramReminders(ctx context.Context, tgUserID int64) error {
	_, err := q.db.Exec(ctx, disableTelegramReminders, tgUserID)
	return err
}

const getDailyQuestion = `-- name: GetDailyQuestion :one
SELECT question_id FROM telegram_daily_question WHERE day = $1
`

func (q *Queries) GetDailyQuestion(ctx context.Context, day pgtype.Date) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDailyQuestion, day)
	var question_id uuid.UUID
	err := row.Scan(&question_id)
	return question_id, err
}

const getTelegramBotUser = `-- name: GetTelegramBotUser :one
SELECT tg_user_id, first_name, username, language_code, first_seen_at, last_seen_at,
       reminders_enabled, blocked_at, last_reminder_on
FROM telegram_bot_user WHERE tg_user_id = $1
`

func (q *Queries) GetTelegramBotUser(ctx context.Context, tgUserID int64) (TelegramBotUser, error) {
	row := q.db.QueryRow(ctx, getTelegramBotUser, tgUserID)
	var i TelegramBotUser
	err := row.Scan(
		&i.TgUserID,
		&i.FirstName,
		&i.Username,
		&i.LanguageCode,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.RemindersEnabled,
		&i.BlockedAt,
		&i.LastReminderOn,
	)
	return i, err
}

const insertDailyQuestion = `-- name: InsertDailyQuestion :exec
INSERT INTO telegram_daily_question (day, question_id) VALUES ($1, $2)
ON CONFLICT (day) DO NOTHING
`

type InsertDailyQuestionParams struct {
	Day        pgtype.Date `json:"day"`
	QuestionID uuid.UUID   `json:"question_id"`
}

func (q *Queries) InsertDailyQuestion(ctx context.Context, arg InsertDailyQuestionParams) error {
	_, err := q.db.Exec(ctx, insertDailyQuestion, arg.Day, arg.QuestionID)
	return err
}

const listDailyQuestionCandidates = `-- name: ListDailyQuestionCandidates :many
SELECT q.id, (ex.fits)::bool AS explanation_fits
FROM question q
JOIN question_translation qu
  ON qu.question_id = q.id AND qu.locale = 'uz-Latn' AND qu.status = 'verified'
LEFT JOIN question_translation qr
  ON qr.question_id = q.id AND qr.locale = 'ru' AND qr.status = 'verified'
CROSS JOIN LATERAL (
  SELECT COUNT(*)::int AS answer_count,
         COUNT(*) FILTER (WHERE a.is_correct)::int AS correct_count,
         COALESCE(BOOL_OR(
           au.text IS NULL OR btrim(au.text) = ''
           OR char_length(au.text) > $1::int
           OR char_length(COALESCE(ar.text, au.text)) > $1::int
         ), true) AS has_bad_answer
  FROM answer a
  LEFT JOIN answer_translation au ON au.answer_id = a.id AND au.locale = 'uz-Latn' AND au.status = 'verified'
  LEFT JOIN answer_translation ar ON ar.answer_id = a.id AND ar.locale = 'ru' AND ar.status = 'verified'
  WHERE a.question_id = q.id
) ans
CROSS JOIN LATERAL (
  SELECT COALESCE(bool_and(char_length(t.txt) <= $2::int), false) AS fits
  FROM (
    SELECT (SELECT string_agg(b->>'text', ' ') FROM jsonb_array_elements(COALESCE(et.blocks, eu.blocks)) b) AS txt
    FROM explanation e
    JOIN explanation_translation eu ON eu.explanation_id = e.id AND eu.locale = 'uz-Latn' AND eu.status = 'verified'
    LEFT JOIN explanation_translation et ON et.explanation_id = e.id AND et.locale = 'ru' AND et.status = 'verified'
    WHERE e.question_id = q.id
    UNION ALL
    SELECT (SELECT string_agg(b->>'text', ' ') FROM jsonb_array_elements(eu.blocks) b)
    FROM explanation e
    JOIN explanation_translation eu ON eu.explanation_id = e.id AND eu.locale = 'uz-Latn' AND eu.status = 'verified'
    WHERE e.question_id = q.id
  ) t
) ex
LEFT JOIN LATERAL (
  SELECT MAX(dq.day) AS last_day FROM telegram_daily_question dq
  WHERE dq.question_id = q.id AND dq.day <> $3::date
) used ON true
WHERE q.validation_status = 'valid'
  AND btrim(qu.text) <> ''
  AND char_length(qu.text) <= $4::int
  AND char_length(COALESCE(qr.text, qu.text)) <= $4::int
  AND ans.answer_count BETWEEN 2 AND $5::int
  AND ans.correct_count = 1
  AND NOT ans.has_bad_answer
ORDER BY used.last_day ASC NULLS FIRST, ex.fits DESC, md5(q.id::text || $3::date::text)
LIMIT $6
`

type ListDailyQuestionCandidatesParams struct {
	MaxOptionLen      int32       `json:"max_option_len"`
	MaxExplanationLen int32       `json:"max_explanation_len"`
	Day               pgtype.Date `json:"day"`
	MaxQuestionLen    int32       `json:"max_question_len"`
	MaxOptions        int32       `json:"max_options"`
	LimitCount        int32       `json:"limit_count"`
}

type ListDailyQuestionCandidatesRow struct {
	ID              uuid.UUID `json:"id"`
	ExplanationFits bool      `json:"explanation_fits"`
}

// Questions that fit a Telegram quiz poll in both uz-Latn and ru (ru falls
// back to uz-Latn like GetQuestion): question <= 300 chars, 2..10 answers of
// <= 100 chars, exactly one correct. Never-used questions come first, then
// those whose explanation fits the poll's 200-char limit in both languages,
// then a per-day hash so the order is deterministic for a given day. Go
// re-checks the winner with buildPollRequest before using it.
func (q *Queries) ListDailyQuestionCandidates(ctx context.Context, arg ListDailyQuestionCandidatesParams) ([]ListDailyQuestionCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listDailyQuestionCandidates,
		arg.MaxOptionLen,
		arg.MaxExplanationLen,
		arg.Day,
		arg.MaxQuestionLen,
		arg.MaxOptions,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyQuestionCandidatesRow
	for rows.Next() {
		var i ListDailyQuestionCandidatesRow
		if err := rows.Scan(&i.ID, &i.ExplanationFits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTelegramReminderAudience = `-- name: ListTelegramReminderAudience :many
SELECT u.tg_user_id, u.first_name, u.language_code,
       (ta.tg_user_id IS NOT NULL)::bool AS linked,
       (ta.phone_verified_at IS NOT NULL)::bool AS phone_verified,
       COALESCE(s.current, 0)::int AS streak_current,
       s.last_active_date AS last_active_date,
       COALESCE(due.n, 0)::int AS due_count,
       COALESCE(tickets.n, 0)::int AS tickets_completed
FROM telegram_bot_user u
LEFT JOIN telegram_account ta ON ta.tg_user_id = u.tg_user_id
LEFT JOIN profile p ON p.id = ta.profile_id AND p.status = 'active'
LEFT JOIN streak s ON s.profile_id = p.id
LEFT JOIN LATERAL (
  SELECT COUNT(*) AS n
  FROM question_memory qm
  JOIN question q ON q.id = qm.question_id AND q.validation_status = 'valid'
  WHERE qm.profile_id = p.id AND qm.due_at <= now()
) due ON p.id IS NOT NULL
LEFT JOIN LATERAL (
  SELECT COUNT(*) AS n
  FROM variant_progress vp
  WHERE vp.profile_id = p.id AND vp.completed_at IS NOT NULL
) tickets ON p.id IS NOT NULL
WHERE u.reminders_enabled AND u.blocked_at IS NULL
  AND ($1::bigint IS NULL OR u.tg_user_id = $1::bigint)
ORDER BY u.tg_user_id
`

type ListTelegramReminderAudienceRow struct {
	TgUserID         int64       `json:"tg_user_id"`
	FirstName        string      `json:"first_name"`
	LanguageCode     string      `json:"language_code"`
	Linked           bool        `json:"linked"`
	PhoneVerified    bool        `json:"phone_verified"`
	StreakCurrent    int32       `json:"streak_current"`
	LastActiveDate   pgtype.Date `json:"last_active_date"`
	DueCount         int32       `json:"due_count"`
	TicketsCompleted int32       `json:"tickets_completed"`
}

// Personal-line inputs for eligible users: one user (after a claim) or all
// of them (dry-run). Profile numbers come only from an active profile; a
// link to a banned profile counts as linked with nothing to report.
func (q *Queries) ListTelegramReminderAudience(ctx context.Context, onlyTgUserID pgtype.Int8) ([]ListTelegramReminderAudienceRow, error) {
	rows, err := q.db.Query(ctx, listTelegramReminderAudience, onlyTgUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTelegramReminderAudienceRow
	for rows.Next() {
		var i ListTelegramReminderAudienceRow
		if err := rows.Scan(
			&i.TgUserID,
			&i.FirstName,
			&i.LanguageCode,
			&i.Linked,
			&i.PhoneVerified,
			&i.StreakCurrent,
			&i.LastActiveDate,
			&i.DueCount,
			&i.TicketsCompleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTelegramBotUserBlocked = `-- name: MarkTelegramBotUserBlocked :exec
INSERT INTO telegram_bot_user (tg_user_id, blocked_at)
VALUES ($1, now())
ON CONFLICT (tg_user_id) DO UPDATE SET blocked_at = now()
`

// my_chat_member kicked in the private chat, or a 403 on send.
func (q *Queries) MarkTelegramBotUserBlocked(ctx context.Context, tgUserID int64) error {
	_, err := q.db.Exec(ctx, markTelegramBotUserBlocked, tgUserID)
	return err
}

const toggleTelegramReminders = `-- name: ToggleTelegramReminders :one
INSERT INTO telegram_bot_user (tg_user_id, reminders_enabled)
VALUES ($1, false)
ON CONFLICT (tg_user_id) DO UPDATE
  SET reminders_enabled = NOT telegram_bot_user.reminders_enabled
RETURNING reminders_enabled
`

// /eslatma. A user without a row has the default (on), so toggling inserts off.
func (q *Queries) ToggleTelegramReminders(ctx context.Context, tgUserID int64) (bool, error) {
	row := q.db.QueryRow(ctx, toggleTelegramReminders, tgUserID)
	var reminders_enabled bool
	err := row.Scan(&reminders_enabled)
	return reminders_enabled, err
}

const upsertTelegramBotUser = `-- name: UpsertTelegramBotUser :exec
INSERT INTO telegram_bot_user (tg_user_id, first_name, username, language_code)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tg_user_id) DO UPDATE SET
  first_name    = EXCLUDED.first_name,
  username      = EXCLUDED.username,
  language_code = EXCLUDED.language_code,
  last_seen_at  = now(),
  blocked_at    = NULL
WHERE telegram_bot_user.blocked_at IS NOT NULL
   OR telegram_bot_user.last_seen_at < now() - interval '1 minute'
   OR telegram_bot_user.first_name    IS DISTINCT FROM EXCLUDED.first_name
   OR telegram_bot_user.username      IS DISTINCT FROM EXCLUDED.username
   OR telegram_bot_user.language_code IS DISTINCT FROM EXCLUDED.language_code
`

type UpsertTelegramBotUserParams struct {
	TgUserID     int64  `json:"tg_user_id"`
	FirstName    string `json:"first_name"`
	Username     string `json:"username"`
	LanguageCode string `json:"language_code"`
}

// Every private-chat update. Any update from the user proves the chat is
// open again, so blocked_at is cleared. The WHERE skips the write when
// nothing changed and the row was touched in the last minute, so a busy
// chat does not turn into one row rewrite per message.
func (q *Queries) UpsertTelegramBotUser(ctx context.Context, arg UpsertTelegramBotUserParams) error {
	_, err := q.db.Exec(ctx, upsertTelegramBotUser,
		arg.TgUserID,
		arg.FirstName,
		arg.Username,
		arg.LanguageCode,
	)
	return err
}
