DROP TABLE IF EXISTS admin_audit_log CASCADE;
DROP TABLE IF EXISTS admin_session CASCADE;
DROP TABLE IF EXISTS admin_user_role CASCADE;
DROP TABLE IF EXISTS admin_role_permission CASCADE;
DROP TABLE IF EXISTS admin_permission CASCADE;
DROP TABLE IF EXISTS admin_role CASCADE;
DROP TABLE IF EXISTS admin_user CASCADE;
