DROP TRIGGER IF EXISTS manual_pay_assignment_atomic_audit ON manual_pay_assignment;
DROP TRIGGER IF EXISTS manual_pay_card_atomic_audit ON manual_pay_card;
DROP TRIGGER IF EXISTS manual_tg_settings_atomic_audit ON manual_tg_settings;
DROP TRIGGER IF EXISTS referral_ledger_atomic_audit ON referral_ledger;
DROP TRIGGER IF EXISTS referral_payout_atomic_audit ON referral_payout;
DROP TRIGGER IF EXISTS b2b_invite_atomic_audit ON b2b_invite;
DROP TRIGGER IF EXISTS b2b_org_license_atomic_audit ON b2b_org_license;
DROP TRIGGER IF EXISTS b2b_org_member_atomic_audit ON b2b_org_member;
DROP TRIGGER IF EXISTS b2b_org_atomic_audit ON b2b_org;
DROP TRIGGER IF EXISTS support_ticket_atomic_audit ON support_ticket;
DROP TRIGGER IF EXISTS site_settings_atomic_audit ON site_settings;
DROP TRIGGER IF EXISTS limit_config_atomic_audit ON limit_config;
DROP TRIGGER IF EXISTS feature_flag_atomic_audit ON feature_flag;
DROP TRIGGER IF EXISTS payment_provider_status_atomic_audit ON payment_provider_status;
DROP TRIGGER IF EXISTS payment_atomic_audit ON payment;
DROP TRIGGER IF EXISTS explanation_translation_atomic_audit ON explanation_translation;
DROP TRIGGER IF EXISTS explanation_atomic_audit ON explanation;
DROP TRIGGER IF EXISTS answer_translation_atomic_audit ON answer_translation;
DROP TRIGGER IF EXISTS answer_atomic_audit ON answer;
DROP TRIGGER IF EXISTS question_translation_atomic_audit ON question_translation;
DROP TRIGGER IF EXISTS question_atomic_audit ON question;
DROP TRIGGER IF EXISTS entitlement_atomic_audit ON entitlement;
DROP TRIGGER IF EXISTS profile_atomic_audit ON profile;
DROP FUNCTION IF EXISTS write_atomic_audit_fallback();
DROP TRIGGER IF EXISTS content_revision_immutable ON content_revision;
DROP TRIGGER IF EXISTS admin_audit_log_immutable ON admin_audit_log;
DROP FUNCTION IF EXISTS reject_immutable_row_change();
