-- Stop treating one hwid_hash as one physical machine.
--
-- hwid_hash is sha256("machineguid:" || MachineGuid). MachineGuid is
-- regenerated by sysprep, but NOT by a raw disk clone -- and a raw disk clone
-- is how a classroom of fifty identical PCs is actually built. On 2026-08-26 a
-- 55-seat school enrolled 43 stations that presented six distinct hwid_hashes
-- between them; this index let exactly one of each stay active, so 37
-- classroom PCs were kicked off the licence by their own classmates, each
-- losing VIP the instant it lost status = 'active'.
--
-- The index was there to stop one machine consuming many seats. That job now
-- belongs to EnrollStation, which reclaims a seat only from a station that has
-- stopped talking to the backend -- something a live classroom PC never does.
-- What must still be impossible is the same *installation* holding two active
-- rows, and an installation is identified by its keypair, not by its disk
-- image: every PC generates its own Ed25519 key on first run.
--
-- Token authentication does not rely on this index in any way. It looks a
-- station up by id and compares that row's own public_key and hwid_hash
-- (see b2b.Auth.Token), so the key-theft binding is unchanged.
DROP INDEX b2b_station_active_hwid_uidx;

CREATE UNIQUE INDEX b2b_station_active_hwid_key_uidx
  ON b2b_station (hwid_hash, public_key) WHERE status = 'active';
