package main

// Authoritative road-sign catalogue for Uzbekistan (YHQ 1-ilova). Sign codes,
// group membership and official names are a published state standard — factual
// data, not authored content. Names are provided in uz-Latn and ru, both taken
// verbatim from official/authoritative sources, cross-checked across at least
// two independent sources per group:
//
//   - uz-Latn: prava.uz (Uzbek PDD Appendix 1), pdd-uzbeki.narod.ru,
//     uzavtoyolbelgi.uz, uz.wikipedia.
//   - ru: prava.uz and 24pdd.uz (the Russian editions of the SAME Uzbek rules,
//     so they share Uzbekistan's numbering), cross-checked against nrm.uz
//     (legislative text) and GOST catalogues.
//
// IMPORTANT: Uzbekistan uses the older Soviet GOST 10807-78 numbering, NOT the
// modern Russian GOST R 52290-2004 scheme. Codes therefore must be aligned to
// the Uzbek rules' own Russian edition (prava.uz / 24pdd.uz), not to modern
// ru.wikipedia — the two diverge past ~1.16. Signs that appear only on vendor
// catalogues (e.g. a "4.10 horse path") but not in the live official rules are
// deliberately excluded rather than shipped unverified.
//
// uz-Cyrl is deliberately omitted for now: Uzbek Latin→Cyrillic has genuinely
// ambiguous cases (word-initial e→э vs е) that would risk shipping a wrong
// reading, and the read path already falls uz-Cyrl back to uz-Latn. Cyrillic
// will be added as a separately reviewed pass, not guessed here.

// group codes must match the frontend filter values exactly
// (frontend/src/app/[locale]/(app)/signs/page.tsx).
var groups = []groupSeed{
	{Code: "warning", Sort: 1, NameLatn: "Ogohlantiruvchi belgilar", NameRu: "Предупреждающие знаки"},
	{Code: "priority", Sort: 2, NameLatn: "Imtiyoz belgilari", NameRu: "Знаки приоритета"},
	{Code: "prohibiting", Sort: 3, NameLatn: "Taqiqlovchi belgilar", NameRu: "Запрещающие знаки"},
	{Code: "mandatory", Sort: 4, NameLatn: "Buyuruvchi belgilar", NameRu: "Предписывающие знаки"},
	{Code: "info", Sort: 5, NameLatn: "Axborot-ko'rsatgich belgilari", NameRu: "Информационно-указательные знаки"},
	{Code: "service", Sort: 6, NameLatn: "Servis belgilari", NameRu: "Знаки сервиса"},
	{Code: "supplementary", Sort: 7, NameLatn: "Qo'shimcha axborot belgilari", NameRu: "Знаки дополнительной информации"},
}

// signs is the catalogue. Each entry's uz-Latn and ru name was read off a
// fetched authoritative page (not invented); codes follow the Uzbek numbering.
var signs = []signSeed{

	// warning group
	{Code: "1.1", Group: "warning", NameLatn: "Shlagbaumli temir yo'l kesishmasi", NameRu: "Железнодорожный переезд со шлагбаумом", Image: "images/1.1.png"},
	{Code: "1.2", Group: "warning", NameLatn: "Shlagbaumsiz temir yo'l kesishmasi", NameRu: "Железнодорожный переезд без шлагбаума", Image: "images/1.2.png"},
	{Code: "1.3.1", Group: "warning", NameLatn: "Bir izli temir yo'l", NameRu: "Однопутная железная дорога", Image: "images/1.3.1.png"},
	{Code: "1.3.2", Group: "warning", NameLatn: "Ko'p izli temir yo'l", NameRu: "Многопутная железная дорога", Image: "images/1.3.2.png"},
	{Code: "1.4.1", Group: "warning", NameLatn: "Temir yo'l kesishmasiga yaqinlashuv", NameRu: "Приближение к железнодорожному переезду", Image: "images/1.4.1.png"},
	{Code: "1.4.2", Group: "warning", NameLatn: "Temir yo'l kesishmasiga yaqinlashuv", NameRu: "Приближение к железнодорожному переезду", Image: "images/1.4.2.png"},
	{Code: "1.4.3", Group: "warning", NameLatn: "Temir yo'l kesishmasiga yaqinlashuv", NameRu: "Приближение к железнодорожному переезду", Image: "images/1.4.3.png"},
	{Code: "1.4.4", Group: "warning", NameLatn: "Temir yo'l kesishmasiga yaqinlashuv", NameRu: "Приближение к железнодорожному переезду", Image: "images/1.4.4.png"},
	{Code: "1.4.5", Group: "warning", NameLatn: "Temir yo'l kesishmasiga yaqinlashuv", NameRu: "Приближение к железнодорожному переезду", Image: "images/1.4.5.png"},
	{Code: "1.4.6", Group: "warning", NameLatn: "Temir yo'l kesishmasiga yaqinlashuv", NameRu: "Приближение к железнодорожному переезду", Image: "images/1.4.6.png"},
	{Code: "1.5", Group: "warning", NameLatn: "Tramvay yo'li bilan kesishuv", NameRu: "Пересечение с трамвайной линией", Image: "images/1.5.png"},
	{Code: "1.6", Group: "warning", NameLatn: "Teng ahamiyatli yo'llar kesishuvi", NameRu: "Пересечение равнозначных дорог", Image: "images/1.6.png"},
	{Code: "1.7", Group: "warning", NameLatn: "Aylanma harakatlanish bilan kesishuv", NameRu: "Пересечение с круговым движением", Image: "images/1.7.png"},
	{Code: "1.8", Group: "warning", NameLatn: "Svetofor tartibga soladi", NameRu: "Светофорное регулирование", Image: "images/1.8.png"},
	{Code: "1.9", Group: "warning", NameLatn: "Ko'tarma ko'prik", NameRu: "Разводной мост", Image: "images/1.9.png"},
	{Code: "1.10", Group: "warning", NameLatn: "Sohilga chiqish", NameRu: "Выезд на набережную", Image: "images/1.10.png"},
	{Code: "1.11.1", Group: "warning", NameLatn: "Xavfli burilish (o'ngga)", NameRu: "Опасный поворот (направо)", Image: "images/1.11.1.png"},
	{Code: "1.11.2", Group: "warning", NameLatn: "Xavfli burilish (chapga)", NameRu: "Опасный поворот (налево)", Image: "images/1.11.2.png"},
	{Code: "1.12.1", Group: "warning", NameLatn: "Xavfli burilishlar (birinchi o'ngga)", NameRu: "Опасные повороты (первый направо)", Image: "images/1.12.1.png"},
	{Code: "1.12.2", Group: "warning", NameLatn: "Xavfli burilishlar (birinchi chapga)", NameRu: "Опасные повороты (первый налево)", Image: "images/1.12.2.png"},
	{Code: "1.13", Group: "warning", NameLatn: "Tik nishablik", NameRu: "Крутой спуск", Image: "images/1.13.png"},
	{Code: "1.14", Group: "warning", NameLatn: "Tik balandlik", NameRu: "Крутой подъем", Image: "images/1.14.png"},
	{Code: "1.15", Group: "warning", NameLatn: "Sirpanchiq yo'l", NameRu: "Скользкая дорога", Image: "images/1.15.png"},
	{Code: "1.16", Group: "warning", NameLatn: "Notekis yo'l", NameRu: "Неровная дорога", Image: "images/1.16.png"},
	{Code: "1.17", Group: "warning", NameLatn: "Tosh otilish xavfi", NameRu: "Выброс гравия", Image: "images/1.17.png"},
	{Code: "1.18.1", Group: "warning", NameLatn: "Yo'lning torayishi", NameRu: "Сужение дороги (с обеих сторон)", Image: "images/1.18.1.png"},
	{Code: "1.18.2", Group: "warning", NameLatn: "Yo'lning torayishi (o'ngga)", NameRu: "Сужение дороги (справа)", Image: "images/1.18.2.png"},
	{Code: "1.18.3", Group: "warning", NameLatn: "Yo'lning torayishi (chapga)", NameRu: "Сужение дороги (слева)", Image: "images/1.18.3.png"},
	{Code: "1.19", Group: "warning", NameLatn: "Ikki tomonlama harakatlanish", NameRu: "Двустороннее движение", Image: "images/1.19.png"},
	{Code: "1.20", Group: "warning", NameLatn: "Piyodalar o'tish joyi", NameRu: "Пешеходный переход", Image: "images/1.20.png"},
	{Code: "1.21", Group: "warning", NameLatn: "Bolalar", NameRu: "Дети", Image: "images/1.21.png"},
	{Code: "1.22", Group: "warning", NameLatn: "Velosiped yo'lkasi bilan kesishuv", NameRu: "Пересечение с велосипедной дорожкой", Image: "images/1.22.png"},
	{Code: "1.23", Group: "warning", NameLatn: "Ta'mirlash ishlari", NameRu: "Дорожные работы", Image: "images/1.23.png"},
	{Code: "1.24", Group: "warning", NameLatn: "Mol haydab o'tish", NameRu: "Перегон скота", Image: "images/1.24.png"},
	{Code: "1.25", Group: "warning", NameLatn: "Yovvoyi hayvonlar", NameRu: "Дикие животные", Image: "images/1.25.png"},
	{Code: "1.25.2", Group: "warning", NameLatn: "Pastlab uchuvchi qushlar", NameRu: "Низколетящие птицы", Image: "images/1.25.2.png"},
	{Code: "1.25.3", Group: "warning", NameLatn: "Kemiruvchi va sudralib yuruvchi hayvonlar", NameRu: "Грызуны и пресмыкающиеся животные", Image: "images/1.25.3.png"},
	{Code: "1.26", Group: "warning", NameLatn: "Toshlar tushishi", NameRu: "Падение камней", Image: "images/1.26.png"},
	{Code: "1.27", Group: "warning", NameLatn: "Yonlama shamol", NameRu: "Боковой ветер", Image: "images/1.27.png"},
	{Code: "1.28", Group: "warning", NameLatn: "Pastlab uchuvchi samolyotlar", NameRu: "Низколетящие самолеты", Image: "images/1.28.png"},
	{Code: "1.29", Group: "warning", NameLatn: "Tonnel", NameRu: "Тоннель", Image: "images/1.29.png"},
	{Code: "1.30", Group: "warning", NameLatn: "Boshqa xavf-xatar", NameRu: "Прочие опасности", Image: "images/1.30.png"},
	{Code: "1.31", Group: "warning", NameLatn: "Sun'iy yo'l notekisligi", NameRu: "Искусственная неровность дороги", Image: "images/1.31.png"},
	{Code: "1.31.1", Group: "warning", NameLatn: "Burilishning yo'nalishi", NameRu: "Направление поворота", Image: "images/1.31.1.png"},
	{Code: "1.31.2", Group: "warning", NameLatn: "Burilishning yo'nalishi", NameRu: "Направление поворота", Image: "images/1.31.2.png"},
	{Code: "1.31.3", Group: "warning", NameLatn: "Burilishning yo'nalishi", NameRu: "Направление поворота", Image: "images/1.31.3.png"},
	{Code: "1.32", Group: "warning", NameLatn: "Tirbandlik", NameRu: "Затор", Image: "images/1.32.png"},
	{Code: "1.33", Group: "warning", NameLatn: "Qatnov qismi kesishmasi hududi", NameRu: "Территория пересечения проезжих частей", Image: "images/1.33.png"},
	{Code: "1.34", Group: "warning", NameLatn: "Diqqat, boshqariladigan to'siq", NameRu: "Внимание, управляемое заградительное устройство", Image: "images/1.34.png"},
	{Code: "1.35", Group: "warning", NameLatn: "Piyodalarning yo'l yoqasidan yurishi mumkin bo'lgan hudud", NameRu: "Территория, где пешеходы могут двигаться по обочине", Image: "images/1.35.png"},

	// priority group
	{Code: "2.1", Group: "priority", NameLatn: "Asosiy yo'l", NameRu: "Главная дорога", Image: "images/2.1.png"},
	{Code: "2.2", Group: "priority", NameLatn: "Asosiy yo'lning oxiri", NameRu: "Конец главной дороги", Image: "images/2.2.png"},
	{Code: "2.3.1", Group: "priority", NameLatn: "Ikkinchi darajali yo'l bilan kesishuv", NameRu: "Пересечение со второстепенной дорогой", Image: "images/2.3.1.png"},
	{Code: "2.3.2", Group: "priority", NameLatn: "Ikkinchi darajali yo'lning o'ngdan tutashuvi", NameRu: "Примыкание второстепенной дороги справа", Image: "images/2.3.2.png"},
	{Code: "2.3.3", Group: "priority", NameLatn: "Ikkinchi darajali yo'lning chapdan tutashuvi", NameRu: "Примыкание второстепенной дороги слева", Image: "images/2.3.3.png"},
	{Code: "2.4", Group: "priority", NameLatn: "Yo'l bering", NameRu: "Уступите дорогу", Image: "images/2.4.png"},
	{Code: "2.5", Group: "priority", NameLatn: "To'xtamasdan harakatlanish taqiqlangan", NameRu: "Движение без остановки запрещено", Image: "images/2.5.png"},
	{Code: "2.6", Group: "priority", NameLatn: "Qarama-qarshi harakatning ustunligi", NameRu: "Преимущество встречного движения", Image: "images/2.6.png"},
	{Code: "2.7", Group: "priority", NameLatn: "Qarama-qarshi harakatga nisbatan ustunlik", NameRu: "Преимущество перед встречным движением", Image: "images/2.7.png"},

	// prohibiting group
	{Code: "3.1", Group: "prohibiting", NameLatn: "Kirish taqiqlangan", NameRu: "Въезд запрещён", Image: "images/3.1.png"},
	{Code: "3.2", Group: "prohibiting", NameLatn: "Harakatlanish taqiqlangan", NameRu: "Движение запрещено", Image: "images/3.2.png"},
	{Code: "3.3", Group: "prohibiting", NameLatn: "Mexanik transport vositalarining harakatlanishi taqiqlangan", NameRu: "Движение механических транспортных средств запрещено", Image: "images/3.3.png"},
	{Code: "3.4", Group: "prohibiting", NameLatn: "Yuk avtomobillarining harakatlanishi taqiqlangan", NameRu: "Движение грузовых автомобилей запрещено", Image: "images/3.4.png"},
	{Code: "3.5", Group: "prohibiting", NameLatn: "Mototsikllar harakatlanishi taqiqlangan", NameRu: "Движение мотоциклов запрещено", Image: "images/3.5.png"},
	{Code: "3.6", Group: "prohibiting", NameLatn: "Traktorlar harakatlanishi taqiqlangan", NameRu: "Движение тракторов запрещено", Image: "images/3.6.png"},
	{Code: "3.7", Group: "prohibiting", NameLatn: "Tirkama bilan harakatlanish taqiqlangan", NameRu: "Движение с прицепом запрещено", Image: "images/3.7.png"},
	{Code: "3.8", Group: "prohibiting", NameLatn: "Ot-arava harakatlanishi taqiqlangan", NameRu: "Движение гужевых повозок запрещено", Image: "images/3.8.png"},
	{Code: "3.9", Group: "prohibiting", NameLatn: "Velosipedda harakatlanish taqiqlangan", NameRu: "Движение на велосипедах запрещено", Image: "images/3.9.png"},
	{Code: "3.10", Group: "prohibiting", NameLatn: "Piyodalarning harakatlanishi taqiqlangan", NameRu: "Движение пешеходов запрещено", Image: "images/3.10.png"},
	{Code: "3.11", Group: "prohibiting", NameLatn: "Vazn cheklangan", NameRu: "Ограничение массы", Image: "images/3.11.png"},
	{Code: "3.12", Group: "prohibiting", NameLatn: "O'qqa tushadigan og'irlik cheklangan", NameRu: "Ограничение массы, приходящейся на ось транспортного средства", Image: "images/3.12.png"},
	{Code: "3.13", Group: "prohibiting", NameLatn: "Cheklangan balandlik", NameRu: "Ограничение высоты", Image: "images/3.13.png"},
	{Code: "3.14", Group: "prohibiting", NameLatn: "Cheklangan kenglik", NameRu: "Ограничение ширины", Image: "images/3.14.png"},
	{Code: "3.15", Group: "prohibiting", NameLatn: "Cheklangan uzunlik", NameRu: "Ограничение длины", Image: "images/3.15.png"},
	{Code: "3.16", Group: "prohibiting", NameLatn: "Eng kam oraliq", NameRu: "Ограничение минимальной дистанции", Image: "images/3.16.png"},
	{Code: "3.17.1", Group: "prohibiting", NameLatn: "Bojxona", NameRu: "Таможня", Image: "images/3.17.1.png"},
	{Code: "3.17.2", Group: "prohibiting", NameLatn: "Xavf-xatar", NameRu: "Опасность", Image: "images/3.17.2.png"},
	{Code: "3.17.3", Group: "prohibiting", NameLatn: "Nazorat joyi", NameRu: "Контроль", Image: "images/3.17.3.png"},
	{Code: "3.18.1", Group: "prohibiting", NameLatn: "O'ngga burilish taqiqlanadi", NameRu: "Поворот направо запрещён", Image: "images/3.18.1.png"},
	{Code: "3.18.2", Group: "prohibiting", NameLatn: "Chapga burilish taqiqlanadi", NameRu: "Поворот налево запрещён", Image: "images/3.18.2.png"},
	{Code: "3.19", Group: "prohibiting", NameLatn: "Qayrilish taqiqlanadi", NameRu: "Разворот запрещён", Image: "images/3.19.png"},
	{Code: "3.20", Group: "prohibiting", NameLatn: "Quvib o'tish taqiqlanadi", NameRu: "Обгон запрещён", Image: "images/3.20.png"},
	{Code: "3.21", Group: "prohibiting", NameLatn: "Quvib o'tish taqiqlangan hududning oxiri", NameRu: "Конец зоны запрещения обгона", Image: "images/3.21.png"},
	{Code: "3.22", Group: "prohibiting", NameLatn: "Yuk avtomobillarida quvib o'tish taqiqlangan", NameRu: "Обгон грузовым автомобилям запрещён", Image: "images/3.22.png"},
	{Code: "3.23", Group: "prohibiting", NameLatn: "Yuk avtomobillarida quvib o'tish taqiqlangan hududning oxiri", NameRu: "Конец зоны запрещения обгона грузовым автомобилям", Image: "images/3.23.png"},
	{Code: "3.24", Group: "prohibiting", NameLatn: "Yuqori tezlik cheklangan", NameRu: "Ограничение максимальной скорости", Image: "images/3.24.png"},
	{Code: "3.25", Group: "prohibiting", NameLatn: "Yuqori tezlik cheklangan hududning oxiri", NameRu: "Конец зоны ограничения максимальной скорости", Image: "images/3.25.png"},
	{Code: "3.26", Group: "prohibiting", NameLatn: "Tovush moslamalaridan foydalanish taqiqlangan", NameRu: "Подача звукового сигнала запрещена", Image: "images/3.26.png"},
	{Code: "3.27", Group: "prohibiting", NameLatn: "To'xtash taqiqlangan", NameRu: "Остановка запрещена", Image: "images/3.27.png"},
	{Code: "3.28", Group: "prohibiting", NameLatn: "To'xtab turish taqiqlangan", NameRu: "Стоянка запрещена", Image: "images/3.28.png"},
	{Code: "3.29", Group: "prohibiting", NameLatn: "Oyning toq kunlarida to'xtab turish taqiqlanadi", NameRu: "Стоянка запрещена по нечётным числам месяца", Image: "images/3.29.png"},
	{Code: "3.30", Group: "prohibiting", NameLatn: "Oyning juft kunlarida to'xtab turish taqiqlanadi", NameRu: "Стоянка запрещена по чётным числам месяца", Image: "images/3.30.png"},
	{Code: "3.31", Group: "prohibiting", NameLatn: "Barcha cheklovlarning oxiri", NameRu: "Конец зоны всех ограничений", Image: "images/3.31.png"},
	{Code: "3.32", Group: "prohibiting", NameLatn: "Xavfli yuk tashiyotgan transport vositasining harakati taqiqlangan", NameRu: "Движение транспортных средств с опасными грузами запрещено", Image: "images/3.32.png"},
	{Code: "3.33", Group: "prohibiting", NameLatn: "Portlovchi va tez alangalanuvchi yukni tashiyotgan transport vositasining harakati taqiqlangan", NameRu: "Движение транспортных средств с взрывчатыми и легковоспламеняющимися грузами запрещено", Image: "images/3.33.png"},
	{Code: "3.34", Group: "prohibiting", NameLatn: "Individual harakatlanish vositalarini boshqarish taqiqlangan", NameRu: "Движение средств индивидуальной мобильности запрещено", Image: "images/3.34.png"},
	{Code: "3.35", Group: "prohibiting", NameLatn: "Ekologik zona hududida «o'rta» va «zararli» ekologik toifalarga ega avtotransport vositalari harakatlanishi taqiqlangan", NameRu: "В экологической зоне движение автотранспортных средств, имеющих экологические категории «средняя» и «вредная», запрещено", Image: "images/3.35.png"},

	// mandatory group
	{Code: "4.1.1", Group: "mandatory", NameLatn: "Harakatlanish to'g'riga", NameRu: "Движение прямо", Image: "images/4.1.1.png"},
	{Code: "4.1.2", Group: "mandatory", NameLatn: "Harakatlanish o'ngga", NameRu: "Движение направо", Image: "images/4.1.2.png"},
	{Code: "4.1.3", Group: "mandatory", NameLatn: "Harakatlanish chapga", NameRu: "Движение налево", Image: "images/4.1.3.png"},
	{Code: "4.1.4", Group: "mandatory", NameLatn: "Harakatlanish to'g'riga yoki o'ngga", NameRu: "Движение прямо или направо", Image: "images/4.1.4.png"},
	{Code: "4.1.5", Group: "mandatory", NameLatn: "Harakatlanish to'g'riga yoki chapga", NameRu: "Движение прямо или налево", Image: "images/4.1.5.png"},
	{Code: "4.1.6", Group: "mandatory", NameLatn: "Harakatlanish o'ngga yoki chapga", NameRu: "Движение направо или налево", Image: "images/4.1.6.png"},
	{Code: "4.2.1", Group: "mandatory", NameLatn: "To'siqni o'ngdan chetlab o'tish", NameRu: "Объезд препятствия справа", Image: "images/4.2.1.png"},
	{Code: "4.2.2", Group: "mandatory", NameLatn: "To'siqni chapdan chetlab o'tish", NameRu: "Объезд препятствия слева", Image: "images/4.2.2.png"},
	{Code: "4.2.3", Group: "mandatory", NameLatn: "To'siqni o'ngdan yoki chapdan chetlab o'tish", NameRu: "Объезд препятствия справа или слева", Image: "images/4.2.3.png"},
	{Code: "4.3", Group: "mandatory", NameLatn: "Aylanma harakatlanish", NameRu: "Круговое движение", Image: "images/4.3.png"},
	{Code: "4.4", Group: "mandatory", NameLatn: "Yengil avtomobillar harakatlanadi", NameRu: "Движение легковых автомобилей", Image: "images/4.4.png"},
	{Code: "4.5", Group: "mandatory", NameLatn: "Velosiped yo'lkasi", NameRu: "Велосипедная дорожка", Image: "images/4.5.png"},
	{Code: "4.6", Group: "mandatory", NameLatn: "Piyodalar yo'lkasi", NameRu: "Пешеходная дорожка", Image: "images/4.6.png"},
	{Code: "4.6.1", Group: "mandatory", NameLatn: "Piyoda va velosipedlar birgalikda harakatlanish yo'li", NameRu: "Пешеходный и велосипедный коридор с совмещенным движением", Image: "images/4.6.1.png"},
	{Code: "4.6.2", Group: "mandatory", NameLatn: "Piyoda va velosipedlar birgalikda harakatlanish yo'li oxiri", NameRu: "Конец пешеходного и велосипедного коридора с совмещенным движением", Image: "images/4.6.2.png"},
	{Code: "4.6.3", Group: "mandatory", NameLatn: "Ajratilgan piyoda va velosiped harakatlanish yo'li", NameRu: "Пешеходный и велосипедный коридор с разделением движения", Image: "images/4.6.3.png"},
	{Code: "4.6.4", Group: "mandatory", NameLatn: "Ajratilgan piyoda va velosiped harakatlanish yo'li oxiri", NameRu: "Конец пешеходного и велосипедного коридора с разделением движения", Image: "images/4.6.4.png"},
	{Code: "4.6.5", Group: "mandatory", NameLatn: "Ajratilgan piyoda va velosiped harakatlanish yo'li", NameRu: "Пешеходный и велосипедный коридор с разделением движения", Image: "images/4.6.5.png"},
	{Code: "4.6.6", Group: "mandatory", NameLatn: "Ajratilgan piyoda va velosiped harakatlanish yo'li oxiri", NameRu: "Конец пешеходного и велосипедного коридора с разделением движения", Image: "images/4.6.6.png"},
	{Code: "4.7", Group: "mandatory", NameLatn: "Eng kam tezlik", NameRu: "Ограничение минимальной скорости", Image: "images/4.7.png"},
	{Code: "4.8", Group: "mandatory", NameLatn: "Eng kam tezlik belgilangan yo'lning oxiri", NameRu: "Конец зоны ограничения минимальной скорости", Image: "images/4.8.png"},
	{Code: "4.9.1", Group: "mandatory", NameLatn: "Transport vositalarining xavfli yuklar bilan harakatlanish yo'nalishi", NameRu: "Направление движения транспортных средств с опасными грузами", Image: "images/4.9.1.png"},
	{Code: "4.9.2", Group: "mandatory", NameLatn: "Transport vositalarining xavfli yuklar bilan harakatlanish yo'nalishi", NameRu: "Направление движения транспортных средств с опасными грузами", Image: "images/4.9.2.png"},
	{Code: "4.9.3", Group: "mandatory", NameLatn: "Transport vositalarining xavfli yuklar bilan harakatlanish yo'nalishi", NameRu: "Направление движения транспортных средств с опасными грузами", Image: "images/4.9.3.png"},

	// info group
	{Code: "5.1", Group: "info", NameLatn: "Avtomagistral", NameRu: "Автомагистраль", Image: "images/5.1.png"},
	{Code: "5.2", Group: "info", NameLatn: "Avtomagistralning oxiri", NameRu: "Конец автомагистрали", Image: "images/5.2.png"},
	{Code: "5.3", Group: "info", NameLatn: "Avtomobillar uchun mo'ljallangan yo'l", NameRu: "Дорога для автомобилей", Image: "images/5.3.png"},
	{Code: "5.4", Group: "info", NameLatn: "Avtomobillar uchun mo'ljallangan yo'lning oxiri", NameRu: "Конец дороги для автомобилей", Image: "images/5.4.png"},
	{Code: "5.5", Group: "info", NameLatn: "Bir tomonlama harakatlanish yo'li", NameRu: "Дорога с односторонним движением", Image: "images/5.5.png"},
	{Code: "5.6", Group: "info", NameLatn: "Bir tomonlama harakatlanish yo'lining oxiri", NameRu: "Конец дороги с односторонним движением", Image: "images/5.6.png"},
	{Code: "5.7.1", Group: "info", NameLatn: "Bir tomonlama harakatlanish yo'liga chiqish", NameRu: "Выезд на дорогу с односторонним движением", Image: "images/5.7.1.png"},
	{Code: "5.7.2", Group: "info", NameLatn: "Bir tomonlama harakatlanish yo'liga chiqish", NameRu: "Выезд на дорогу с односторонним движением", Image: "images/5.7.2.png"},
	{Code: "5.8.1", Group: "info", NameLatn: "Bo'laklar bo'yicha harakatlanish yo'nalishi", NameRu: "Направления движения по полосам", Image: "images/5.8.1.png"},
	{Code: "5.8.2", Group: "info", NameLatn: "Bo'lak bo'yicha harakatlanish yo'nalishi", NameRu: "Направления движения по полосе", Image: "images/5.8.2.png"},
	{Code: "5.8.3", Group: "info", NameLatn: "Bo'lakning boshlanishi", NameRu: "Начало полосы", Image: "images/5.8.3.png"},
	{Code: "5.8.4", Group: "info", NameLatn: "Bo'lakning boshlanishi", NameRu: "Начало полосы", Image: "images/5.8.4.png"},
	{Code: "5.8.5", Group: "info", NameLatn: "Bo'lak oxiri", NameRu: "Конец полосы", Image: "images/5.8.5.png"},
	{Code: "5.8.6", Group: "info", NameLatn: "Bo'lak oxiri", NameRu: "Конец полосы", Image: "images/5.8.6.png"},
	{Code: "5.8.7", Group: "info", NameLatn: "Bo'laklar bo'yicha harakatlanish yo'nalishi", NameRu: "Направление движения по полосам", Image: "images/5.8.7.png"},
	{Code: "5.8.8", Group: "info", NameLatn: "Bo'laklar bo'yicha harakatlanish yo'nalishi", NameRu: "Направление движения по полосам", Image: "images/5.8.8.png"},
	{Code: "5.9", Group: "info", NameLatn: "Belgilangan yo'nalishli transport vositalari uchun mo'ljallangan bo'lak", NameRu: "Полоса для маршрутных транспортных средств", Image: "images/5.9.png"},
	{Code: "5.10.1", Group: "info", NameLatn: "Belgilangan yo'nalishli transport vositalari uchun bo'lagi bor yo'l", NameRu: "Дорога с полосой для маршрутных транспортных средств", Image: "images/5.10.1.png"},
	{Code: "5.10.2", Group: "info", NameLatn: "Belgilangan yo'nalishli transport vositalari uchun bo'lagi bor yo'l", NameRu: "Выезд на дорогу с полосой для маршрутных транспортных средств", Image: "images/5.10.2.png"},
	{Code: "5.10.3", Group: "info", NameLatn: "Belgilangan yo'nalishli transport vositalari uchun bo'lagi bor yo'l", NameRu: "Выезд на дорогу с полосой для маршрутных транспортных средств", Image: "images/5.10.3.png"},
	{Code: "5.10.4", Group: "info", NameLatn: "Belgilangan yo'nalishli transport vositalari uchun bo'lagi bor yo'lning oxiri", NameRu: "Конец дороги с полосой для маршрутных транспортных средств", Image: "images/5.10.4.png"},
	{Code: "5.11.1", Group: "info", NameLatn: "Qayirilish joyi", NameRu: "Место для разворота", Image: "images/5.11.1.png"},
	{Code: "5.11.2", Group: "info", NameLatn: "Qayirilish oralig'i", NameRu: "Зона для разворота", Image: "images/5.11.2.png"},
	{Code: "5.12", Group: "info", NameLatn: "Avtobus va trolleybus to'xtash joyi", NameRu: "Место остановки автобуса и (или) троллейбуса", Image: "images/5.12.png"},
	{Code: "5.13", Group: "info", NameLatn: "Tramvay to'xtash joyi", NameRu: "Место остановки трамвая", Image: "images/5.13.png"},
	{Code: "5.14", Group: "info", NameLatn: "Taksi to'xtab turish joyi", NameRu: "Место стоянки легковых такси", Image: "images/5.14.png"},
	{Code: "5.15", Group: "info", NameLatn: "To'xtab turish joyi", NameRu: "Место стоянки", Image: "images/5.15.png"},
	{Code: "5.15.1", Group: "info", NameLatn: "Pullik to'xtab turish joyi", NameRu: "Платная стоянка", Image: "images/5.15.1.png"},
	{Code: "5.16.1", Group: "info", NameLatn: "Piyodalar o'tish joyi", NameRu: "Пешеходный переход", Image: "images/5.16.1.png"},
	{Code: "5.16.2", Group: "info", NameLatn: "Piyodalar o'tish joyi", NameRu: "Пешеходный переход", Image: "images/5.16.2.png"},
	{Code: "5.17.1", Group: "info", NameLatn: "Piyodalarning er ostidan o'tish joyi", NameRu: "Подземный пешеходный переход", Image: "images/5.17.1.png"},
	{Code: "5.17.2", Group: "info", NameLatn: "Piyodalarning er ostidan o'tish joyi", NameRu: "Подземный пешеходный переход", Image: "images/5.17.2.png"},
	{Code: "5.17.3", Group: "info", NameLatn: "Piyodalarning er ustidan o'tish joyi", NameRu: "Надземный пешеходный переход", Image: "images/5.17.3.png"},
	{Code: "5.17.4", Group: "info", NameLatn: "Piyodalarning er ustidan o'tish joyi", NameRu: "Надземный пешеходный переход", Image: "images/5.17.4.png"},
	{Code: "5.18", Group: "info", NameLatn: "Tavsiya etilgan tezlik", NameRu: "Рекомендуемая скорость", Image: "images/5.18.png"},
	{Code: "5.19.1", Group: "info", NameLatn: "Oxiri berk yo'l, ko'cha", NameRu: "Тупик", Image: "images/5.19.1.png"},
	{Code: "5.19.2", Group: "info", NameLatn: "Oxiri berk yo'l, ko'cha", NameRu: "Тупик", Image: "images/5.19.2.png"},
	{Code: "5.19.3", Group: "info", NameLatn: "Oxiri berk yo'l, ko'cha", NameRu: "Тупик", Image: "images/5.19.3.png"},
	{Code: "5.20.1", Group: "info", NameLatn: "Yo'nalishlarning dastlabki ko'rsatkichi", NameRu: "Предварительный указатель направлений", Image: "images/5.20.1.png"},
	{Code: "5.20.2", Group: "info", NameLatn: "Yo'nalishlarning dastlabki ko'rsatkichi", NameRu: "Предварительный указатель направлений", Image: "images/5.20.2.png"},
	{Code: "5.20.3", Group: "info", NameLatn: "Harakatlanish tasviri", NameRu: "Схема движения", Image: "images/5.20.3.png"},
	{Code: "5.21.1", Group: "info", NameLatn: "Yo'nalish ko'rsatkichi", NameRu: "Указатель направления", Image: "images/5.21.1.png"},
	{Code: "5.21.2", Group: "info", NameLatn: "Yo'nalishlar ko'rsatkichi", NameRu: "Указатель направлений", Image: "images/5.21.2.png"},
	{Code: "5.22", Group: "info", NameLatn: "Aholi yashaydigan joyning boshlanishi", NameRu: "Начало населенного пункта", Image: "images/5.22.png"},
	{Code: "5.23", Group: "info", NameLatn: "Aholi yashaydigan joyning oxiri", NameRu: "Конец населенного пункта", Image: "images/5.23.png"},
	{Code: "5.24", Group: "info", NameLatn: "Aholi yashaydigan joyning boshlanishi", NameRu: "Начало населенного пункта", Image: "images/5.24.png"},
	{Code: "5.25", Group: "info", NameLatn: "Aholi yashaydigan joyning oxiri", NameRu: "Конец населенного пункта", Image: "images/5.25.png"},
	{Code: "5.26", Group: "info", NameLatn: "Manzil nomi", NameRu: "Наименование объекта", Image: "images/5.26.png"},
	{Code: "5.27", Group: "info", NameLatn: "Masofalar ko'rsatkichi", NameRu: "Указатель расстояний", Image: "images/5.27.png"},
	{Code: "5.28", Group: "info", NameLatn: "Kilometr belgisi", NameRu: "Километровый знак", Image: "images/5.28.png"},
	{Code: "5.29.1", Group: "info", NameLatn: "Yo'l raqami", NameRu: "Номер дороги", Image: "images/5.29.1.png"},
	{Code: "5.29.2", Group: "info", NameLatn: "Yo'l raqami", NameRu: "Номер дороги", Image: "images/5.29.2.png"},
	{Code: "5.30.1", Group: "info", NameLatn: "Yuk avtomobillari uchun harakatlanish yo'nalishi", NameRu: "Направление движения для грузовых автомобилей", Image: "images/5.30.1.png"},
	{Code: "5.30.2", Group: "info", NameLatn: "Yuk avtomobillari uchun harakatlanish yo'nalishi", NameRu: "Направление движения для грузовых автомобилей", Image: "images/5.30.2.png"},
	{Code: "5.30.3", Group: "info", NameLatn: "Yuk avtomobillari uchun harakatlanish yo'nalishi", NameRu: "Направление движения для грузовых автомобилей", Image: "images/5.30.3.png"},
	{Code: "5.31", Group: "info", NameLatn: "Aylanib o'tish tasviri", NameRu: "Схема объезда", Image: "images/5.31.png"},
	{Code: "5.32.1", Group: "info", NameLatn: "Chetlab o'tish yo'nalishi", NameRu: "Направление объезда", Image: "images/5.32.1.png"},
	{Code: "5.32.2", Group: "info", NameLatn: "Chetlab o'tish yo'nalishi", NameRu: "Направление объезда", Image: "images/5.32.2.png"},
	{Code: "5.32.3", Group: "info", NameLatn: "Chetlab o'tish yo'nalishi", NameRu: "Направление объезда", Image: "images/5.32.3.png"},
	{Code: "5.33", Group: "info", NameLatn: "To'xtash chizig'i", NameRu: "Стоп-линия", Image: "images/5.33.png"},
	{Code: "5.34.1", Group: "info", NameLatn: "Boshqa qatnov qismiga qayta tizilishning boshlang'ich ko'rsatkichi", NameRu: "Предварительный указатель перестроения на другую проезжую часть", Image: "images/5.34.1.png"},
	{Code: "5.34.2", Group: "info", NameLatn: "Boshqa qatnov qismiga qayta tizilishning boshlang'ich ko'rsatkichi", NameRu: "Предварительный указатель перестроения на другую проезжую часть", Image: "images/5.34.2.png"},
	{Code: "5.35", Group: "info", NameLatn: "Reversiv harakatlanish", NameRu: "Реверсивное движение", Image: "images/5.35.png"},
	{Code: "5.36", Group: "info", NameLatn: "Reversiv harakatlanish oxiri", NameRu: "Конец реверсивного движения", Image: "images/5.36.png"},
	{Code: "5.37", Group: "info", NameLatn: "Reversiv harakatlanish yo'liga chiqish", NameRu: "Выезд на дорогу с реверсивным движением", Image: "images/5.37.png"},
	{Code: "5.38", Group: "info", NameLatn: "Turar-joy dahasi", NameRu: "Жилая зона", Image: "images/5.38.png"},
	{Code: "5.39", Group: "info", NameLatn: "Turar-joy dahasining oxiri", NameRu: "Конец жилой зоны", Image: "images/5.39.png"},
	{Code: "5.40", Group: "info", NameLatn: "Falokatli holatlar uchun kirish yo'li", NameRu: "Дорога для въезда в аварийных случаях", Image: "images/5.40.png"},
	{Code: "5.41", Group: "info", NameLatn: "Foto va video qayd etish", NameRu: "Фото и видео фиксация", Image: "images/5.41.png"},
	{Code: "5.42", Group: "info", NameLatn: "Qizil chiroqda o'ngga harakatlanish", NameRu: "Движение направо при красном сигнале", Image: "images/5.42.png"},
	{Code: "5.43", Group: "info", NameLatn: "Radar", NameRu: "Радар", Image: "images/5.43.png"},
	{Code: "5.44", Group: "info", NameLatn: "Velosipedchilar uchun tasma", NameRu: "Полоса для велосипедистов", Image: "images/5.44.png"},
	{Code: "5.45", Group: "info", NameLatn: "Velosipedchilar uchun tasmaning oxiri", NameRu: "Конец полосы для велосипедистов", Image: "images/5.45.png"},
	{Code: "5.46", Group: "info", NameLatn: "Maktab", NameRu: "Школа", Image: "images/5.46.png"},
	{Code: "5.47", Group: "info", NameLatn: "Turizm obyektlari yo'nalish ko'rsatgichi", NameRu: "Указатель направления туристического объекта", Image: "images/5.47.png"},
	{Code: "5.48", Group: "info", NameLatn: "Baland piyodalar o'tish joyi", NameRu: "Высокий пешеходный переход", Image: "images/5.48.png"},

	// service group
	{Code: "6.1", Group: "service", NameLatn: "Tibbiy yordam ko'rsatish joyi", NameRu: "Пункт медицинской помощи", Image: "images/6.1.png"},
	{Code: "6.2", Group: "service", NameLatn: "Shifoxona", NameRu: "Больница", Image: "images/6.2.png"},
	{Code: "6.3.1", Group: "service", NameLatn: "Avtomobillarga yonilg'i quyish shoxobchasi", NameRu: "Автомобильная заправочная станция", Image: "images/6.3.1.png"},
	{Code: "6.3.2", Group: "service", NameLatn: "Avtomobillarga ko'p tarmoqli yonilg'i quyish shoxobchasi", NameRu: "Многофункциональная автомобильная заправочная станция", Image: "images/6.3.2.png"},
	{Code: "6.3.3", Group: "service", NameLatn: "Elektromobillarni quvvatlash shoxobchasi", NameRu: "Зарядная станция для электромобилей", Image: "images/6.3.3.png"},
	{Code: "6.4", Group: "service", NameLatn: "Avtomobillarga texnik xizmat ko'rsatish joyi", NameRu: "Техническое обслуживание автомобилей", Image: "images/6.4.png"},
	{Code: "6.5", Group: "service", NameLatn: "Avtomobillarni yuvish joyi", NameRu: "Мойка автомобилей", Image: "images/6.5.png"},
	{Code: "6.6", Group: "service", NameLatn: "Telefon", NameRu: "Телефон", Image: "images/6.6.png"},
	{Code: "6.7", Group: "service", NameLatn: "Oshxona", NameRu: "Пункт питания", Image: "images/6.7.png"},
	{Code: "6.8", Group: "service", NameLatn: "Ichimlik suvi", NameRu: "Питьевая вода", Image: "images/6.8.png"},
	{Code: "6.9", Group: "service", NameLatn: "Mehmonxona yoki motel", NameRu: "Гостиница", Image: "images/6.9.png"},
	{Code: "6.10", Group: "service", NameLatn: "Kemping", NameRu: "Кемпинг", Image: "images/6.10.png"},
	{Code: "6.11", Group: "service", NameLatn: "Dam olish joyi", NameRu: "Место отдыха", Image: "images/6.11.png"},
	{Code: "6.12", Group: "service", NameLatn: "YPX maskani", NameRu: "Пост ДПС", Image: "images/6.12.png"},
	{Code: "6.13", Group: "service", NameLatn: "Avtotashuvchilarning nazorat punkti", NameRu: "Контрольный пункт международных автоперевозчиков", Image: "images/6.13.png"},
	{Code: "6.14", Group: "service", NameLatn: "Hojatxona", NameRu: "Туалет", Image: "images/6.14.png"},
	{Code: "6.15", Group: "service", NameLatn: "Chiqindi yig'ish joyi", NameRu: "Место сбора мусора", Image: "images/6.15.png"},
	{Code: "6.16", Group: "service", NameLatn: "Cho'milish havzasi", NameRu: "Водоем для купания", Image: "images/6.16.png"},
	{Code: "6.17", Group: "service", NameLatn: "Ichki ishlar bo'limi", NameRu: "Отдел внутренних дел", Image: "images/6.17.png"},
	{Code: "6.18", Group: "service", NameLatn: "Radio aloqasi", NameRu: "Радиосвязь", Image: "images/6.18.png"},
	{Code: "6.19", Group: "service", NameLatn: "Jome' masjidi", NameRu: "Соборная мечеть", Image: "images/6.19.png"},
	{Code: "6.20", Group: "service", NameLatn: "Cherkov", NameRu: "Церковь", Image: "images/6.20.png"},
	{Code: "6.21", Group: "service", NameLatn: "Ibodatxona", NameRu: "Молитвенный дом", Image: "images/6.21.png"},
	{Code: "6.22", Group: "service", NameLatn: "Temir yo'l vokzali", NameRu: "Железнодорожный вокзал", Image: "images/6.22.png"},
	{Code: "6.23", Group: "service", NameLatn: "Aeroport", NameRu: "Аэропорт", Image: "images/6.23.png"},
	{Code: "6.24", Group: "service", NameLatn: "Bozor", NameRu: "Рынок", Image: "images/6.24.png"},
	{Code: "6.25", Group: "service", NameLatn: "Turistik axborot markazi", NameRu: "Центр информации туризма", Image: "images/6.25.png"},
	{Code: "6.26", Group: "service", NameLatn: "Qo'riqxona", NameRu: "Заповедник", Image: "images/6.26.png"},
	{Code: "6.27", Group: "service", NameLatn: "Manzarali joy", NameRu: "Живописное место", Image: "images/6.27.png"},
	{Code: "6.28", Group: "service", NameLatn: "Me'morchilik yodgorligi", NameRu: "Памятник зодчества", Image: "images/6.28.png"},

	// supplementary group
	{Code: "7.1.1", Group: "supplementary", NameLatn: "Manzilgacha bo'lgan masofa", NameRu: "Расстояние до объекта", Image: "images/7.1.1.png"},
	{Code: "7.1.2", Group: "supplementary", NameLatn: "Manzilgacha bo'lgan masofa", NameRu: "Расстояние до объекта", Image: "images/7.1.2.png"},
	{Code: "7.1.3", Group: "supplementary", NameLatn: "Manzilgacha bo'lgan masofa", NameRu: "Расстояние до объекта", Image: "images/7.1.3.png"},
	{Code: "7.1.4", Group: "supplementary", NameLatn: "Manzilgacha bo'lgan masofa", NameRu: "Расстояние до объекта", Image: "images/7.1.4.png"},
	{Code: "7.2.1", Group: "supplementary", NameLatn: "Ta'sir oralig'i", NameRu: "Зона действия", Image: "images/7.2.1.png"},
	{Code: "7.2.2", Group: "supplementary", NameLatn: "Ta'sir oralig'i", NameRu: "Зона действия", Image: "images/7.2.2.png"},
	{Code: "7.2.3", Group: "supplementary", NameLatn: "Ta'sir oralig'i", NameRu: "Зона действия", Image: "images/7.2.3.png"},
	{Code: "7.2.4", Group: "supplementary", NameLatn: "Ta'sir oralig'i", NameRu: "Зона действия", Image: "images/7.2.4.png"},
	{Code: "7.2.5", Group: "supplementary", NameLatn: "Ta'sir oralig'i", NameRu: "Зона действия", Image: "images/7.2.5.png"},
	{Code: "7.2.6", Group: "supplementary", NameLatn: "Ta'sir oralig'i", NameRu: "Зона действия", Image: "images/7.2.6.png"},
	{Code: "7.3.1", Group: "supplementary", NameLatn: "Ta'sir yo'nalishlari", NameRu: "Направления действия", Image: "images/7.3.1.png"},
	{Code: "7.3.2", Group: "supplementary", NameLatn: "Ta'sir yo'nalishlari", NameRu: "Направления действия", Image: "images/7.3.2.png"},
	{Code: "7.3.3", Group: "supplementary", NameLatn: "Ta'sir yo'nalishlari", NameRu: "Направления действия", Image: "images/7.3.3.png"},
	{Code: "7.4.1", Group: "supplementary", NameLatn: "Transport vositasining turi", NameRu: "Вид транспортного средства", Image: "images/7.4.1.png"},
	{Code: "7.4.2", Group: "supplementary", NameLatn: "Transport vositasining turi", NameRu: "Вид транспортного средства", Image: "images/7.4.2.png"},
	{Code: "7.4.3", Group: "supplementary", NameLatn: "Transport vositasining turi", NameRu: "Вид транспортного средства", Image: "images/7.4.3.png"},
	{Code: "7.4.4", Group: "supplementary", NameLatn: "Transport vositasining turi", NameRu: "Вид транспортного средства", Image: "images/7.4.4.png"},
	{Code: "7.4.5", Group: "supplementary", NameLatn: "Transport vositasining turi", NameRu: "Вид транспортного средства", Image: "images/7.4.5.png"},
	{Code: "7.4.6", Group: "supplementary", NameLatn: "Transport vositasining turi", NameRu: "Вид транспортного средства", Image: "images/7.4.6.png"},
	{Code: "7.4.7", Group: "supplementary", NameLatn: "Transport vositasining turi", NameRu: "Вид транспортного средства", Image: "images/7.4.7.png"},
	{Code: "7.5.1", Group: "supplementary", NameLatn: "Shanba, yakshanba va bayram kunlari", NameRu: "Субботние, воскресные и праздничные дни", Image: "images/7.5.1.png"},
	{Code: "7.5.2", Group: "supplementary", NameLatn: "Ish kunlari", NameRu: "Рабочие дни", Image: "images/7.5.2.png"},
	{Code: "7.5.3", Group: "supplementary", NameLatn: "Hafta kunlari", NameRu: "Дни недели", Image: "images/7.5.3.png"},
	{Code: "7.5.4", Group: "supplementary", NameLatn: "Amal qilish vaqti", NameRu: "Время действия", Image: "images/7.5.4.png"},
	{Code: "7.5.5", Group: "supplementary", NameLatn: "Amal qilish vaqti", NameRu: "Время действия", Image: "images/7.5.5.png"},
	{Code: "7.5.6", Group: "supplementary", NameLatn: "Amal qilish vaqti", NameRu: "Время действия", Image: "images/7.5.6.png"},
	{Code: "7.5.7", Group: "supplementary", NameLatn: "Amal qilish vaqti", NameRu: "Время действия", Image: "images/7.5.7.png"},
	{Code: "7.6.1", Group: "supplementary", NameLatn: "Transport vositasini to'xtab turish joyiga qo'yish usuli", NameRu: "Способ постановки транспортного средства на стоянку", Image: "images/7.6.1.png"},
	{Code: "7.6.2", Group: "supplementary", NameLatn: "Transport vositasini to'xtab turish joyiga qo'yish usuli", NameRu: "Способ постановки транспортного средства на стоянку", Image: "images/7.6.2.png"},
	{Code: "7.6.3", Group: "supplementary", NameLatn: "Transport vositasini to'xtab turish joyiga qo'yish usuli", NameRu: "Способ постановки транспортного средства на стоянку", Image: "images/7.6.3.png"},
	{Code: "7.6.4", Group: "supplementary", NameLatn: "Transport vositasini to'xtab turish joyiga qo'yish usuli", NameRu: "Способ постановки транспортного средства на стоянку", Image: "images/7.6.4.png"},
	{Code: "7.6.5", Group: "supplementary", NameLatn: "Transport vositasini to'xtab turish joyiga qo'yish usuli", NameRu: "Способ постановки транспортного средства на стоянку", Image: "images/7.6.5.png"},
	{Code: "7.6.6", Group: "supplementary", NameLatn: "Transport vositasini to'xtab turish joyiga qo'yish usuli", NameRu: "Способ постановки транспортного средства на стоянку", Image: "images/7.6.6.png"},
	{Code: "7.6.7", Group: "supplementary", NameLatn: "Transport vositasini to'xtab turish joyiga qo'yish usuli", NameRu: "Способ постановки транспортного средства на стоянку", Image: "images/7.6.7.png"},
	{Code: "7.6.8", Group: "supplementary", NameLatn: "Transport vositasini to'xtab turish joyiga qo'yish usuli", NameRu: "Способ постановки транспортного средства на стоянку", Image: "images/7.6.8.png"},
	{Code: "7.6.9", Group: "supplementary", NameLatn: "Transport vositasini to'xtab turish joyiga qo'yish usuli", NameRu: "Способ постановки транспортного средства на стоянку", Image: "images/7.6.9.png"},
	{Code: "7.7", Group: "supplementary", NameLatn: "Yurgizgichni ishlatmasdan to'xtab turish joyi", NameRu: "Стоянка с неработающим двигателем", Image: "images/7.7.png"},
	{Code: "7.8", Group: "supplementary", NameLatn: "Pullik xizmat ko'rsatish joyi", NameRu: "Платные услуги", Image: "images/7.8.png"},
	{Code: "7.9", Group: "supplementary", NameLatn: "To'xtab turish muddati cheklangan", NameRu: "Ограничение продолжительности стоянки", Image: "images/7.9.png"},
	{Code: "7.10", Group: "supplementary", NameLatn: "Avtomobillarni ko'rikdan o'tkazish joyi", NameRu: "Место для осмотра автомобилей", Image: "images/7.10.png"},
	{Code: "7.11", Group: "supplementary", NameLatn: "To'la vazni cheklangan", NameRu: "Ограничение разрешенной максимальной массы", Image: "images/7.11.png"},
	{Code: "7.12", Group: "supplementary", NameLatn: "Xavfli yo'l yoqasi", NameRu: "Опасная обочина", Image: "images/7.12.png"},
	{Code: "7.13", Group: "supplementary", NameLatn: "Asosiy yo'lning yo'nalishi", NameRu: "Направление главной дороги", Image: "images/7.13.png"},
	{Code: "7.14", Group: "supplementary", NameLatn: "Harakatlanish bo'lagi", NameRu: "Полоса движения", Image: "images/7.14.png"},
	{Code: "7.15", Group: "supplementary", NameLatn: "Ko'zi ojiz piyodalar", NameRu: "Слепые пешеходы", Image: "images/7.15.png"},
	{Code: "7.16", Group: "supplementary", NameLatn: "Nam qoplama", NameRu: "Влажное покрытие", Image: "images/7.16.png"},
	{Code: "7.17", Group: "supplementary", NameLatn: "Nogironlar", NameRu: "Инвалиды", Image: "images/7.17.png"},
	{Code: "7.18", Group: "supplementary", NameLatn: "Nogironlar mustasno", NameRu: "Кроме инвалидов", Image: "images/7.18.png"},
	{Code: "7.19", Group: "supplementary", NameLatn: "Foto va video qayd etish", NameRu: "Фото и видео фиксация", Image: "images/7.19.png"},
	{Code: "7.20", Group: "supplementary", NameLatn: "Xavfli yuk toifasi", NameRu: "Класс опасного груза", Image: "images/7.20.png"},
	{Code: "7.21", Group: "supplementary", NameLatn: "Evakuator ishlamoqda", NameRu: "Работает эвакуатор", Image: "images/7.21.png"},
	{Code: "7.22.1", Group: "supplementary", NameLatn: "To'siq", NameRu: "Препятствие", Image: "images/7.22.1.png"},
	{Code: "7.22.2", Group: "supplementary", NameLatn: "To'siq", NameRu: "Препятствие", Image: "images/7.22.2.png"},
	{Code: "7.22.3", Group: "supplementary", NameLatn: "To'siq", NameRu: "Препятствие", Image: "images/7.22.3.png"},
	{Code: "7.23", Group: "supplementary", NameLatn: "Navbat bilan o'tish", NameRu: "Поочередный проезд", Image: "images/7.23.png"},
	{Code: "7.24", Group: "supplementary", NameLatn: "Transport vositasining davlat raqami", NameRu: "Государственный номер транспортного средства", Image: "images/7.24.png"},
	{Code: "7.25", Group: "supplementary", NameLatn: "Faqat xizmat avtomobillari", NameRu: "Только служебные автомобили", Image: "images/7.25.png"},
	{Code: "7.26", Group: "supplementary", NameLatn: "Sun'iy notekislik", NameRu: "Искусственная неровность", Image: "images/7.26.png"},
}
